// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 09 Feb 2023 23:47:41 PST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "vulkan/vulkan.h"
#include "vulkan/vulkan_beta.h"
#include "vk_wrapper.h"
#include "vk_bridge.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// PFN_vkDebugReportCallbackEXT_c918aac4 is a proxy for callback PFN_vkDebugReportCallbackEXT.
unsigned int PFN_vkDebugReportCallbackEXT_c918aac4(unsigned int flags, VkDebugReportObjectTypeEXT objectType, unsigned long long object, unsigned long long location, int messageCode, char* pLayerPrefix, char* pMessage, void* pUserData);

// PFN_vkDeviceMemoryReportCallbackEXT_e34d104c is a proxy for callback PFN_vkDeviceMemoryReportCallbackEXT.
void PFN_vkDeviceMemoryReportCallbackEXT_e34d104c(VkDeviceMemoryReportCallbackDataEXT* pCallbackData, void* pUserData);

