// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 16 May 2016 03:35:25 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

void* PFN_vkAllocationFunction_9c4c5852(void* pUserData, unsigned long int size, unsigned long int alignment, VkSystemAllocationScope allocationScope) {
	return pFNAllocationFunction9C4C5852(pUserData, size, alignment, allocationScope);
}

void* PFN_vkReallocationFunction_622801d0(void* pUserData, void* pOriginal, unsigned long int size, unsigned long int alignment, VkSystemAllocationScope allocationScope) {
	return pFNReallocationFunction622801D0(pUserData, pOriginal, size, alignment, allocationScope);
}

void PFN_vkFreeFunction_28edd2c6(void* pUserData, void* pMemory) {
	pFNFreeFunction28EDD2C6(pUserData, pMemory);
}

void PFN_vkInternalAllocationNotification_eadf4b16(void* pUserData, unsigned long int size, VkInternalAllocationType allocationType, VkSystemAllocationScope allocationScope) {
	pFNInternalAllocationNotificationEADF4B16(pUserData, size, allocationType, allocationScope);
}

void PFN_vkInternalFreeNotification_ce87d96(void* pUserData, unsigned long int size, VkInternalAllocationType allocationType, VkSystemAllocationScope allocationScope) {
	pFNInternalFreeNotificationCE87D96(pUserData, size, allocationType, allocationScope);
}

void PFN_vkVoidFunction_4cd0423b() {
	pFNVoidFunction4CD0423B();
}

VkResult PFN_vkCreateInstance_c4de473d(VkInstanceCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkInstance* pInstance) {
	return pFNCreateInstanceC4DE473D(pCreateInfo, pAllocator, pInstance);
}

void PFN_vkDestroyInstance_38a99281(VkInstance instance, VkAllocationCallbacks* pAllocator) {
	pFNDestroyInstance38A99281(instance, pAllocator);
}

VkResult PFN_vkEnumeratePhysicalDevices_1025caff(VkInstance instance, unsigned int* pPhysicalDeviceCount, VkPhysicalDevice* pPhysicalDevices) {
	return pFNEnumeratePhysicalDevices1025CAFF(instance, pPhysicalDeviceCount, pPhysicalDevices);
}

void PFN_vkGetPhysicalDeviceFeatures_be6387a0(VkPhysicalDevice physicalDevice, VkPhysicalDeviceFeatures* pFeatures) {
	pFNGetPhysicalDeviceFeaturesBE6387A0(physicalDevice, pFeatures);
}

void PFN_vkGetPhysicalDeviceFormatProperties_df58990e(VkPhysicalDevice physicalDevice, VkFormat format, VkFormatProperties* pFormatProperties) {
	pFNGetPhysicalDeviceFormatPropertiesDF58990E(physicalDevice, format, pFormatProperties);
}

VkResult PFN_vkGetPhysicalDeviceImageFormatProperties_1362d074(VkPhysicalDevice physicalDevice, VkFormat format, VkImageType _type, VkImageTiling tiling, unsigned int usage, unsigned int flags, VkImageFormatProperties* pImageFormatProperties) {
	return pFNGetPhysicalDeviceImageFormatProperties1362D074(physicalDevice, format, _type, tiling, usage, flags, pImageFormatProperties);
}

void PFN_vkGetPhysicalDeviceProperties_b4924563(VkPhysicalDevice physicalDevice, VkPhysicalDeviceProperties* pProperties) {
	pFNGetPhysicalDevicePropertiesB4924563(physicalDevice, pProperties);
}

void PFN_vkGetPhysicalDeviceQueueFamilyProperties_8aa13a90(VkPhysicalDevice physicalDevice, unsigned int* pQueueFamilyPropertyCount, VkQueueFamilyProperties* pQueueFamilyProperties) {
	pFNGetPhysicalDeviceQueueFamilyProperties8AA13A90(physicalDevice, pQueueFamilyPropertyCount, pQueueFamilyProperties);
}

void PFN_vkGetPhysicalDeviceMemoryProperties_2e4807f(VkPhysicalDevice physicalDevice, VkPhysicalDeviceMemoryProperties* pMemoryProperties) {
	pFNGetPhysicalDeviceMemoryProperties2E4807F(physicalDevice, pMemoryProperties);
}

VkResult PFN_vkCreateDevice_f58db1eb(VkPhysicalDevice physicalDevice, VkDeviceCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkDevice* pDevice) {
	return pFNCreateDeviceF58DB1EB(physicalDevice, pCreateInfo, pAllocator, pDevice);
}

void PFN_vkDestroyDevice_c9a9759c(VkDevice device, VkAllocationCallbacks* pAllocator) {
	pFNDestroyDeviceC9A9759C(device, pAllocator);
}

VkResult PFN_vkEnumerateInstanceExtensionProperties_43068f6e(char* pLayerName, unsigned int* pPropertyCount, VkExtensionProperties* pProperties) {
	return pFNEnumerateInstanceExtensionProperties43068F6E(pLayerName, pPropertyCount, pProperties);
}

VkResult PFN_vkEnumerateDeviceExtensionProperties_1f7c3436(VkPhysicalDevice physicalDevice, char* pLayerName, unsigned int* pPropertyCount, VkExtensionProperties* pProperties) {
	return pFNEnumerateDeviceExtensionProperties1F7C3436(physicalDevice, pLayerName, pPropertyCount, pProperties);
}

VkResult PFN_vkEnumerateInstanceLayerProperties_692027fa(unsigned int* pPropertyCount, VkLayerProperties* pProperties) {
	return pFNEnumerateInstanceLayerProperties692027FA(pPropertyCount, pProperties);
}

VkResult PFN_vkEnumerateDeviceLayerProperties_991fc1be(VkPhysicalDevice physicalDevice, unsigned int* pPropertyCount, VkLayerProperties* pProperties) {
	return pFNEnumerateDeviceLayerProperties991FC1BE(physicalDevice, pPropertyCount, pProperties);
}

void PFN_vkGetDeviceQueue_a2e8a65a(VkDevice device, unsigned int queueFamilyIndex, unsigned int queueIndex, VkQueue* pQueue) {
	pFNGetDeviceQueueA2E8A65A(device, queueFamilyIndex, queueIndex, pQueue);
}

VkResult PFN_vkQueueSubmit_e01486a5(VkQueue queue, unsigned int submitCount, VkSubmitInfo* pSubmits, VkFence fence) {
	return pFNQueueSubmitE01486A5(queue, submitCount, pSubmits, fence);
}

VkResult PFN_vkQueueWaitIdle_ce1a9277(VkQueue queue) {
	return pFNQueueWaitIdleCE1A9277(queue);
}

VkResult PFN_vkDeviceWaitIdle_beed6562(VkDevice device) {
	return pFNDeviceWaitIdleBEED6562(device);
}

VkResult PFN_vkAllocateMemory_4fe39399(VkDevice device, VkMemoryAllocateInfo* pAllocateInfo, VkAllocationCallbacks* pAllocator, VkDeviceMemory* pMemory) {
	return pFNAllocateMemory4FE39399(device, pAllocateInfo, pAllocator, pMemory);
}

void PFN_vkFreeMemory_80ce986a(VkDevice device, VkDeviceMemory memory, VkAllocationCallbacks* pAllocator) {
	pFNFreeMemory80CE986A(device, memory, pAllocator);
}

VkResult PFN_vkMapMemory_55d2603d(VkDevice device, VkDeviceMemory memory, unsigned long long offset, unsigned long long size, unsigned int flags, void** ppData) {
	return pFNMapMemory55D2603D(device, memory, offset, size, flags, ppData);
}

void PFN_vkUnmapMemory_2c1026ee(VkDevice device, VkDeviceMemory memory) {
	pFNUnmapMemory2C1026EE(device, memory);
}

VkResult PFN_vkFlushMappedMemoryRanges_912839f9(VkDevice device, unsigned int memoryRangeCount, VkMappedMemoryRange* pMemoryRanges) {
	return pFNFlushMappedMemoryRanges912839F9(device, memoryRangeCount, pMemoryRanges);
}

VkResult PFN_vkInvalidateMappedMemoryRanges_583cf236(VkDevice device, unsigned int memoryRangeCount, VkMappedMemoryRange* pMemoryRanges) {
	return pFNInvalidateMappedMemoryRanges583CF236(device, memoryRangeCount, pMemoryRanges);
}

void PFN_vkGetDeviceMemoryCommitment_26e8ee13(VkDevice device, VkDeviceMemory memory, unsigned long long* pCommittedMemoryInBytes) {
	pFNGetDeviceMemoryCommitment26E8EE13(device, memory, pCommittedMemoryInBytes);
}

VkResult PFN_vkBindBufferMemory_f22e1edb(VkDevice device, VkBuffer buffer, VkDeviceMemory memory, unsigned long long memoryOffset) {
	return pFNBindBufferMemoryF22E1EDB(device, buffer, memory, memoryOffset);
}

VkResult PFN_vkBindImageMemory_56f456ab(VkDevice device, VkImage image, VkDeviceMemory memory, unsigned long long memoryOffset) {
	return pFNBindImageMemory56F456AB(device, image, memory, memoryOffset);
}

void PFN_vkGetBufferMemoryRequirements_4af23f40(VkDevice device, VkBuffer buffer, VkMemoryRequirements* pMemoryRequirements) {
	pFNGetBufferMemoryRequirements4AF23F40(device, buffer, pMemoryRequirements);
}

void PFN_vkGetImageMemoryRequirements_74385628(VkDevice device, VkImage image, VkMemoryRequirements* pMemoryRequirements) {
	pFNGetImageMemoryRequirements74385628(device, image, pMemoryRequirements);
}

void PFN_vkGetImageSparseMemoryRequirements_86dd1a84(VkDevice device, VkImage image, unsigned int* pSparseMemoryRequirementCount, VkSparseImageMemoryRequirements* pSparseMemoryRequirements) {
	pFNGetImageSparseMemoryRequirements86DD1A84(device, image, pSparseMemoryRequirementCount, pSparseMemoryRequirements);
}

void PFN_vkGetPhysicalDeviceSparseImageFormatProperties_b8d919e9(VkPhysicalDevice physicalDevice, VkFormat format, VkImageType _type, VkSampleCountFlagBits samples, unsigned int usage, VkImageTiling tiling, unsigned int* pPropertyCount, VkSparseImageFormatProperties* pProperties) {
	pFNGetPhysicalDeviceSparseImageFormatPropertiesB8D919E9(physicalDevice, format, _type, samples, usage, tiling, pPropertyCount, pProperties);
}

VkResult PFN_vkQueueBindSparse_cd067eaa(VkQueue queue, unsigned int bindInfoCount, VkBindSparseInfo* pBindInfo, VkFence fence) {
	return pFNQueueBindSparseCD067EAA(queue, bindInfoCount, pBindInfo, fence);
}

VkResult PFN_vkCreateFence_f6662003(VkDevice device, VkFenceCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkFence* pFence) {
	return pFNCreateFenceF6662003(device, pCreateInfo, pAllocator, pFence);
}

void PFN_vkDestroyFence_d1468627(VkDevice device, VkFence fence, VkAllocationCallbacks* pAllocator) {
	pFNDestroyFenceD1468627(device, fence, pAllocator);
}

VkResult PFN_vkResetFences_7df2b051(VkDevice device, unsigned int fenceCount, VkFence* pFences) {
	return pFNResetFences7DF2B051(device, fenceCount, pFences);
}

VkResult PFN_vkGetFenceStatus_f2c52e1a(VkDevice device, VkFence fence) {
	return pFNGetFenceStatusF2C52E1A(device, fence);
}

VkResult PFN_vkWaitForFences_899d94e6(VkDevice device, unsigned int fenceCount, VkFence* pFences, unsigned int waitAll, unsigned long long timeout) {
	return pFNWaitForFences899D94E6(device, fenceCount, pFences, waitAll, timeout);
}

VkResult PFN_vkCreateSemaphore_c37ad412(VkDevice device, VkSemaphoreCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkSemaphore* pSemaphore) {
	return pFNCreateSemaphoreC37AD412(device, pCreateInfo, pAllocator, pSemaphore);
}

void PFN_vkDestroySemaphore_1515c60(VkDevice device, VkSemaphore semaphore, VkAllocationCallbacks* pAllocator) {
	pFNDestroySemaphore1515C60(device, semaphore, pAllocator);
}

VkResult PFN_vkCreateEvent_202113fc(VkDevice device, VkEventCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkEvent* pEvent) {
	return pFNCreateEvent202113FC(device, pCreateInfo, pAllocator, pEvent);
}

void PFN_vkDestroyEvent_701b5d8(VkDevice device, VkEvent event, VkAllocationCallbacks* pAllocator) {
	pFNDestroyEvent701B5D8(device, event, pAllocator);
}

VkResult PFN_vkGetEventStatus_7f476e86(VkDevice device, VkEvent event) {
	return pFNGetEventStatus7F476E86(device, event);
}

VkResult PFN_vkSetEvent_52745188(VkDevice device, VkEvent event) {
	return pFNSetEvent52745188(device, event);
}

VkResult PFN_vkResetEvent_2c03a325(VkDevice device, VkEvent event) {
	return pFNResetEvent2C03A325(device, event);
}

VkResult PFN_vkCreateQueryPool_99a5956a(VkDevice device, VkQueryPoolCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkQueryPool* pQueryPool) {
	return pFNCreateQueryPool99A5956A(device, pCreateInfo, pAllocator, pQueryPool);
}

void PFN_vkDestroyQueryPool_5b8e1d18(VkDevice device, VkQueryPool queryPool, VkAllocationCallbacks* pAllocator) {
	pFNDestroyQueryPool5B8E1D18(device, queryPool, pAllocator);
}

VkResult PFN_vkGetQueryPoolResults_b2d2a5cb(VkDevice device, VkQueryPool queryPool, unsigned int firstQuery, unsigned int queryCount, unsigned long int dataSize, void* pData, unsigned long long stride, unsigned int flags) {
	return pFNGetQueryPoolResultsB2D2A5CB(device, queryPool, firstQuery, queryCount, dataSize, pData, stride, flags);
}

VkResult PFN_vkCreateBuffer_cdf8f797(VkDevice device, VkBufferCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkBuffer* pBuffer) {
	return pFNCreateBufferCDF8F797(device, pCreateInfo, pAllocator, pBuffer);
}

void PFN_vkDestroyBuffer_f1dc33e0(VkDevice device, VkBuffer buffer, VkAllocationCallbacks* pAllocator) {
	pFNDestroyBufferF1DC33E0(device, buffer, pAllocator);
}

VkResult PFN_vkCreateBufferView_f7636d40(VkDevice device, VkBufferViewCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkBufferView* pView) {
	return pFNCreateBufferViewF7636D40(device, pCreateInfo, pAllocator, pView);
}

void PFN_vkDestroyBufferView_49aa56d8(VkDevice device, VkBufferView bufferView, VkAllocationCallbacks* pAllocator) {
	pFNDestroyBufferView49AA56D8(device, bufferView, pAllocator);
}

VkResult PFN_vkCreateImage_deb21d04(VkDevice device, VkImageCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkImage* pImage) {
	return pFNCreateImageDEB21D04(device, pCreateInfo, pAllocator, pImage);
}

void PFN_vkDestroyImage_f992bb20(VkDevice device, VkImage image, VkAllocationCallbacks* pAllocator) {
	pFNDestroyImageF992BB20(device, image, pAllocator);
}

void PFN_vkGetImageSubresourceLayout_a0bcfd9d(VkDevice device, VkImage image, VkImageSubresource* pSubresource, VkSubresourceLayout* pLayout) {
	pFNGetImageSubresourceLayoutA0BCFD9D(device, image, pSubresource, pLayout);
}

VkResult PFN_vkCreateImageView_72cb902d(VkDevice device, VkImageViewCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkImageView* pView) {
	return pFNCreateImageView72CB902D(device, pCreateInfo, pAllocator, pView);
}

void PFN_vkDestroyImageView_b0e0185f(VkDevice device, VkImageView imageView, VkAllocationCallbacks* pAllocator) {
	pFNDestroyImageViewB0E0185F(device, imageView, pAllocator);
}

VkResult PFN_vkCreateShaderModule_15afa953(VkDevice device, VkShaderModuleCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkShaderModule* pShaderModule) {
	return pFNCreateShaderModule15AFA953(device, pCreateInfo, pAllocator, pShaderModule);
}

void PFN_vkDestroyShaderModule_1d3cfeac(VkDevice device, VkShaderModule shaderModule, VkAllocationCallbacks* pAllocator) {
	pFNDestroyShaderModule1D3CFEAC(device, shaderModule, pAllocator);
}

VkResult PFN_vkCreatePipelineCache_7bac14c4(VkDevice device, VkPipelineCacheCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkPipelineCache* pPipelineCache) {
	return pFNCreatePipelineCache7BAC14C4(device, pCreateInfo, pAllocator, pPipelineCache);
}

void PFN_vkDestroyPipelineCache_56a6681e(VkDevice device, VkPipelineCache pipelineCache, VkAllocationCallbacks* pAllocator) {
	pFNDestroyPipelineCache56A6681E(device, pipelineCache, pAllocator);
}

VkResult PFN_vkGetPipelineCacheData_ac8f8977(VkDevice device, VkPipelineCache pipelineCache, unsigned long int* pDataSize, void* pData) {
	return pFNGetPipelineCacheDataAC8F8977(device, pipelineCache, pDataSize, pData);
}

VkResult PFN_vkMergePipelineCaches_6b8cabfe(VkDevice device, VkPipelineCache dstCache, unsigned int srcCacheCount, VkPipelineCache* pSrcCaches) {
	return pFNMergePipelineCaches6B8CABFE(device, dstCache, srcCacheCount, pSrcCaches);
}

VkResult PFN_vkCreateGraphicsPipelines_c7fab507(VkDevice device, VkPipelineCache pipelineCache, unsigned int createInfoCount, VkGraphicsPipelineCreateInfo* pCreateInfos, VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines) {
	return pFNCreateGraphicsPipelinesC7FAB507(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
}

VkResult PFN_vkCreateComputePipelines_3616b207(VkDevice device, VkPipelineCache pipelineCache, unsigned int createInfoCount, VkComputePipelineCreateInfo* pCreateInfos, VkAllocationCallbacks* pAllocator, VkPipeline* pPipelines) {
	return pFNCreateComputePipelines3616B207(device, pipelineCache, createInfoCount, pCreateInfos, pAllocator, pPipelines);
}

void PFN_vkDestroyPipeline_765fa86(VkDevice device, VkPipeline pipeline, VkAllocationCallbacks* pAllocator) {
	pFNDestroyPipeline765FA86(device, pipeline, pAllocator);
}

VkResult PFN_vkCreatePipelineLayout_9867f1ef(VkDevice device, VkPipelineLayoutCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkPipelineLayout* pPipelineLayout) {
	return pFNCreatePipelineLayout9867F1EF(device, pCreateInfo, pAllocator, pPipelineLayout);
}

void PFN_vkDestroyPipelineLayout_fe4cc059(VkDevice device, VkPipelineLayout pipelineLayout, VkAllocationCallbacks* pAllocator) {
	pFNDestroyPipelineLayoutFE4CC059(device, pipelineLayout, pAllocator);
}

VkResult PFN_vkCreateSampler_53b15031(VkDevice device, VkSamplerCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkSampler* pSampler) {
	return pFNCreateSampler53B15031(device, pCreateInfo, pAllocator, pSampler);
}

void PFN_vkDestroySampler_9dec906a(VkDevice device, VkSampler sampler, VkAllocationCallbacks* pAllocator) {
	pFNDestroySampler9DEC906A(device, sampler, pAllocator);
}

VkResult PFN_vkCreateDescriptorSetLayout_df81b6fb(VkDevice device, VkDescriptorSetLayoutCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkDescriptorSetLayout* pSetLayout) {
	return pFNCreateDescriptorSetLayoutDF81B6FB(device, pCreateInfo, pAllocator, pSetLayout);
}

void PFN_vkDestroyDescriptorSetLayout_f2eb1ab(VkDevice device, VkDescriptorSetLayout descriptorSetLayout, VkAllocationCallbacks* pAllocator) {
	pFNDestroyDescriptorSetLayoutF2EB1AB(device, descriptorSetLayout, pAllocator);
}

VkResult PFN_vkCreateDescriptorPool_ab14fe1b(VkDevice device, VkDescriptorPoolCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkDescriptorPool* pDescriptorPool) {
	return pFNCreateDescriptorPoolAB14FE1B(device, pCreateInfo, pAllocator, pDescriptorPool);
}

void PFN_vkDestroyDescriptorPool_cd3fcfad(VkDevice device, VkDescriptorPool descriptorPool, VkAllocationCallbacks* pAllocator) {
	pFNDestroyDescriptorPoolCD3FCFAD(device, descriptorPool, pAllocator);
}

VkResult PFN_vkResetDescriptorPool_eaa63710(VkDevice device, VkDescriptorPool descriptorPool, unsigned int flags) {
	return pFNResetDescriptorPoolEAA63710(device, descriptorPool, flags);
}

VkResult PFN_vkAllocateDescriptorSets_f727f5c9(VkDevice device, VkDescriptorSetAllocateInfo* pAllocateInfo, VkDescriptorSet* pDescriptorSets) {
	return pFNAllocateDescriptorSetsF727F5C9(device, pAllocateInfo, pDescriptorSets);
}

VkResult PFN_vkFreeDescriptorSets_54b3db78(VkDevice device, VkDescriptorPool descriptorPool, unsigned int descriptorSetCount, VkDescriptorSet* pDescriptorSets) {
	return pFNFreeDescriptorSets54B3DB78(device, descriptorPool, descriptorSetCount, pDescriptorSets);
}

void PFN_vkUpdateDescriptorSets_6f0b94ac(VkDevice device, unsigned int descriptorWriteCount, VkWriteDescriptorSet* pDescriptorWrites, unsigned int descriptorCopyCount, VkCopyDescriptorSet* pDescriptorCopies) {
	pFNUpdateDescriptorSets6F0B94AC(device, descriptorWriteCount, pDescriptorWrites, descriptorCopyCount, pDescriptorCopies);
}

VkResult PFN_vkCreateFramebuffer_d64a4d97(VkDevice device, VkFramebufferCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkFramebuffer* pFramebuffer) {
	return pFNCreateFramebufferD64A4D97(device, pCreateInfo, pAllocator, pFramebuffer);
}

void PFN_vkDestroyFramebuffer_28209fda(VkDevice device, VkFramebuffer framebuffer, VkAllocationCallbacks* pAllocator) {
	pFNDestroyFramebuffer28209FDA(device, framebuffer, pAllocator);
}

VkResult PFN_vkCreateRenderPass_8fadbef(VkDevice device, VkRenderPassCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkRenderPass* pRenderPass) {
	return pFNCreateRenderPass8FADBEF(device, pCreateInfo, pAllocator, pRenderPass);
}

void PFN_vkDestroyRenderPass_b633e077(VkDevice device, VkRenderPass renderPass, VkAllocationCallbacks* pAllocator) {
	pFNDestroyRenderPassB633E077(device, renderPass, pAllocator);
}

void PFN_vkGetRenderAreaGranularity_bf72d2fc(VkDevice device, VkRenderPass renderPass, VkExtent2D* pGranularity) {
	pFNGetRenderAreaGranularityBF72D2FC(device, renderPass, pGranularity);
}

VkResult PFN_vkCreateCommandPool_97050bd8(VkDevice device, VkCommandPoolCreateInfo* pCreateInfo, VkAllocationCallbacks* pAllocator, VkCommandPool* pCommandPool) {
	return pFNCreateCommandPool97050BD8(device, pCreateInfo, pAllocator, pCommandPool);
}

void PFN_vkDestroyCommandPool_696fd995(VkDevice device, VkCommandPool commandPool, VkAllocationCallbacks* pAllocator) {
	pFNDestroyCommandPool696FD995(device, commandPool, pAllocator);
}

VkResult PFN_vkResetCommandPool_b1d2d0fa(VkDevice device, VkCommandPool commandPool, unsigned int flags) {
	return pFNResetCommandPoolB1D2D0FA(device, commandPool, flags);
}

VkResult PFN_vkAllocateCommandBuffers_22d26bfa(VkDevice device, VkCommandBufferAllocateInfo* pAllocateInfo, VkCommandBuffer* pCommandBuffers) {
	return pFNAllocateCommandBuffers22D26BFA(device, pAllocateInfo, pCommandBuffers);
}

void PFN_vkFreeCommandBuffers_8146454b(VkDevice device, VkCommandPool commandPool, unsigned int commandBufferCount, VkCommandBuffer* pCommandBuffers) {
	pFNFreeCommandBuffers8146454B(device, commandPool, commandBufferCount, pCommandBuffers);
}

VkResult PFN_vkBeginCommandBuffer_76cc70c1(VkCommandBuffer commandBuffer, VkCommandBufferBeginInfo* pBeginInfo) {
	return pFNBeginCommandBuffer76CC70C1(commandBuffer, pBeginInfo);
}

VkResult PFN_vkEndCommandBuffer_4956641(VkCommandBuffer commandBuffer) {
	return pFNEndCommandBuffer4956641(commandBuffer);
}

VkResult PFN_vkResetCommandBuffer_9b0911d3(VkCommandBuffer commandBuffer, unsigned int flags) {
	return pFNResetCommandBuffer9B0911D3(commandBuffer, flags);
}

void PFN_vkCmdBindPipeline_a2c7555b(VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipeline pipeline) {
	pFNCmdBindPipelineA2C7555B(commandBuffer, pipelineBindPoint, pipeline);
}

void PFN_vkCmdSetViewport_edc0e9f4(VkCommandBuffer commandBuffer, unsigned int firstViewport, unsigned int viewportCount, VkViewport* pViewports) {
	pFNCmdSetViewportEDC0E9F4(commandBuffer, firstViewport, viewportCount, pViewports);
}

void PFN_vkCmdSetScissor_cc776c1c(VkCommandBuffer commandBuffer, unsigned int firstScissor, unsigned int scissorCount, VkRect2D* pScissors) {
	pFNCmdSetScissorCC776C1C(commandBuffer, firstScissor, scissorCount, pScissors);
}

void PFN_vkCmdSetLineWidth_1080bc84(VkCommandBuffer commandBuffer, float lineWidth) {
	pFNCmdSetLineWidth1080BC84(commandBuffer, lineWidth);
}

void PFN_vkCmdSetDepthBias_e2d686bd(VkCommandBuffer commandBuffer, float depthBiasConstantFactor, float depthBiasClamp, float depthBiasSlopeFactor) {
	pFNCmdSetDepthBiasE2D686BD(commandBuffer, depthBiasConstantFactor, depthBiasClamp, depthBiasSlopeFactor);
}

void PFN_vkCmdSetDepthBounds_98318da7(VkCommandBuffer commandBuffer, float minDepthBounds, float maxDepthBounds) {
	pFNCmdSetDepthBounds98318DA7(commandBuffer, minDepthBounds, maxDepthBounds);
}

void PFN_vkCmdSetStencilCompareMask_1c528e50(VkCommandBuffer commandBuffer, unsigned int faceMask, unsigned int compareMask) {
	pFNCmdSetStencilCompareMask1C528E50(commandBuffer, faceMask, compareMask);
}

void PFN_vkCmdSetStencilWriteMask_663bc6f1(VkCommandBuffer commandBuffer, unsigned int faceMask, unsigned int writeMask) {
	pFNCmdSetStencilWriteMask663BC6F1(commandBuffer, faceMask, writeMask);
}

void PFN_vkCmdSetStencilReference_7570ae73(VkCommandBuffer commandBuffer, unsigned int faceMask, unsigned int reference) {
	pFNCmdSetStencilReference7570AE73(commandBuffer, faceMask, reference);
}

void PFN_vkCmdBindDescriptorSets_92256a49(VkCommandBuffer commandBuffer, VkPipelineBindPoint pipelineBindPoint, VkPipelineLayout layout, unsigned int firstSet, unsigned int descriptorSetCount, VkDescriptorSet* pDescriptorSets, unsigned int dynamicOffsetCount, unsigned int* pDynamicOffsets) {
	pFNCmdBindDescriptorSets92256A49(commandBuffer, pipelineBindPoint, layout, firstSet, descriptorSetCount, pDescriptorSets, dynamicOffsetCount, pDynamicOffsets);
}

void PFN_vkCmdBindIndexBuffer_8a8b689c(VkCommandBuffer commandBuffer, VkBuffer buffer, unsigned long long offset, VkIndexType indexType) {
	pFNCmdBindIndexBuffer8A8B689C(commandBuffer, buffer, offset, indexType);
}

void PFN_vkCmdBindVertexBuffers_cd53a724(VkCommandBuffer commandBuffer, unsigned int firstBinding, unsigned int bindingCount, VkBuffer* pBuffers, unsigned long long* pOffsets) {
	pFNCmdBindVertexBuffersCD53A724(commandBuffer, firstBinding, bindingCount, pBuffers, pOffsets);
}

void PFN_vkCmdDraw_4706e5bd(VkCommandBuffer commandBuffer, unsigned int vertexCount, unsigned int instanceCount, unsigned int firstVertex, unsigned int firstInstance) {
	pFNCmdDraw4706E5BD(commandBuffer, vertexCount, instanceCount, firstVertex, firstInstance);
}

void PFN_vkCmdDrawIndexed_9854657c(VkCommandBuffer commandBuffer, unsigned int indexCount, unsigned int instanceCount, unsigned int firstIndex, int vertexOffset, unsigned int firstInstance) {
	pFNCmdDrawIndexed9854657C(commandBuffer, indexCount, instanceCount, firstIndex, vertexOffset, firstInstance);
}

void PFN_vkCmdDrawIndirect_394da878(VkCommandBuffer commandBuffer, VkBuffer buffer, unsigned long long offset, unsigned int drawCount, unsigned int stride) {
	pFNCmdDrawIndirect394DA878(commandBuffer, buffer, offset, drawCount, stride);
}

void PFN_vkCmdDrawIndexedIndirect_4db44457(VkCommandBuffer commandBuffer, VkBuffer buffer, unsigned long long offset, unsigned int drawCount, unsigned int stride) {
	pFNCmdDrawIndexedIndirect4DB44457(commandBuffer, buffer, offset, drawCount, stride);
}

void PFN_vkCmdDispatch_9bab1ef5(VkCommandBuffer commandBuffer, unsigned int x, unsigned int y, unsigned int z) {
	pFNCmdDispatch9BAB1EF5(commandBuffer, x, y, z);
}

void PFN_vkCmdDispatchIndirect_4ccb8f6b(VkCommandBuffer commandBuffer, VkBuffer buffer, unsigned long long offset) {
	pFNCmdDispatchIndirect4CCB8F6B(commandBuffer, buffer, offset);
}

void PFN_vkCmdCopyBuffer_7f558dee(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkBuffer dstBuffer, unsigned int regionCount, VkBufferCopy* pRegions) {
	pFNCmdCopyBuffer7F558DEE(commandBuffer, srcBuffer, dstBuffer, regionCount, pRegions);
}

void PFN_vkCmdCopyImage_cec34cbd(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, unsigned int regionCount, VkImageCopy* pRegions) {
	pFNCmdCopyImageCEC34CBD(commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions);
}

void PFN_vkCmdBlitImage_19ef95de(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, unsigned int regionCount, VkImageBlit* pRegions, VkFilter filter) {
	pFNCmdBlitImage19EF95DE(commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions, filter);
}

void PFN_vkCmdCopyBufferToImage_4394592e(VkCommandBuffer commandBuffer, VkBuffer srcBuffer, VkImage dstImage, VkImageLayout dstImageLayout, unsigned int regionCount, VkBufferImageCopy* pRegions) {
	pFNCmdCopyBufferToImage4394592E(commandBuffer, srcBuffer, dstImage, dstImageLayout, regionCount, pRegions);
}

void PFN_vkCmdCopyImageToBuffer_4185ace5(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkBuffer dstBuffer, unsigned int regionCount, VkBufferImageCopy* pRegions) {
	pFNCmdCopyImageToBuffer4185ACE5(commandBuffer, srcImage, srcImageLayout, dstBuffer, regionCount, pRegions);
}

void PFN_vkCmdUpdateBuffer_c541b249(VkCommandBuffer commandBuffer, VkBuffer dstBuffer, unsigned long long dstOffset, unsigned long long dataSize, unsigned int* pData) {
	pFNCmdUpdateBufferC541B249(commandBuffer, dstBuffer, dstOffset, dataSize, pData);
}

void PFN_vkCmdFillBuffer_f494a82d(VkCommandBuffer commandBuffer, VkBuffer dstBuffer, unsigned long long dstOffset, unsigned long long size, unsigned int data) {
	pFNCmdFillBufferF494A82D(commandBuffer, dstBuffer, dstOffset, size, data);
}

void PFN_vkCmdClearColorImage_453252cf(VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout, VkClearColorValue* pColor, unsigned int rangeCount, VkImageSubresourceRange* pRanges) {
	pFNCmdClearColorImage453252CF(commandBuffer, image, imageLayout, pColor, rangeCount, pRanges);
}

void PFN_vkCmdClearDepthStencilImage_1045179c(VkCommandBuffer commandBuffer, VkImage image, VkImageLayout imageLayout, VkClearDepthStencilValue* pDepthStencil, unsigned int rangeCount, VkImageSubresourceRange* pRanges) {
	pFNCmdClearDepthStencilImage1045179C(commandBuffer, image, imageLayout, pDepthStencil, rangeCount, pRanges);
}

void PFN_vkCmdClearAttachments_4b13dddc(VkCommandBuffer commandBuffer, unsigned int attachmentCount, VkClearAttachment* pAttachments, unsigned int rectCount, VkClearRect* pRects) {
	pFNCmdClearAttachments4B13DDDC(commandBuffer, attachmentCount, pAttachments, rectCount, pRects);
}

void PFN_vkCmdResolveImage_8773c849(VkCommandBuffer commandBuffer, VkImage srcImage, VkImageLayout srcImageLayout, VkImage dstImage, VkImageLayout dstImageLayout, unsigned int regionCount, VkImageResolve* pRegions) {
	pFNCmdResolveImage8773C849(commandBuffer, srcImage, srcImageLayout, dstImage, dstImageLayout, regionCount, pRegions);
}

void PFN_vkCmdSetEvent_2f34cf9e(VkCommandBuffer commandBuffer, VkEvent event, unsigned int stageMask) {
	pFNCmdSetEvent2F34CF9E(commandBuffer, event, stageMask);
}

void PFN_vkCmdResetEvent_272cd5f1(VkCommandBuffer commandBuffer, VkEvent event, unsigned int stageMask) {
	pFNCmdResetEvent272CD5F1(commandBuffer, event, stageMask);
}

void PFN_vkCmdWaitEvents_f92c9b96(VkCommandBuffer commandBuffer, unsigned int eventCount, VkEvent* pEvents, unsigned int srcStageMask, unsigned int dstStageMask, unsigned int memoryBarrierCount, VkMemoryBarrier* pMemoryBarriers, unsigned int bufferMemoryBarrierCount, VkBufferMemoryBarrier* pBufferMemoryBarriers, unsigned int imageMemoryBarrierCount, VkImageMemoryBarrier* pImageMemoryBarriers) {
	pFNCmdWaitEventsF92C9B96(commandBuffer, eventCount, pEvents, srcStageMask, dstStageMask, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers);
}

void PFN_vkCmdPipelineBarrier_d83ec454(VkCommandBuffer commandBuffer, unsigned int srcStageMask, unsigned int dstStageMask, unsigned int dependencyFlags, unsigned int memoryBarrierCount, VkMemoryBarrier* pMemoryBarriers, unsigned int bufferMemoryBarrierCount, VkBufferMemoryBarrier* pBufferMemoryBarriers, unsigned int imageMemoryBarrierCount, VkImageMemoryBarrier* pImageMemoryBarriers) {
	pFNCmdPipelineBarrierD83EC454(commandBuffer, srcStageMask, dstStageMask, dependencyFlags, memoryBarrierCount, pMemoryBarriers, bufferMemoryBarrierCount, pBufferMemoryBarriers, imageMemoryBarrierCount, pImageMemoryBarriers);
}

void PFN_vkCmdBeginQuery_828d9f0d(VkCommandBuffer commandBuffer, VkQueryPool queryPool, unsigned int query, unsigned int flags) {
	pFNCmdBeginQuery828D9F0D(commandBuffer, queryPool, query, flags);
}

void PFN_vkCmdEndQuery_8b221e1f(VkCommandBuffer commandBuffer, VkQueryPool queryPool, unsigned int query) {
	pFNCmdEndQuery8B221E1F(commandBuffer, queryPool, query);
}

void PFN_vkCmdResetQueryPool_d5274cab(VkCommandBuffer commandBuffer, VkQueryPool queryPool, unsigned int firstQuery, unsigned int queryCount) {
	pFNCmdResetQueryPoolD5274CAB(commandBuffer, queryPool, firstQuery, queryCount);
}

void PFN_vkCmdWriteTimestamp_dc3d5864(VkCommandBuffer commandBuffer, VkPipelineStageFlagBits pipelineStage, VkQueryPool queryPool, unsigned int query) {
	pFNCmdWriteTimestampDC3D5864(commandBuffer, pipelineStage, queryPool, query);
}

void PFN_vkCmdCopyQueryPoolResults_a38fbcd6(VkCommandBuffer commandBuffer, VkQueryPool queryPool, unsigned int firstQuery, unsigned int queryCount, VkBuffer dstBuffer, unsigned long long dstOffset, unsigned long long stride, unsigned int flags) {
	pFNCmdCopyQueryPoolResultsA38FBCD6(commandBuffer, queryPool, firstQuery, queryCount, dstBuffer, dstOffset, stride, flags);
}

void PFN_vkCmdPushConstants_32b3fc16(VkCommandBuffer commandBuffer, VkPipelineLayout layout, unsigned int stageFlags, unsigned int offset, unsigned int size, void* pValues) {
	pFNCmdPushConstants32B3FC16(commandBuffer, layout, stageFlags, offset, size, pValues);
}

void PFN_vkCmdBeginRenderPass_9d5a29dd(VkCommandBuffer commandBuffer, VkRenderPassBeginInfo* pRenderPassBegin, VkSubpassContents contents) {
	pFNCmdBeginRenderPass9D5A29DD(commandBuffer, pRenderPassBegin, contents);
}

void PFN_vkCmdNextSubpass_ffe19f9a(VkCommandBuffer commandBuffer, VkSubpassContents contents) {
	pFNCmdNextSubpassFFE19F9A(commandBuffer, contents);
}

void PFN_vkCmdEndRenderPass_d1799d75(VkCommandBuffer commandBuffer) {
	pFNCmdEndRenderPassD1799D75(commandBuffer);
}

void PFN_vkCmdExecuteCommands_ba33faee(VkCommandBuffer commandBuffer, unsigned int commandBufferCount, VkCommandBuffer* pCommandBuffers) {
	pFNCmdExecuteCommandsBA33FAEE(commandBuffer, commandBufferCount, pCommandBuffers);
}

void PFN_vkDestroySurfaceKHR_d5f3492(VkInstance instance, VkSurfaceKHR surface, VkAllocationCallbacks* pAllocator) {
	pFNDestroySurfaceKHRD5F3492(instance, surface, pAllocator);
}

VkResult PFN_vkGetPhysicalDeviceSurfaceSupportKHR_1f637f55(VkPhysicalDevice physicalDevice, unsigned int queueFamilyIndex, VkSurfaceKHR surface, unsigned int* pSupported) {
	return pFNGetPhysicalDeviceSurfaceSupportKHR1F637F55(physicalDevice, queueFamilyIndex, surface, pSupported);
}

VkResult PFN_vkGetPhysicalDeviceSurfaceCapabilitiesKHR_7e3a1b89(VkPhysicalDevice physicalDevice, VkSurfaceKHR surface, VkSurfaceCapabilitiesKHR* pSurfaceCapabilities) {
	return pFNGetPhysicalDeviceSurfaceCapabilitiesKHR7E3A1B89(physicalDevice, surface, pSurfaceCapabilities);
}

VkResult PFN_vkGetPhysicalDeviceSurfaceFormatsKHR_8bbbab0c(VkPhysicalDevice physicalDevice, VkSurfaceKHR surface, unsigned int* pSurfaceFormatCount, VkSurfaceFormatKHR* pSurfaceFormats) {
	return pFNGetPhysicalDeviceSurfaceFormatsKHR8BBBAB0C(physicalDevice, surface, pSurfaceFormatCount, pSurfaceFormats);
}

VkResult PFN_vkGetPhysicalDeviceSurfacePresentModesKHR_79c877(VkPhysicalDevice physicalDevice, VkSurfaceKHR surface, unsigned int* pPresentModeCount, VkPresentModeKHR* pPresentModes) {
	return pFNGetPhysicalDeviceSurfacePresentModesKHR79C877(physicalDevice, surface, pPresentModeCount, pPresentModes);
}

VkResult PFN_vkCreateSwapchainKHR_2b7f1c9e(VkDevice device, VkSwapchainCreateInfoKHR* pCreateInfo, VkAllocationCallbacks* pAllocator, VkSwapchainKHR* pSwapchain) {
	return pFNCreateSwapchainKHR2B7F1C9E(device, pCreateInfo, pAllocator, pSwapchain);
}

void PFN_vkDestroySwapchainKHR_23ec4b61(VkDevice device, VkSwapchainKHR swapchain, VkAllocationCallbacks* pAllocator) {
	pFNDestroySwapchainKHR23EC4B61(device, swapchain, pAllocator);
}

VkResult PFN_vkGetSwapchainImagesKHR_caef1c13(VkDevice device, VkSwapchainKHR swapchain, unsigned int* pSwapchainImageCount, VkImage* pSwapchainImages) {
	return pFNGetSwapchainImagesKHRCAEF1C13(device, swapchain, pSwapchainImageCount, pSwapchainImages);
}

VkResult PFN_vkAcquireNextImageKHR_bce813c0(VkDevice device, VkSwapchainKHR swapchain, unsigned long long timeout, VkSemaphore semaphore, VkFence fence, unsigned int* pImageIndex) {
	return pFNAcquireNextImageKHRBCE813C0(device, swapchain, timeout, semaphore, fence, pImageIndex);
}

VkResult PFN_vkQueuePresentKHR_fa5ab313(VkQueue queue, VkPresentInfoKHR* pPresentInfo) {
	return pFNQueuePresentKHRFA5AB313(queue, pPresentInfo);
}

VkResult PFN_vkGetPhysicalDeviceDisplayPropertiesKHR_625cafbe(VkPhysicalDevice physicalDevice, unsigned int* pPropertyCount, VkDisplayPropertiesKHR* pProperties) {
	return pFNGetPhysicalDeviceDisplayPropertiesKHR625CAFBE(physicalDevice, pPropertyCount, pProperties);
}

VkResult PFN_vkGetPhysicalDeviceDisplayPlanePropertiesKHR_290f765f(VkPhysicalDevice physicalDevice, unsigned int* pPropertyCount, VkDisplayPlanePropertiesKHR* pProperties) {
	return pFNGetPhysicalDeviceDisplayPlanePropertiesKHR290F765F(physicalDevice, pPropertyCount, pProperties);
}

VkResult PFN_vkGetDisplayPlaneSupportedDisplaysKHR_c06c75a8(VkPhysicalDevice physicalDevice, unsigned int planeIndex, unsigned int* pDisplayCount, VkDisplayKHR* pDisplays) {
	return pFNGetDisplayPlaneSupportedDisplaysKHRC06C75A8(physicalDevice, planeIndex, pDisplayCount, pDisplays);
}

VkResult PFN_vkGetDisplayModePropertiesKHR_fa283554(VkPhysicalDevice physicalDevice, VkDisplayKHR display, unsigned int* pPropertyCount, VkDisplayModePropertiesKHR* pProperties) {
	return pFNGetDisplayModePropertiesKHRFA283554(physicalDevice, display, pPropertyCount, pProperties);
}

VkResult PFN_vkCreateDisplayModeKHR_aa042680(VkPhysicalDevice physicalDevice, VkDisplayKHR display, VkDisplayModeCreateInfoKHR* pCreateInfo, VkAllocationCallbacks* pAllocator, VkDisplayModeKHR* pMode) {
	return pFNCreateDisplayModeKHRAA042680(physicalDevice, display, pCreateInfo, pAllocator, pMode);
}

VkResult PFN_vkGetDisplayPlaneCapabilitiesKHR_9fc9571d(VkPhysicalDevice physicalDevice, VkDisplayModeKHR mode, unsigned int planeIndex, VkDisplayPlaneCapabilitiesKHR* pCapabilities) {
	return pFNGetDisplayPlaneCapabilitiesKHR9FC9571D(physicalDevice, mode, planeIndex, pCapabilities);
}

VkResult PFN_vkCreateDisplayPlaneSurfaceKHR_a82dd380(VkInstance instance, VkDisplaySurfaceCreateInfoKHR* pCreateInfo, VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface) {
	return pFNCreateDisplayPlaneSurfaceKHRA82DD380(instance, pCreateInfo, pAllocator, pSurface);
}

VkResult PFN_vkCreateSharedSwapchainsKHR_4bb273f(VkDevice device, unsigned int swapchainCount, VkSwapchainCreateInfoKHR* pCreateInfos, VkAllocationCallbacks* pAllocator, VkSwapchainKHR* pSwapchains) {
	return pFNCreateSharedSwapchainsKHR4BB273F(device, swapchainCount, pCreateInfos, pAllocator, pSwapchains);
}

VkResult PFN_vkCreateAndroidSurfaceKHR_45c62d4(VkInstance instance, VkAndroidSurfaceCreateInfoKHR* pCreateInfo, VkAllocationCallbacks* pAllocator, VkSurfaceKHR* pSurface) {
	return pFNCreateAndroidSurfaceKHR45C62D4(instance, pCreateInfo, pAllocator, pSurface);
}

unsigned int PFN_vkDebugReportCallbackEXT_c918aac4(unsigned int flags, VkDebugReportObjectTypeEXT objectType, unsigned long long object, unsigned long int location, int messageCode, char* pLayerPrefix, char* pMessage, void* pUserData) {
	return pFNDebugReportCallbackEXTC918AAC4(flags, objectType, object, location, messageCode, pLayerPrefix, pMessage, pUserData);
}

VkResult PFN_vkCreateDebugReportCallbackEXT_3f23708f(VkInstance instance, VkDebugReportCallbackCreateInfoEXT* pCreateInfo, VkAllocationCallbacks* pAllocator, VkDebugReportCallbackEXT* pCallback) {
	return pFNCreateDebugReportCallbackEXT3F23708F(instance, pCreateInfo, pAllocator, pCallback);
}

void PFN_vkDestroyDebugReportCallbackEXT_5ab77651(VkInstance instance, VkDebugReportCallbackEXT callback, VkAllocationCallbacks* pAllocator) {
	pFNDestroyDebugReportCallbackEXT5AB77651(instance, callback, pAllocator);
}

void PFN_vkDebugReportMessageEXT_847e0f11(VkInstance instance, unsigned int flags, VkDebugReportObjectTypeEXT objectType, unsigned long long object, unsigned long int location, int messageCode, char* pLayerPrefix, char* pMessage) {
	pFNDebugReportMessageEXT847E0F11(instance, flags, objectType, object, location, messageCode, pLayerPrefix, pMessage);
}

VkResult PFN_vkDebugMarkerSetObjectTagEXT_64dcd960(VkDevice device, VkDebugMarkerObjectTagInfoEXT* pTagInfo) {
	return pFNDebugMarkerSetObjectTagEXT64DCD960(device, pTagInfo);
}

VkResult PFN_vkDebugMarkerSetObjectNameEXT_62b5ccd1(VkDevice device, VkDebugMarkerObjectNameInfoEXT* pNameInfo) {
	return pFNDebugMarkerSetObjectNameEXT62B5CCD1(device, pNameInfo);
}

void PFN_vkCmdDebugMarkerBeginEXT_f3766240(VkCommandBuffer commandBuffer, VkDebugMarkerMarkerInfoEXT* pMarkerInfo) {
	pFNCmdDebugMarkerBeginEXTF3766240(commandBuffer, pMarkerInfo);
}

void PFN_vkCmdDebugMarkerEndEXT_66e51d45(VkCommandBuffer commandBuffer) {
	pFNCmdDebugMarkerEndEXT66E51D45(commandBuffer);
}

void PFN_vkCmdDebugMarkerInsertEXT_a68b2dd7(VkCommandBuffer commandBuffer, VkDebugMarkerMarkerInfoEXT* pMarkerInfo) {
	pFNCmdDebugMarkerInsertEXTA68B2DD7(commandBuffer, pMarkerInfo);
}

