// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 03 Mar 2016 02:03:17 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package vulkan

/*
#include "vulkan.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// Version10 as defined in vulkan/vulkan.h:37
	Version10 = 1
	// ApiVersion as defined in vulkan/vulkan.h:44
	ApiVersion = 4194308
	// NullHandle as defined in vulkan/vulkan.h:50
	NullHandle = 0
	// LodClampNone as defined in vulkan/vulkan.h:96
	LodClampNone = 1000
	// RemainingMipLevels as defined in vulkan/vulkan.h:97
	RemainingMipLevels = 4294967295
	// RemainingArrayLayers as defined in vulkan/vulkan.h:98
	RemainingArrayLayers = 4294967295
	// WholeSize as defined in vulkan/vulkan.h:99
	WholeSize = 18446744073709551615
	// AttachmentUnused as defined in vulkan/vulkan.h:100
	AttachmentUnused = 4294967295
	// True as defined in vulkan/vulkan.h:101
	True = 1
	// False as defined in vulkan/vulkan.h:102
	False = 0
	// QueueFamilyIgnored as defined in vulkan/vulkan.h:103
	QueueFamilyIgnored = 4294967295
	// SubpassExternal as defined in vulkan/vulkan.h:104
	SubpassExternal = 4294967295
	// MaxPhysicalDeviceNameSize as defined in vulkan/vulkan.h:105
	MaxPhysicalDeviceNameSize = 256
	// UuidSize as defined in vulkan/vulkan.h:106
	UuidSize = 16
	// MaxMemoryTypes as defined in vulkan/vulkan.h:107
	MaxMemoryTypes = 32
	// MaxMemoryHeaps as defined in vulkan/vulkan.h:108
	MaxMemoryHeaps = 16
	// MaxExtensionNameSize as defined in vulkan/vulkan.h:109
	MaxExtensionNameSize = 256
	// MaxDescriptionSize as defined in vulkan/vulkan.h:110
	MaxDescriptionSize = 256
	// KhrSurface as defined in vulkan/vulkan.h:3134
	KhrSurface = 1
	// KhrSurfaceSpecVersion as defined in vulkan/vulkan.h:3137
	KhrSurfaceSpecVersion = 25
	// KhrSurfaceExtensionName as defined in vulkan/vulkan.h:3138
	KhrSurfaceExtensionName = VK_KHR_surface
	// KhrSwapchain as defined in vulkan/vulkan.h:3237
	KhrSwapchain = 1
	// KhrSwapchainSpecVersion as defined in vulkan/vulkan.h:3240
	KhrSwapchainSpecVersion = 67
	// KhrSwapchainExtensionName as defined in vulkan/vulkan.h:3241
	KhrSwapchainExtensionName = VK_KHR_swapchain
	// KhrDisplay as defined in vulkan/vulkan.h:3315
	KhrDisplay = 1
	// KhrDisplaySpecVersion as defined in vulkan/vulkan.h:3319
	KhrDisplaySpecVersion = 21
	// KhrDisplayExtensionName as defined in vulkan/vulkan.h:3320
	KhrDisplayExtensionName = VK_KHR_display
	// KhrDisplaySwapchain as defined in vulkan/vulkan.h:3442
	KhrDisplaySwapchain = 1
	// KhrDisplaySwapchainSpecVersion as defined in vulkan/vulkan.h:3443
	KhrDisplaySwapchainSpecVersion = 9
	// KhrDisplaySwapchainExtensionName as defined in vulkan/vulkan.h:3444
	KhrDisplaySwapchainExtensionName = VK_KHR_display_swapchain
	// KhrSamplerMirrorClampToEdge as defined in vulkan/vulkan.h:3670
	KhrSamplerMirrorClampToEdge = 1
	// KhrSamplerMirrorClampToEdgeSpecVersion as defined in vulkan/vulkan.h:3671
	KhrSamplerMirrorClampToEdgeSpecVersion = 1
	// KhrSamplerMirrorClampToEdgeExtensionName as defined in vulkan/vulkan.h:3672
	KhrSamplerMirrorClampToEdgeExtensionName = VK_KHR_sampler_mirror_clamp_to_edge
	// ExtDebugReport as defined in vulkan/vulkan.h:3675
	ExtDebugReport = 1
	// ExtDebugReportSpecVersion as defined in vulkan/vulkan.h:3678
	ExtDebugReportSpecVersion = 2
	// ExtDebugReportExtensionName as defined in vulkan/vulkan.h:3679
	ExtDebugReportExtensionName = VK_EXT_debug_report
	// StructureTypeDebugReportCreateInfoExt as defined in vulkan/vulkan.h:3680
	StructureTypeDebugReportCreateInfoExt = 0
)

// VertexInputRate as declared in vulkan/vulkan.h:533
type VertexInputRate uint32

// VertexInputRate enumeration from vulkan/vulkan.h:533
const (
	VertexInputRateVertex     VertexInputRate = 0
	VertexInputRateInstance   VertexInputRate = 1
	VertexInputRateBeginRange VertexInputRate = 0
	VertexInputRateEndRange   VertexInputRate = 1
	VertexInputRateRangeSize  VertexInputRate = 2
	VertexInputRateMaxEnum    VertexInputRate = 2147483647
)

// BorderColor as declared in vulkan/vulkan.h:720
type BorderColor uint32

// BorderColor enumeration from vulkan/vulkan.h:720
const (
	BorderColorFloatTransparentBlack BorderColor = 0
	BorderColorIntTransparentBlack   BorderColor = 1
	BorderColorFloatOpaqueBlack      BorderColor = 2
	BorderColorIntOpaqueBlack        BorderColor = 3
	BorderColorFloatOpaqueWhite      BorderColor = 4
	BorderColorIntOpaqueWhite        BorderColor = 5
	BorderColorBeginRange            BorderColor = 0
	BorderColorEndRange              BorderColor = 5
	BorderColorRangeSize             BorderColor = 6
	BorderColorMaxEnum               BorderColor = 2147483647
)

// ImageUsageFlagBits as declared in vulkan/vulkan.h:823
type ImageUsageFlagBits uint32

// ImageUsageFlagBits enumeration from vulkan/vulkan.h:823
const (
	ImageUsageTransferSrcBit            ImageUsageFlagBits = 1
	ImageUsageTransferDstBit            ImageUsageFlagBits = 2
	ImageUsageSampledBit                ImageUsageFlagBits = 4
	ImageUsageStorageBit                ImageUsageFlagBits = 8
	ImageUsageColorAttachmentBit        ImageUsageFlagBits = 16
	ImageUsageDepthStencilAttachmentBit ImageUsageFlagBits = 32
	ImageUsageTransientAttachmentBit    ImageUsageFlagBits = 64
	ImageUsageInputAttachmentBit        ImageUsageFlagBits = 128
)

// SparseMemoryBindFlagBits as declared in vulkan/vulkan.h:909
type SparseMemoryBindFlagBits uint32

// SparseMemoryBindFlagBits enumeration from vulkan/vulkan.h:909
const (
	SparseMemoryBindMetadataBit SparseMemoryBindFlagBits = 1
)

// DisplayPlaneAlphaFlagBitsKHR as declared in vulkan/vulkan.h:3328
type DisplayPlaneAlphaFlagBitsKHR uint32

// DisplayPlaneAlphaFlagBitsKHR enumeration from vulkan/vulkan.h:3328
const (
	DisplayPlaneAlphaOpaqueBitKhr                DisplayPlaneAlphaFlagBitsKHR = 1
	DisplayPlaneAlphaGlobalBitKhr                DisplayPlaneAlphaFlagBitsKHR = 2
	DisplayPlaneAlphaPerPixelBitKhr              DisplayPlaneAlphaFlagBitsKHR = 4
	DisplayPlaneAlphaPerPixelPremultipliedBitKhr DisplayPlaneAlphaFlagBitsKHR = 8
)

// BlendOp as declared in vulkan/vulkan.h:661
type BlendOp uint32

// BlendOp enumeration from vulkan/vulkan.h:661
const (
	BlendOpAdd             BlendOp = 0
	BlendOpSubtract        BlendOp = 1
	BlendOpReverseSubtract BlendOp = 2
	BlendOpMin             BlendOp = 3
	BlendOpMax             BlendOp = 4
	BlendOpBeginRange      BlendOp = 0
	BlendOpEndRange        BlendOp = 4
	BlendOpRangeSize       BlendOp = 5
	BlendOpMaxEnum         BlendOp = 2147483647
)

// SubpassContents as declared in vulkan/vulkan.h:793
type SubpassContents uint32

// SubpassContents enumeration from vulkan/vulkan.h:793
const (
	SubpassContentsInline                  SubpassContents = 0
	SubpassContentsSecondaryCommandBuffers SubpassContents = 1
	SubpassContentsBeginRange              SubpassContents = 0
	SubpassContentsEndRange                SubpassContents = 1
	SubpassContentsRangeSize               SubpassContents = 2
	SubpassContentsMaxEnum                 SubpassContents = 2147483647
)

// FenceCreateFlagBits as declared in vulkan/vulkan.h:914
type FenceCreateFlagBits uint32

// FenceCreateFlagBits enumeration from vulkan/vulkan.h:914
const (
	FenceCreateSignaledBit FenceCreateFlagBits = 1
)

// ImageTiling as declared in vulkan/vulkan.h:448
type ImageTiling uint32

// ImageTiling enumeration from vulkan/vulkan.h:448
const (
	ImageTilingOptimal    ImageTiling = 0
	ImageTilingLinear     ImageTiling = 1
	ImageTilingBeginRange ImageTiling = 0
	ImageTilingEndRange   ImageTiling = 1
	ImageTilingRangeSize  ImageTiling = 2
	ImageTilingMaxEnum    ImageTiling = 2147483647
)

// LogicOp as declared in vulkan/vulkan.h:623
type LogicOp uint32

// LogicOp enumeration from vulkan/vulkan.h:623
const (
	LogicOpClear        LogicOp = 0
	LogicOpAnd          LogicOp = 1
	LogicOpAndReverse   LogicOp = 2
	LogicOpCopy         LogicOp = 3
	LogicOpAndInverted  LogicOp = 4
	LogicOpNoOp         LogicOp = 5
	LogicOpXor          LogicOp = 6
	LogicOpOr           LogicOp = 7
	LogicOpNor          LogicOp = 8
	LogicOpEquivalent   LogicOp = 9
	LogicOpInvert       LogicOp = 10
	LogicOpOrReverse    LogicOp = 11
	LogicOpCopyInverted LogicOp = 12
	LogicOpOrInverted   LogicOp = 13
	LogicOpNand         LogicOp = 14
	LogicOpSet          LogicOp = 15
	LogicOpBeginRange   LogicOp = 0
	LogicOpEndRange     LogicOp = 15
	LogicOpRangeSize    LogicOp = 16
	LogicOpMaxEnum      LogicOp = 2147483647
)

// Filter as declared in vulkan/vulkan.h:686
type Filter uint32

// Filter enumeration from vulkan/vulkan.h:686
const (
	FilterNearest    Filter = 0
	FilterLinear     Filter = 1
	FilterBeginRange Filter = 0
	FilterEndRange   Filter = 1
	FilterRangeSize  Filter = 2
	FilterMaxEnum    Filter = 2147483647
)

// CullModeFlagBits as declared in vulkan/vulkan.h:996
type CullModeFlagBits uint32

// CullModeFlagBits enumeration from vulkan/vulkan.h:996
const (
	CullModeNone         CullModeFlagBits = 0
	CullModeFrontBit     CullModeFlagBits = 1
	CullModeBackBit      CullModeFlagBits = 2
	CullModeFrontAndBack CullModeFlagBits = 3
)

// CompareOp as declared in vulkan/vulkan.h:585
type CompareOp uint32

// CompareOp enumeration from vulkan/vulkan.h:585
const (
	CompareOpNever          CompareOp = 0
	CompareOpLess           CompareOp = 1
	CompareOpEqual          CompareOp = 2
	CompareOpLessOrEqual    CompareOp = 3
	CompareOpGreater        CompareOp = 4
	CompareOpNotEqual       CompareOp = 5
	CompareOpGreaterOrEqual CompareOp = 6
	CompareOpAlways         CompareOp = 7
	CompareOpBeginRange     CompareOp = 0
	CompareOpEndRange       CompareOp = 7
	CompareOpRangeSize      CompareOp = 8
	CompareOpMaxEnum        CompareOp = 2147483647
)

// QueueFlagBits as declared in vulkan/vulkan.h:851
type QueueFlagBits uint32

// QueueFlagBits enumeration from vulkan/vulkan.h:851
const (
	QueueGraphicsBit      QueueFlagBits = 1
	QueueComputeBit       QueueFlagBits = 2
	QueueTransferBit      QueueFlagBits = 4
	QueueSparseBindingBit QueueFlagBits = 8
)

// BufferCreateFlagBits as declared in vulkan/vulkan.h:947
type BufferCreateFlagBits uint32

// BufferCreateFlagBits enumeration from vulkan/vulkan.h:947
const (
	BufferCreateSparseBindingBit   BufferCreateFlagBits = 1
	BufferCreateSparseResidencyBit BufferCreateFlagBits = 2
	BufferCreateSparseAliasedBit   BufferCreateFlagBits = 4
)

// InternalAllocationType as declared in vulkan/vulkan.h:237
type InternalAllocationType uint32

// InternalAllocationType enumeration from vulkan/vulkan.h:237
const (
	InternalAllocationTypeExecutable InternalAllocationType = 0
	InternalAllocationTypeBeginRange InternalAllocationType = 0
	InternalAllocationTypeEndRange   InternalAllocationType = 0
	InternalAllocationTypeRangeSize  InternalAllocationType = 1
	InternalAllocationTypeMaxEnum    InternalAllocationType = 2147483647
)

// PipelineBindPoint as declared in vulkan/vulkan.h:766
type PipelineBindPoint uint32

// PipelineBindPoint enumeration from vulkan/vulkan.h:766
const (
	PipelineBindPointGraphics   PipelineBindPoint = 0
	PipelineBindPointCompute    PipelineBindPoint = 1
	PipelineBindPointBeginRange PipelineBindPoint = 0
	PipelineBindPointEndRange   PipelineBindPoint = 1
	PipelineBindPointRangeSize  PipelineBindPoint = 2
	PipelineBindPointMaxEnum    PipelineBindPoint = 2147483647
)

// MemoryPropertyFlagBits as declared in vulkan/vulkan.h:860
type MemoryPropertyFlagBits uint32

// MemoryPropertyFlagBits enumeration from vulkan/vulkan.h:860
const (
	MemoryPropertyDeviceLocalBit     MemoryPropertyFlagBits = 1
	MemoryPropertyHostVisibleBit     MemoryPropertyFlagBits = 2
	MemoryPropertyHostCoherentBit    MemoryPropertyFlagBits = 4
	MemoryPropertyHostCachedBit      MemoryPropertyFlagBits = 8
	MemoryPropertyLazilyAllocatedBit MemoryPropertyFlagBits = 16
)

// ImageAspectFlagBits as declared in vulkan/vulkan.h:897
type ImageAspectFlagBits uint32

// ImageAspectFlagBits enumeration from vulkan/vulkan.h:897
const (
	ImageAspectColorBit    ImageAspectFlagBits = 1
	ImageAspectDepthBit    ImageAspectFlagBits = 2
	ImageAspectStencilBit  ImageAspectFlagBits = 4
	ImageAspectMetadataBit ImageAspectFlagBits = 8
)

// Format as declared in vulkan/vulkan.h:429
type Format uint32

// Format enumeration from vulkan/vulkan.h:429
const (
	FormatUndefined                Format = 0
	FormatR4g4UnormPack8           Format = 1
	FormatR4g4b4a4UnormPack16      Format = 2
	FormatB4g4r4a4UnormPack16      Format = 3
	FormatR5g6b5UnormPack16        Format = 4
	FormatB5g6r5UnormPack16        Format = 5
	FormatR5g5b5a1UnormPack16      Format = 6
	FormatB5g5r5a1UnormPack16      Format = 7
	FormatA1r5g5b5UnormPack16      Format = 8
	FormatR8Unorm                  Format = 9
	FormatR8Snorm                  Format = 10
	FormatR8Uscaled                Format = 11
	FormatR8Sscaled                Format = 12
	FormatR8Uint                   Format = 13
	FormatR8Sint                   Format = 14
	FormatR8Srgb                   Format = 15
	FormatR8g8Unorm                Format = 16
	FormatR8g8Snorm                Format = 17
	FormatR8g8Uscaled              Format = 18
	FormatR8g8Sscaled              Format = 19
	FormatR8g8Uint                 Format = 20
	FormatR8g8Sint                 Format = 21
	FormatR8g8Srgb                 Format = 22
	FormatR8g8b8Unorm              Format = 23
	FormatR8g8b8Snorm              Format = 24
	FormatR8g8b8Uscaled            Format = 25
	FormatR8g8b8Sscaled            Format = 26
	FormatR8g8b8Uint               Format = 27
	FormatR8g8b8Sint               Format = 28
	FormatR8g8b8Srgb               Format = 29
	FormatB8g8r8Unorm              Format = 30
	FormatB8g8r8Snorm              Format = 31
	FormatB8g8r8Uscaled            Format = 32
	FormatB8g8r8Sscaled            Format = 33
	FormatB8g8r8Uint               Format = 34
	FormatB8g8r8Sint               Format = 35
	FormatB8g8r8Srgb               Format = 36
	FormatR8g8b8a8Unorm            Format = 37
	FormatR8g8b8a8Snorm            Format = 38
	FormatR8g8b8a8Uscaled          Format = 39
	FormatR8g8b8a8Sscaled          Format = 40
	FormatR8g8b8a8Uint             Format = 41
	FormatR8g8b8a8Sint             Format = 42
	FormatR8g8b8a8Srgb             Format = 43
	FormatB8g8r8a8Unorm            Format = 44
	FormatB8g8r8a8Snorm            Format = 45
	FormatB8g8r8a8Uscaled          Format = 46
	FormatB8g8r8a8Sscaled          Format = 47
	FormatB8g8r8a8Uint             Format = 48
	FormatB8g8r8a8Sint             Format = 49
	FormatB8g8r8a8Srgb             Format = 50
	FormatA8b8g8r8UnormPack32      Format = 51
	FormatA8b8g8r8SnormPack32      Format = 52
	FormatA8b8g8r8UscaledPack32    Format = 53
	FormatA8b8g8r8SscaledPack32    Format = 54
	FormatA8b8g8r8UintPack32       Format = 55
	FormatA8b8g8r8SintPack32       Format = 56
	FormatA8b8g8r8SrgbPack32       Format = 57
	FormatA2r10g10b10UnormPack32   Format = 58
	FormatA2r10g10b10SnormPack32   Format = 59
	FormatA2r10g10b10UscaledPack32 Format = 60
	FormatA2r10g10b10SscaledPack32 Format = 61
	FormatA2r10g10b10UintPack32    Format = 62
	FormatA2r10g10b10SintPack32    Format = 63
	FormatA2b10g10r10UnormPack32   Format = 64
	FormatA2b10g10r10SnormPack32   Format = 65
	FormatA2b10g10r10UscaledPack32 Format = 66
	FormatA2b10g10r10SscaledPack32 Format = 67
	FormatA2b10g10r10UintPack32    Format = 68
	FormatA2b10g10r10SintPack32    Format = 69
	FormatR16Unorm                 Format = 70
	FormatR16Snorm                 Format = 71
	FormatR16Uscaled               Format = 72
	FormatR16Sscaled               Format = 73
	FormatR16Uint                  Format = 74
	FormatR16Sint                  Format = 75
	FormatR16Sfloat                Format = 76
	FormatR16g16Unorm              Format = 77
	FormatR16g16Snorm              Format = 78
	FormatR16g16Uscaled            Format = 79
	FormatR16g16Sscaled            Format = 80
	FormatR16g16Uint               Format = 81
	FormatR16g16Sint               Format = 82
	FormatR16g16Sfloat             Format = 83
	FormatR16g16b16Unorm           Format = 84
	FormatR16g16b16Snorm           Format = 85
	FormatR16g16b16Uscaled         Format = 86
	FormatR16g16b16Sscaled         Format = 87
	FormatR16g16b16Uint            Format = 88
	FormatR16g16b16Sint            Format = 89
	FormatR16g16b16Sfloat          Format = 90
	FormatR16g16b16a16Unorm        Format = 91
	FormatR16g16b16a16Snorm        Format = 92
	FormatR16g16b16a16Uscaled      Format = 93
	FormatR16g16b16a16Sscaled      Format = 94
	FormatR16g16b16a16Uint         Format = 95
	FormatR16g16b16a16Sint         Format = 96
	FormatR16g16b16a16Sfloat       Format = 97
	FormatR32Uint                  Format = 98
	FormatR32Sint                  Format = 99
	FormatR32Sfloat                Format = 100
	FormatR32g32Uint               Format = 101
	FormatR32g32Sint               Format = 102
	FormatR32g32Sfloat             Format = 103
	FormatR32g32b32Uint            Format = 104
	FormatR32g32b32Sint            Format = 105
	FormatR32g32b32Sfloat          Format = 106
	FormatR32g32b32a32Uint         Format = 107
	FormatR32g32b32a32Sint         Format = 108
	FormatR32g32b32a32Sfloat       Format = 109
	FormatR64Uint                  Format = 110
	FormatR64Sint                  Format = 111
	FormatR64Sfloat                Format = 112
	FormatR64g64Uint               Format = 113
	FormatR64g64Sint               Format = 114
	FormatR64g64Sfloat             Format = 115
	FormatR64g64b64Uint            Format = 116
	FormatR64g64b64Sint            Format = 117
	FormatR64g64b64Sfloat          Format = 118
	FormatR64g64b64a64Uint         Format = 119
	FormatR64g64b64a64Sint         Format = 120
	FormatR64g64b64a64Sfloat       Format = 121
	FormatB10g11r11UfloatPack32    Format = 122
	FormatE5b9g9r9UfloatPack32     Format = 123
	FormatD16Unorm                 Format = 124
	FormatX8D24UnormPack32         Format = 125
	FormatD32Sfloat                Format = 126
	FormatS8Uint                   Format = 127
	FormatD16UnormS8Uint           Format = 128
	FormatD24UnormS8Uint           Format = 129
	FormatD32SfloatS8Uint          Format = 130
	FormatBc1RgbUnormBlock         Format = 131
	FormatBc1RgbSrgbBlock          Format = 132
	FormatBc1RgbaUnormBlock        Format = 133
	FormatBc1RgbaSrgbBlock         Format = 134
	FormatBc2UnormBlock            Format = 135
	FormatBc2SrgbBlock             Format = 136
	FormatBc3UnormBlock            Format = 137
	FormatBc3SrgbBlock             Format = 138
	FormatBc4UnormBlock            Format = 139
	FormatBc4SnormBlock            Format = 140
	FormatBc5UnormBlock            Format = 141
	FormatBc5SnormBlock            Format = 142
	FormatBc6hUfloatBlock          Format = 143
	FormatBc6hSfloatBlock          Format = 144
	FormatBc7UnormBlock            Format = 145
	FormatBc7SrgbBlock             Format = 146
	FormatEtc2R8g8b8UnormBlock     Format = 147
	FormatEtc2R8g8b8SrgbBlock      Format = 148
	FormatEtc2R8g8b8a1UnormBlock   Format = 149
	FormatEtc2R8g8b8a1SrgbBlock    Format = 150
	FormatEtc2R8g8b8a8UnormBlock   Format = 151
	FormatEtc2R8g8b8a8SrgbBlock    Format = 152
	FormatEacR11UnormBlock         Format = 153
	FormatEacR11SnormBlock         Format = 154
	FormatEacR11g11UnormBlock      Format = 155
	FormatEacR11g11SnormBlock      Format = 156
	FormatAstc4x4UnormBlock        Format = 157
	FormatAstc4x4SrgbBlock         Format = 158
	FormatAstc5x4UnormBlock        Format = 159
	FormatAstc5x4SrgbBlock         Format = 160
	FormatAstc5x5UnormBlock        Format = 161
	FormatAstc5x5SrgbBlock         Format = 162
	FormatAstc6x5UnormBlock        Format = 163
	FormatAstc6x5SrgbBlock         Format = 164
	FormatAstc6x6UnormBlock        Format = 165
	FormatAstc6x6SrgbBlock         Format = 166
	FormatAstc8x5UnormBlock        Format = 167
	FormatAstc8x5SrgbBlock         Format = 168
	FormatAstc8x6UnormBlock        Format = 169
	FormatAstc8x6SrgbBlock         Format = 170
	FormatAstc8x8UnormBlock        Format = 171
	FormatAstc8x8SrgbBlock         Format = 172
	FormatAstc10x5UnormBlock       Format = 173
	FormatAstc10x5SrgbBlock        Format = 174
	FormatAstc10x6UnormBlock       Format = 175
	FormatAstc10x6SrgbBlock        Format = 176
	FormatAstc10x8UnormBlock       Format = 177
	FormatAstc10x8SrgbBlock        Format = 178
	FormatAstc10x10UnormBlock      Format = 179
	FormatAstc10x10SrgbBlock       Format = 180
	FormatAstc12x10UnormBlock      Format = 181
	FormatAstc12x10SrgbBlock       Format = 182
	FormatAstc12x12UnormBlock      Format = 183
	FormatAstc12x12SrgbBlock       Format = 184
	FormatBeginRange               Format = 0
	FormatEndRange                 Format = 184
	FormatRangeSize                Format = 185
	FormatMaxEnum                  Format = 2147483647
)

// ImageLayout as declared in vulkan/vulkan.h:496
type ImageLayout uint32

// ImageLayout enumeration from vulkan/vulkan.h:496
const (
	ImageLayoutUndefined                     ImageLayout = 0
	ImageLayoutGeneral                       ImageLayout = 1
	ImageLayoutColorAttachmentOptimal        ImageLayout = 2
	ImageLayoutDepthStencilAttachmentOptimal ImageLayout = 3
	ImageLayoutDepthStencilReadOnlyOptimal   ImageLayout = 4
	ImageLayoutShaderReadOnlyOptimal         ImageLayout = 5
	ImageLayoutTransferSrcOptimal            ImageLayout = 6
	ImageLayoutTransferDstOptimal            ImageLayout = 7
	ImageLayoutPreinitialized                ImageLayout = 8
	ImageLayoutPresentSrcKhr                 ImageLayout = 1000001002
	ImageLayoutBeginRange                    ImageLayout = 0
	ImageLayoutEndRange                      ImageLayout = 8
	ImageLayoutRangeSize                     ImageLayout = 9
	ImageLayoutMaxEnum                       ImageLayout = 2147483647
)

// FrontFace as declared in vulkan/vulkan.h:570
type FrontFace uint32

// FrontFace enumeration from vulkan/vulkan.h:570
const (
	FrontFaceCounterClockwise FrontFace = 0
	FrontFaceClockwise        FrontFace = 1
	FrontFaceBeginRange       FrontFace = 0
	FrontFaceEndRange         FrontFace = 1
	FrontFaceRangeSize        FrontFace = 2
	FrontFaceMaxEnum          FrontFace = 2147483647
)

// QueryResultFlagBits as declared in vulkan/vulkan.h:940
type QueryResultFlagBits uint32

// QueryResultFlagBits enumeration from vulkan/vulkan.h:940
const (
	QueryResult64Bit               QueryResultFlagBits = 1
	QueryResultWaitBit             QueryResultFlagBits = 2
	QueryResultWithAvailabilityBit QueryResultFlagBits = 4
	QueryResultPartialBit          QueryResultFlagBits = 8
)

// SurfaceTransformFlagBitsKHR as declared in vulkan/vulkan.h:3171
type SurfaceTransformFlagBitsKHR uint32

// SurfaceTransformFlagBitsKHR enumeration from vulkan/vulkan.h:3171
const (
	SurfaceTransformIdentityBitKhr                  SurfaceTransformFlagBitsKHR = 1
	SurfaceTransformRotate90BitKhr                  SurfaceTransformFlagBitsKHR = 2
	SurfaceTransformRotate180BitKhr                 SurfaceTransformFlagBitsKHR = 4
	SurfaceTransformRotate270BitKhr                 SurfaceTransformFlagBitsKHR = 8
	SurfaceTransformHorizontalMirrorBitKhr          SurfaceTransformFlagBitsKHR = 16
	SurfaceTransformHorizontalMirrorRotate90BitKhr  SurfaceTransformFlagBitsKHR = 32
	SurfaceTransformHorizontalMirrorRotate180BitKhr SurfaceTransformFlagBitsKHR = 64
	SurfaceTransformHorizontalMirrorRotate270BitKhr SurfaceTransformFlagBitsKHR = 128
	SurfaceTransformInheritBitKhr                   SurfaceTransformFlagBitsKHR = 256
)

// CompositeAlphaFlagBitsKHR as declared in vulkan/vulkan.h:3179
type CompositeAlphaFlagBitsKHR uint32

// CompositeAlphaFlagBitsKHR enumeration from vulkan/vulkan.h:3179
const (
	CompositeAlphaOpaqueBitKhr         CompositeAlphaFlagBitsKHR = 1
	CompositeAlphaPreMultipliedBitKhr  CompositeAlphaFlagBitsKHR = 2
	CompositeAlphaPostMultipliedBitKhr CompositeAlphaFlagBitsKHR = 4
	CompositeAlphaInheritBitKhr        CompositeAlphaFlagBitsKHR = 8
)

// CommandPoolResetFlagBits as declared in vulkan/vulkan.h:1063
type CommandPoolResetFlagBits uint32

// CommandPoolResetFlagBits enumeration from vulkan/vulkan.h:1063
const (
	CommandPoolResetReleaseResourcesBit CommandPoolResetFlagBits = 1
)

// PipelineCacheHeaderVersion as declared in vulkan/vulkan.h:119
type PipelineCacheHeaderVersion uint32

// PipelineCacheHeaderVersion enumeration from vulkan/vulkan.h:119
const (
	PipelineCacheHeaderVersionOne        PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionBeginRange PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionEndRange   PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionRangeSize  PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionMaxEnum    PipelineCacheHeaderVersion = 2147483647
)

// AttachmentStoreOp as declared in vulkan/vulkan.h:757
type AttachmentStoreOp uint32

// AttachmentStoreOp enumeration from vulkan/vulkan.h:757
const (
	AttachmentStoreOpStore      AttachmentStoreOp = 0
	AttachmentStoreOpDontCare   AttachmentStoreOp = 1
	AttachmentStoreOpBeginRange AttachmentStoreOp = 0
	AttachmentStoreOpEndRange   AttachmentStoreOp = 1
	AttachmentStoreOpRangeSize  AttachmentStoreOp = 2
	AttachmentStoreOpMaxEnum    AttachmentStoreOp = 2147483647
)

// ImageCreateFlagBits as declared in vulkan/vulkan.h:832
type ImageCreateFlagBits uint32

// ImageCreateFlagBits enumeration from vulkan/vulkan.h:832
const (
	ImageCreateSparseBindingBit   ImageCreateFlagBits = 1
	ImageCreateSparseResidencyBit ImageCreateFlagBits = 2
	ImageCreateSparseAliasedBit   ImageCreateFlagBits = 4
	ImageCreateMutableFormatBit   ImageCreateFlagBits = 8
	ImageCreateCubeCompatibleBit  ImageCreateFlagBits = 16
)

// AccessFlagBits as declared in vulkan/vulkan.h:1047
type AccessFlagBits uint32

// AccessFlagBits enumeration from vulkan/vulkan.h:1047
const (
	AccessIndirectCommandReadBit         AccessFlagBits = 1
	AccessIndexReadBit                   AccessFlagBits = 2
	AccessVertexAttributeReadBit         AccessFlagBits = 4
	AccessUniformReadBit                 AccessFlagBits = 8
	AccessInputAttachmentReadBit         AccessFlagBits = 16
	AccessShaderReadBit                  AccessFlagBits = 32
	AccessShaderWriteBit                 AccessFlagBits = 64
	AccessColorAttachmentReadBit         AccessFlagBits = 128
	AccessColorAttachmentWriteBit        AccessFlagBits = 256
	AccessDepthStencilAttachmentReadBit  AccessFlagBits = 512
	AccessDepthStencilAttachmentWriteBit AccessFlagBits = 1024
	AccessTransferReadBit                AccessFlagBits = 2048
	AccessTransferWriteBit               AccessFlagBits = 4096
	AccessHostReadBit                    AccessFlagBits = 8192
	AccessHostWriteBit                   AccessFlagBits = 16384
	AccessMemoryReadBit                  AccessFlagBits = 32768
	AccessMemoryWriteBit                 AccessFlagBits = 65536
)

// ColorSpaceKHR as declared in vulkan/vulkan.h:3147
type ColorSpaceKHR uint32

// ColorSpaceKHR enumeration from vulkan/vulkan.h:3147
const (
	ColorspaceSrgbNonlinearKhr ColorSpaceKHR = 0
	ColorspaceBeginRange       ColorSpaceKHR = 0
	ColorspaceEndRange         ColorSpaceKHR = 0
	ColorspaceRangeSize        ColorSpaceKHR = 1
	ColorspaceMaxEnum          ColorSpaceKHR = 2147483647
)

// SampleCountFlagBits as declared in vulkan/vulkan.h:843
type SampleCountFlagBits uint32

// SampleCountFlagBits enumeration from vulkan/vulkan.h:843
const (
	SampleCount1Bit  SampleCountFlagBits = 1
	SampleCount2Bit  SampleCountFlagBits = 2
	SampleCount4Bit  SampleCountFlagBits = 4
	SampleCount8Bit  SampleCountFlagBits = 8
	SampleCount16Bit SampleCountFlagBits = 16
	SampleCount32Bit SampleCountFlagBits = 32
	SampleCount64Bit SampleCountFlagBits = 64
)

// SamplerMipmapMode as declared in vulkan/vulkan.h:695
type SamplerMipmapMode uint32

// SamplerMipmapMode enumeration from vulkan/vulkan.h:695
const (
	SamplerMipmapModeNearest    SamplerMipmapMode = 0
	SamplerMipmapModeLinear     SamplerMipmapMode = 1
	SamplerMipmapModeBeginRange SamplerMipmapMode = 0
	SamplerMipmapModeEndRange   SamplerMipmapMode = 1
	SamplerMipmapModeRangeSize  SamplerMipmapMode = 2
	SamplerMipmapModeMaxEnum    SamplerMipmapMode = 2147483647
)

// AttachmentLoadOp as declared in vulkan/vulkan.h:748
type AttachmentLoadOp uint32

// AttachmentLoadOp enumeration from vulkan/vulkan.h:748
const (
	AttachmentLoadOpLoad       AttachmentLoadOp = 0
	AttachmentLoadOpClear      AttachmentLoadOp = 1
	AttachmentLoadOpDontCare   AttachmentLoadOp = 2
	AttachmentLoadOpBeginRange AttachmentLoadOp = 0
	AttachmentLoadOpEndRange   AttachmentLoadOp = 2
	AttachmentLoadOpRangeSize  AttachmentLoadOp = 3
	AttachmentLoadOpMaxEnum    AttachmentLoadOp = 2147483647
)

// FormatFeatureFlagBits as declared in vulkan/vulkan.h:811
type FormatFeatureFlagBits uint32

// FormatFeatureFlagBits enumeration from vulkan/vulkan.h:811
const (
	FormatFeatureSampledImageBit             FormatFeatureFlagBits = 1
	FormatFeatureStorageImageBit             FormatFeatureFlagBits = 2
	FormatFeatureStorageImageAtomicBit       FormatFeatureFlagBits = 4
	FormatFeatureUniformTexelBufferBit       FormatFeatureFlagBits = 8
	FormatFeatureStorageTexelBufferBit       FormatFeatureFlagBits = 16
	FormatFeatureStorageTexelBufferAtomicBit FormatFeatureFlagBits = 32
	FormatFeatureVertexBufferBit             FormatFeatureFlagBits = 64
	FormatFeatureColorAttachmentBit          FormatFeatureFlagBits = 128
	FormatFeatureColorAttachmentBlendBit     FormatFeatureFlagBits = 256
	FormatFeatureDepthStencilAttachmentBit   FormatFeatureFlagBits = 512
	FormatFeatureBlitSrcBit                  FormatFeatureFlagBits = 1024
	FormatFeatureBlitDstBit                  FormatFeatureFlagBits = 2048
	FormatFeatureSampledImageFilterLinearBit FormatFeatureFlagBits = 4096
)

// QueryControlFlagBits as declared in vulkan/vulkan.h:1075
type QueryControlFlagBits uint32

// QueryControlFlagBits enumeration from vulkan/vulkan.h:1075
const (
	QueryControlPreciseBit QueryControlFlagBits = 1
)

// ComponentSwizzle as declared in vulkan/vulkan.h:524
type ComponentSwizzle uint32

// ComponentSwizzle enumeration from vulkan/vulkan.h:524
const (
	ComponentSwizzleIdentity   ComponentSwizzle = 0
	ComponentSwizzleZero       ComponentSwizzle = 1
	ComponentSwizzleOne        ComponentSwizzle = 2
	ComponentSwizzleR          ComponentSwizzle = 3
	ComponentSwizzleG          ComponentSwizzle = 4
	ComponentSwizzleB          ComponentSwizzle = 5
	ComponentSwizzleA          ComponentSwizzle = 6
	ComponentSwizzleBeginRange ComponentSwizzle = 0
	ComponentSwizzleEndRange   ComponentSwizzle = 6
	ComponentSwizzleRangeSize  ComponentSwizzle = 7
	ComponentSwizzleMaxEnum    ComponentSwizzle = 2147483647
)

// IndexType as declared in vulkan/vulkan.h:784
type IndexType uint32

// IndexType enumeration from vulkan/vulkan.h:784
const (
	IndexTypeUint16     IndexType = 0
	IndexTypeUint32     IndexType = 1
	IndexTypeBeginRange IndexType = 0
	IndexTypeEndRange   IndexType = 1
	IndexTypeRangeSize  IndexType = 2
	IndexTypeMaxEnum    IndexType = 2147483647
)

// CommandPoolCreateFlagBits as declared in vulkan/vulkan.h:1058
type CommandPoolCreateFlagBits uint32

// CommandPoolCreateFlagBits enumeration from vulkan/vulkan.h:1058
const (
	CommandPoolCreateTransientBit          CommandPoolCreateFlagBits = 1
	CommandPoolCreateResetCommandBufferBit CommandPoolCreateFlagBits = 2
)

// DebugReportObjectTypeEXT as declared in vulkan/vulkan.h:3713
type DebugReportObjectTypeEXT uint32

// DebugReportObjectTypeEXT enumeration from vulkan/vulkan.h:3713
const (
	DebugReportObjectTypeUnknownExt             DebugReportObjectTypeEXT = 0
	DebugReportObjectTypeInstanceExt            DebugReportObjectTypeEXT = 1
	DebugReportObjectTypePhysicalDeviceExt      DebugReportObjectTypeEXT = 2
	DebugReportObjectTypeDeviceExt              DebugReportObjectTypeEXT = 3
	DebugReportObjectTypeQueueExt               DebugReportObjectTypeEXT = 4
	DebugReportObjectTypeSemaphoreExt           DebugReportObjectTypeEXT = 5
	DebugReportObjectTypeCommandBufferExt       DebugReportObjectTypeEXT = 6
	DebugReportObjectTypeFenceExt               DebugReportObjectTypeEXT = 7
	DebugReportObjectTypeDeviceMemoryExt        DebugReportObjectTypeEXT = 8
	DebugReportObjectTypeBufferExt              DebugReportObjectTypeEXT = 9
	DebugReportObjectTypeImageExt               DebugReportObjectTypeEXT = 10
	DebugReportObjectTypeEventExt               DebugReportObjectTypeEXT = 11
	DebugReportObjectTypeQueryPoolExt           DebugReportObjectTypeEXT = 12
	DebugReportObjectTypeBufferViewExt          DebugReportObjectTypeEXT = 13
	DebugReportObjectTypeImageViewExt           DebugReportObjectTypeEXT = 14
	DebugReportObjectTypeShaderModuleExt        DebugReportObjectTypeEXT = 15
	DebugReportObjectTypePipelineCacheExt       DebugReportObjectTypeEXT = 16
	DebugReportObjectTypePipelineLayoutExt      DebugReportObjectTypeEXT = 17
	DebugReportObjectTypeRenderPassExt          DebugReportObjectTypeEXT = 18
	DebugReportObjectTypePipelineExt            DebugReportObjectTypeEXT = 19
	DebugReportObjectTypeDescriptorSetLayoutExt DebugReportObjectTypeEXT = 20
	DebugReportObjectTypeSamplerExt             DebugReportObjectTypeEXT = 21
	DebugReportObjectTypeDescriptorPoolExt      DebugReportObjectTypeEXT = 22
	DebugReportObjectTypeDescriptorSetExt       DebugReportObjectTypeEXT = 23
	DebugReportObjectTypeFramebufferExt         DebugReportObjectTypeEXT = 24
	DebugReportObjectTypeCommandPoolExt         DebugReportObjectTypeEXT = 25
	DebugReportObjectTypeSurfaceKhrExt          DebugReportObjectTypeEXT = 26
	DebugReportObjectTypeSwapchainKhrExt        DebugReportObjectTypeEXT = 27
	DebugReportObjectTypeDebugReportExt         DebugReportObjectTypeEXT = 28
)

// QueryType as declared in vulkan/vulkan.h:470
type QueryType uint32

// QueryType enumeration from vulkan/vulkan.h:470
const (
	QueryTypeOcclusion          QueryType = 0
	QueryTypePipelineStatistics QueryType = 1
	QueryTypeTimestamp          QueryType = 2
	QueryTypeBeginRange         QueryType = 0
	QueryTypeEndRange           QueryType = 2
	QueryTypeRangeSize          QueryType = 3
	QueryTypeMaxEnum            QueryType = 2147483647
)

// SamplerAddressMode as declared in vulkan/vulkan.h:707
type SamplerAddressMode uint32

// SamplerAddressMode enumeration from vulkan/vulkan.h:707
const (
	SamplerAddressModeRepeat            SamplerAddressMode = 0
	SamplerAddressModeMirroredRepeat    SamplerAddressMode = 1
	SamplerAddressModeClampToEdge       SamplerAddressMode = 2
	SamplerAddressModeClampToBorder     SamplerAddressMode = 3
	SamplerAddressModeMirrorClampToEdge SamplerAddressMode = 4
	SamplerAddressModeBeginRange        SamplerAddressMode = 0
	SamplerAddressModeEndRange          SamplerAddressMode = 3
	SamplerAddressModeRangeSize         SamplerAddressMode = 4
	SamplerAddressModeMaxEnum           SamplerAddressMode = 2147483647
)

// StencilFaceFlagBits as declared in vulkan/vulkan.h:1087
type StencilFaceFlagBits uint32

// StencilFaceFlagBits enumeration from vulkan/vulkan.h:1087
const (
	StencilFaceFrontBit StencilFaceFlagBits = 1
	StencilFaceBackBit  StencilFaceFlagBits = 2
	StencilFrontAndBack StencilFaceFlagBits = 3
)

// CommandBufferLevel as declared in vulkan/vulkan.h:775
type CommandBufferLevel uint32

// CommandBufferLevel enumeration from vulkan/vulkan.h:775
const (
	CommandBufferLevelPrimary    CommandBufferLevel = 0
	CommandBufferLevelSecondary  CommandBufferLevel = 1
	CommandBufferLevelBeginRange CommandBufferLevel = 0
	CommandBufferLevelEndRange   CommandBufferLevel = 1
	CommandBufferLevelRangeSize  CommandBufferLevel = 2
	CommandBufferLevelMaxEnum    CommandBufferLevel = 2147483647
)

// PipelineCreateFlagBits as declared in vulkan/vulkan.h:971
type PipelineCreateFlagBits uint32

// PipelineCreateFlagBits enumeration from vulkan/vulkan.h:971
const (
	PipelineCreateDisableOptimizationBit PipelineCreateFlagBits = 1
	PipelineCreateAllowDerivativesBit    PipelineCreateFlagBits = 2
	PipelineCreateDerivativeBit          PipelineCreateFlagBits = 4
)

// ImageViewType as declared in vulkan/vulkan.h:510
type ImageViewType uint32

// ImageViewType enumeration from vulkan/vulkan.h:510
const (
	ImageViewType1d         ImageViewType = 0
	ImageViewType2d         ImageViewType = 1
	ImageViewType3d         ImageViewType = 2
	ImageViewTypeCube       ImageViewType = 3
	ImageViewType1dArray    ImageViewType = 4
	ImageViewType2dArray    ImageViewType = 5
	ImageViewTypeCubeArray  ImageViewType = 6
	ImageViewTypeBeginRange ImageViewType = 0
	ImageViewTypeEndRange   ImageViewType = 6
	ImageViewTypeRangeSize  ImageViewType = 7
	ImageViewTypeMaxEnum    ImageViewType = 2147483647
)

// DependencyFlagBits as declared in vulkan/vulkan.h:1052
type DependencyFlagBits uint32

// DependencyFlagBits enumeration from vulkan/vulkan.h:1052
const (
	DependencyByRegionBit DependencyFlagBits = 1
)

// DescriptorPoolCreateFlagBits as declared in vulkan/vulkan.h:1017
type DescriptorPoolCreateFlagBits uint32

// DescriptorPoolCreateFlagBits enumeration from vulkan/vulkan.h:1017
const (
	DescriptorPoolCreateFreeDescriptorSetBit DescriptorPoolCreateFlagBits = 1
)

// MemoryHeapFlagBits as declared in vulkan/vulkan.h:865
type MemoryHeapFlagBits uint32

// MemoryHeapFlagBits enumeration from vulkan/vulkan.h:865
const (
	MemoryHeapDeviceLocalBit MemoryHeapFlagBits = 1
)

// SparseImageFormatFlagBits as declared in vulkan/vulkan.h:904
type SparseImageFormatFlagBits uint32

// SparseImageFormatFlagBits enumeration from vulkan/vulkan.h:904
const (
	SparseImageFormatSingleMiptailBit        SparseImageFormatFlagBits = 1
	SparseImageFormatAlignedMipSizeBit       SparseImageFormatFlagBits = 2
	SparseImageFormatNonstandardBlockSizeBit SparseImageFormatFlagBits = 4
)

// BufferUsageFlagBits as declared in vulkan/vulkan.h:960
type BufferUsageFlagBits uint32

// BufferUsageFlagBits enumeration from vulkan/vulkan.h:960
const (
	BufferUsageTransferSrcBit        BufferUsageFlagBits = 1
	BufferUsageTransferDstBit        BufferUsageFlagBits = 2
	BufferUsageUniformTexelBufferBit BufferUsageFlagBits = 4
	BufferUsageStorageTexelBufferBit BufferUsageFlagBits = 8
	BufferUsageUniformBufferBit      BufferUsageFlagBits = 16
	BufferUsageStorageBufferBit      BufferUsageFlagBits = 32
	BufferUsageIndexBufferBit        BufferUsageFlagBits = 64
	BufferUsageVertexBufferBit       BufferUsageFlagBits = 128
	BufferUsageIndirectBufferBit     BufferUsageFlagBits = 256
)

// CommandBufferUsageFlagBits as declared in vulkan/vulkan.h:1070
type CommandBufferUsageFlagBits uint32

// CommandBufferUsageFlagBits enumeration from vulkan/vulkan.h:1070
const (
	CommandBufferUsageOneTimeSubmitBit      CommandBufferUsageFlagBits = 1
	CommandBufferUsageRenderPassContinueBit CommandBufferUsageFlagBits = 2
	CommandBufferUsageSimultaneousUseBit    CommandBufferUsageFlagBits = 4
)

// CommandBufferResetFlagBits as declared in vulkan/vulkan.h:1080
type CommandBufferResetFlagBits uint32

// CommandBufferResetFlagBits enumeration from vulkan/vulkan.h:1080
const (
	CommandBufferResetReleaseResourcesBit CommandBufferResetFlagBits = 1
)

// StencilOp as declared in vulkan/vulkan.h:600
type StencilOp uint32

// StencilOp enumeration from vulkan/vulkan.h:600
const (
	StencilOpKeep              StencilOp = 0
	StencilOpZero              StencilOp = 1
	StencilOpReplace           StencilOp = 2
	StencilOpIncrementAndClamp StencilOp = 3
	StencilOpDecrementAndClamp StencilOp = 4
	StencilOpInvert            StencilOp = 5
	StencilOpIncrementAndWrap  StencilOp = 6
	StencilOpDecrementAndWrap  StencilOp = 7
	StencilOpBeginRange        StencilOp = 0
	StencilOpEndRange          StencilOp = 7
	StencilOpRangeSize         StencilOp = 8
	StencilOpMaxEnum           StencilOp = 2147483647
)

// Result as declared in vulkan/vulkan.h:149
type Result int32

// Result enumeration from vulkan/vulkan.h:149
const (
	Success                     Result = 0
	NotReady                    Result = 1
	Timeout                     Result = 2
	EventSet                    Result = 3
	EventReset                  Result = 4
	Incomplete                  Result = 5
	ErrorOutOfHostMemory        Result = -1
	ErrorOutOfDeviceMemory      Result = -2
	ErrorInitializationFailed   Result = -3
	ErrorDeviceLost             Result = -4
	ErrorMemoryMapFailed        Result = -5
	ErrorLayerNotPresent        Result = -6
	ErrorExtensionNotPresent    Result = -7
	ErrorFeatureNotPresent      Result = -8
	ErrorIncompatibleDriver     Result = -9
	ErrorTooManyObjects         Result = -10
	ErrorFormatNotSupported     Result = -11
	ErrorSurfaceLostKhr         Result = -1000000000
	ErrorNativeWindowInUseKhr   Result = -1000000001
	SuboptimalKhr               Result = 1000001003
	ErrorOutOfDateKhr           Result = -1000001004
	ErrorIncompatibleDisplayKhr Result = -1000003001
	ErrorValidationFailedExt    Result = -1000011001
	ResultBeginRange            Result = -11
	ResultEndRange              Result = 5
	ResultRangeSize             Result = 17
	ResultMaxEnum               Result = 2147483647
)

// PipelineStageFlagBits as declared in vulkan/vulkan.h:888
type PipelineStageFlagBits uint32

// PipelineStageFlagBits enumeration from vulkan/vulkan.h:888
const (
	PipelineStageTopOfPipeBit                    PipelineStageFlagBits = 1
	PipelineStageDrawIndirectBit                 PipelineStageFlagBits = 2
	PipelineStageVertexInputBit                  PipelineStageFlagBits = 4
	PipelineStageVertexShaderBit                 PipelineStageFlagBits = 8
	PipelineStageTessellationControlShaderBit    PipelineStageFlagBits = 16
	PipelineStageTessellationEvaluationShaderBit PipelineStageFlagBits = 32
	PipelineStageGeometryShaderBit               PipelineStageFlagBits = 64
	PipelineStageFragmentShaderBit               PipelineStageFlagBits = 128
	PipelineStageEarlyFragmentTestsBit           PipelineStageFlagBits = 256
	PipelineStageLateFragmentTestsBit            PipelineStageFlagBits = 512
	PipelineStageColorAttachmentOutputBit        PipelineStageFlagBits = 1024
	PipelineStageComputeShaderBit                PipelineStageFlagBits = 2048
	PipelineStageTransferBit                     PipelineStageFlagBits = 4096
	PipelineStageBottomOfPipeBit                 PipelineStageFlagBits = 8192
	PipelineStageHostBit                         PipelineStageFlagBits = 16384
	PipelineStageAllGraphicsBit                  PipelineStageFlagBits = 32768
	PipelineStageAllCommandsBit                  PipelineStageFlagBits = 65536
)

// ColorComponentFlagBits as declared in vulkan/vulkan.h:1007
type ColorComponentFlagBits uint32

// ColorComponentFlagBits enumeration from vulkan/vulkan.h:1007
const (
	ColorComponentRBit ColorComponentFlagBits = 1
	ColorComponentGBit ColorComponentFlagBits = 2
	ColorComponentBBit ColorComponentFlagBits = 4
	ColorComponentABit ColorComponentFlagBits = 8
)

// DebugReportErrorEXT as declared in vulkan/vulkan.h:3718
type DebugReportErrorEXT uint32

// DebugReportErrorEXT enumeration from vulkan/vulkan.h:3718
const (
	DebugReportErrorNoneExt        DebugReportErrorEXT = 0
	DebugReportErrorCallbackRefExt DebugReportErrorEXT = 1
)

// SystemAllocationScope as declared in vulkan/vulkan.h:229
type SystemAllocationScope uint32

// SystemAllocationScope enumeration from vulkan/vulkan.h:229
const (
	SystemAllocationScopeCommand    SystemAllocationScope = 0
	SystemAllocationScopeObject     SystemAllocationScope = 1
	SystemAllocationScopeCache      SystemAllocationScope = 2
	SystemAllocationScopeDevice     SystemAllocationScope = 3
	SystemAllocationScopeInstance   SystemAllocationScope = 4
	SystemAllocationScopeBeginRange SystemAllocationScope = 0
	SystemAllocationScopeEndRange   SystemAllocationScope = 4
	SystemAllocationScopeRangeSize  SystemAllocationScope = 5
	SystemAllocationScopeMaxEnum    SystemAllocationScope = 2147483647
)

// StructureType as declared in vulkan/vulkan.h:217
type StructureType uint32

// StructureType enumeration from vulkan/vulkan.h:217
const (
	StructureTypeApplicationInfo                      StructureType = 0
	StructureTypeInstanceCreateInfo                   StructureType = 1
	StructureTypeDeviceQueueCreateInfo                StructureType = 2
	StructureTypeDeviceCreateInfo                     StructureType = 3
	StructureTypeSubmitInfo                           StructureType = 4
	StructureTypeMemoryAllocateInfo                   StructureType = 5
	StructureTypeMappedMemoryRange                    StructureType = 6
	StructureTypeBindSparseInfo                       StructureType = 7
	StructureTypeFenceCreateInfo                      StructureType = 8
	StructureTypeSemaphoreCreateInfo                  StructureType = 9
	StructureTypeEventCreateInfo                      StructureType = 10
	StructureTypeQueryPoolCreateInfo                  StructureType = 11
	StructureTypeBufferCreateInfo                     StructureType = 12
	StructureTypeBufferViewCreateInfo                 StructureType = 13
	StructureTypeImageCreateInfo                      StructureType = 14
	StructureTypeImageViewCreateInfo                  StructureType = 15
	StructureTypeShaderModuleCreateInfo               StructureType = 16
	StructureTypePipelineCacheCreateInfo              StructureType = 17
	StructureTypePipelineShaderStageCreateInfo        StructureType = 18
	StructureTypePipelineVertexInputStateCreateInfo   StructureType = 19
	StructureTypePipelineInputAssemblyStateCreateInfo StructureType = 20
	StructureTypePipelineTessellationStateCreateInfo  StructureType = 21
	StructureTypePipelineViewportStateCreateInfo      StructureType = 22
	StructureTypePipelineRasterizationStateCreateInfo StructureType = 23
	StructureTypePipelineMultisampleStateCreateInfo   StructureType = 24
	StructureTypePipelineDepthStencilStateCreateInfo  StructureType = 25
	StructureTypePipelineColorBlendStateCreateInfo    StructureType = 26
	StructureTypePipelineDynamicStateCreateInfo       StructureType = 27
	StructureTypeGraphicsPipelineCreateInfo           StructureType = 28
	StructureTypeComputePipelineCreateInfo            StructureType = 29
	StructureTypePipelineLayoutCreateInfo             StructureType = 30
	StructureTypeSamplerCreateInfo                    StructureType = 31
	StructureTypeDescriptorSetLayoutCreateInfo        StructureType = 32
	StructureTypeDescriptorPoolCreateInfo             StructureType = 33
	StructureTypeDescriptorSetAllocateInfo            StructureType = 34
	StructureTypeWriteDescriptorSet                   StructureType = 35
	StructureTypeCopyDescriptorSet                    StructureType = 36
	StructureTypeFramebufferCreateInfo                StructureType = 37
	StructureTypeRenderPassCreateInfo                 StructureType = 38
	StructureTypeCommandPoolCreateInfo                StructureType = 39
	StructureTypeCommandBufferAllocateInfo            StructureType = 40
	StructureTypeCommandBufferInheritanceInfo         StructureType = 41
	StructureTypeCommandBufferBeginInfo               StructureType = 42
	StructureTypeRenderPassBeginInfo                  StructureType = 43
	StructureTypeBufferMemoryBarrier                  StructureType = 44
	StructureTypeImageMemoryBarrier                   StructureType = 45
	StructureTypeMemoryBarrier                        StructureType = 46
	StructureTypeLoaderInstanceCreateInfo             StructureType = 47
	StructureTypeLoaderDeviceCreateInfo               StructureType = 48
	StructureTypeSwapchainCreateInfoKhr               StructureType = 1000001000
	StructureTypePresentInfoKhr                       StructureType = 1000001001
	StructureTypeDisplayModeCreateInfoKhr             StructureType = 1000002000
	StructureTypeDisplaySurfaceCreateInfoKhr          StructureType = 1000002001
	StructureTypeDisplayPresentInfoKhr                StructureType = 1000003000
	StructureTypeXlibSurfaceCreateInfoKhr             StructureType = 1000004000
	StructureTypeXcbSurfaceCreateInfoKhr              StructureType = 1000005000
	StructureTypeWaylandSurfaceCreateInfoKhr          StructureType = 1000006000
	StructureTypeMirSurfaceCreateInfoKhr              StructureType = 1000007000
	StructureTypeAndroidSurfaceCreateInfoKhr          StructureType = 1000008000
	StructureTypeWin32SurfaceCreateInfoKhr            StructureType = 1000009000
	StructureTypeDebugReportCallbackCreateInfoExt     StructureType = 1000011000
	StructureTypeBeginRange                           StructureType = 0
	StructureTypeEndRange                             StructureType = 48
	StructureTypeRangeSize                            StructureType = 49
	StructureTypeMaxEnum                              StructureType = 2147483647
)

// PhysicalDeviceType as declared in vulkan/vulkan.h:460
type PhysicalDeviceType uint32

// PhysicalDeviceType enumeration from vulkan/vulkan.h:460
const (
	PhysicalDeviceTypeOther         PhysicalDeviceType = 0
	PhysicalDeviceTypeIntegratedGpu PhysicalDeviceType = 1
	PhysicalDeviceTypeDiscreteGpu   PhysicalDeviceType = 2
	PhysicalDeviceTypeVirtualGpu    PhysicalDeviceType = 3
	PhysicalDeviceTypeCpu           PhysicalDeviceType = 4
	PhysicalDeviceTypeBeginRange    PhysicalDeviceType = 0
	PhysicalDeviceTypeEndRange      PhysicalDeviceType = 4
	PhysicalDeviceTypeRangeSize     PhysicalDeviceType = 5
	PhysicalDeviceTypeMaxEnum       PhysicalDeviceType = 2147483647
)

// DynamicState as declared in vulkan/vulkan.h:677
type DynamicState uint32

// DynamicState enumeration from vulkan/vulkan.h:677
const (
	DynamicStateViewport           DynamicState = 0
	DynamicStateScissor            DynamicState = 1
	DynamicStateLineWidth          DynamicState = 2
	DynamicStateDepthBias          DynamicState = 3
	DynamicStateBlendConstants     DynamicState = 4
	DynamicStateDepthBounds        DynamicState = 5
	DynamicStateStencilCompareMask DynamicState = 6
	DynamicStateStencilWriteMask   DynamicState = 7
	DynamicStateStencilReference   DynamicState = 8
	DynamicStateBeginRange         DynamicState = 0
	DynamicStateEndRange           DynamicState = 8
	DynamicStateRangeSize          DynamicState = 9
	DynamicStateMaxEnum            DynamicState = 2147483647
)

// PrimitiveTopology as declared in vulkan/vulkan.h:551
type PrimitiveTopology uint32

// PrimitiveTopology enumeration from vulkan/vulkan.h:551
const (
	PrimitiveTopologyPointList                  PrimitiveTopology = 0
	PrimitiveTopologyLineList                   PrimitiveTopology = 1
	PrimitiveTopologyLineStrip                  PrimitiveTopology = 2
	PrimitiveTopologyTriangleList               PrimitiveTopology = 3
	PrimitiveTopologyTriangleStrip              PrimitiveTopology = 4
	PrimitiveTopologyTriangleFan                PrimitiveTopology = 5
	PrimitiveTopologyLineListWithAdjacency      PrimitiveTopology = 6
	PrimitiveTopologyLineStripWithAdjacency     PrimitiveTopology = 7
	PrimitiveTopologyTriangleListWithAdjacency  PrimitiveTopology = 8
	PrimitiveTopologyTriangleStripWithAdjacency PrimitiveTopology = 9
	PrimitiveTopologyPatchList                  PrimitiveTopology = 10
	PrimitiveTopologyBeginRange                 PrimitiveTopology = 0
	PrimitiveTopologyEndRange                   PrimitiveTopology = 10
	PrimitiveTopologyRangeSize                  PrimitiveTopology = 11
	PrimitiveTopologyMaxEnum                    PrimitiveTopology = 2147483647
)

// PolygonMode as declared in vulkan/vulkan.h:561
type PolygonMode uint32

// PolygonMode enumeration from vulkan/vulkan.h:561
const (
	PolygonModeFill       PolygonMode = 0
	PolygonModeLine       PolygonMode = 1
	PolygonModePoint      PolygonMode = 2
	PolygonModeBeginRange PolygonMode = 0
	PolygonModeEndRange   PolygonMode = 2
	PolygonModeRangeSize  PolygonMode = 3
	PolygonModeMaxEnum    PolygonMode = 2147483647
)

// ShaderStageFlagBits as declared in vulkan/vulkan.h:984
type ShaderStageFlagBits uint32

// ShaderStageFlagBits enumeration from vulkan/vulkan.h:984
const (
	ShaderStageVertexBit                 ShaderStageFlagBits = 1
	ShaderStageTessellationControlBit    ShaderStageFlagBits = 2
	ShaderStageTessellationEvaluationBit ShaderStageFlagBits = 4
	ShaderStageGeometryBit               ShaderStageFlagBits = 8
	ShaderStageFragmentBit               ShaderStageFlagBits = 16
	ShaderStageComputeBit                ShaderStageFlagBits = 32
	ShaderStageAllGraphics               ShaderStageFlagBits = 31
	ShaderStageAll                       ShaderStageFlagBits = 2147483647
)

// AttachmentDescriptionFlagBits as declared in vulkan/vulkan.h:1025
type AttachmentDescriptionFlagBits uint32

// AttachmentDescriptionFlagBits enumeration from vulkan/vulkan.h:1025
const (
	AttachmentDescriptionMayAliasBit AttachmentDescriptionFlagBits = 1
)

// DebugReportFlagBitsEXT as declared in vulkan/vulkan.h:3727
type DebugReportFlagBitsEXT uint32

// DebugReportFlagBitsEXT enumeration from vulkan/vulkan.h:3727
const (
	DebugReportInformationBitExt        DebugReportFlagBitsEXT = 1
	DebugReportWarningBitExt            DebugReportFlagBitsEXT = 2
	DebugReportPerformanceWarningBitExt DebugReportFlagBitsEXT = 4
	DebugReportErrorBitExt              DebugReportFlagBitsEXT = 8
	DebugReportDebugBitExt              DebugReportFlagBitsEXT = 16
)

// ImageType as declared in vulkan/vulkan.h:439
type ImageType uint32

// ImageType enumeration from vulkan/vulkan.h:439
const (
	ImageType1d         ImageType = 0
	ImageType2d         ImageType = 1
	ImageType3d         ImageType = 2
	ImageTypeBeginRange ImageType = 0
	ImageTypeEndRange   ImageType = 2
	ImageTypeRangeSize  ImageType = 3
	ImageTypeMaxEnum    ImageType = 2147483647
)

// BlendFactor as declared in vulkan/vulkan.h:649
type BlendFactor uint32

// BlendFactor enumeration from vulkan/vulkan.h:649
const (
	BlendFactorZero                  BlendFactor = 0
	BlendFactorOne                   BlendFactor = 1
	BlendFactorSrcColor              BlendFactor = 2
	BlendFactorOneMinusSrcColor      BlendFactor = 3
	BlendFactorDstColor              BlendFactor = 4
	BlendFactorOneMinusDstColor      BlendFactor = 5
	BlendFactorSrcAlpha              BlendFactor = 6
	BlendFactorOneMinusSrcAlpha      BlendFactor = 7
	BlendFactorDstAlpha              BlendFactor = 8
	BlendFactorOneMinusDstAlpha      BlendFactor = 9
	BlendFactorConstantColor         BlendFactor = 10
	BlendFactorOneMinusConstantColor BlendFactor = 11
	BlendFactorConstantAlpha         BlendFactor = 12
	BlendFactorOneMinusConstantAlpha BlendFactor = 13
	BlendFactorSrcAlphaSaturate      BlendFactor = 14
	BlendFactorSrc1Color             BlendFactor = 15
	BlendFactorOneMinusSrc1Color     BlendFactor = 16
	BlendFactorSrc1Alpha             BlendFactor = 17
	BlendFactorOneMinusSrc1Alpha     BlendFactor = 18
	BlendFactorBeginRange            BlendFactor = 0
	BlendFactorEndRange              BlendFactor = 18
	BlendFactorRangeSize             BlendFactor = 19
	BlendFactorMaxEnum               BlendFactor = 2147483647
)

// DescriptorType as declared in vulkan/vulkan.h:738
type DescriptorType uint32

// DescriptorType enumeration from vulkan/vulkan.h:738
const (
	DescriptorTypeSampler              DescriptorType = 0
	DescriptorTypeCombinedImageSampler DescriptorType = 1
	DescriptorTypeSampledImage         DescriptorType = 2
	DescriptorTypeStorageImage         DescriptorType = 3
	DescriptorTypeUniformTexelBuffer   DescriptorType = 4
	DescriptorTypeStorageTexelBuffer   DescriptorType = 5
	DescriptorTypeUniformBuffer        DescriptorType = 6
	DescriptorTypeStorageBuffer        DescriptorType = 7
	DescriptorTypeUniformBufferDynamic DescriptorType = 8
	DescriptorTypeStorageBufferDynamic DescriptorType = 9
	DescriptorTypeInputAttachment      DescriptorType = 10
	DescriptorTypeBeginRange           DescriptorType = 0
	DescriptorTypeEndRange             DescriptorType = 10
	DescriptorTypeRangeSize            DescriptorType = 11
	DescriptorTypeMaxEnum              DescriptorType = 2147483647
)

// SharingMode as declared in vulkan/vulkan.h:479
type SharingMode uint32

// SharingMode enumeration from vulkan/vulkan.h:479
const (
	SharingModeExclusive  SharingMode = 0
	SharingModeConcurrent SharingMode = 1
	SharingModeBeginRange SharingMode = 0
	SharingModeEndRange   SharingMode = 1
	SharingModeRangeSize  SharingMode = 2
	SharingModeMaxEnum    SharingMode = 2147483647
)

// QueryPipelineStatisticFlagBits as declared in vulkan/vulkan.h:932
type QueryPipelineStatisticFlagBits uint32

// QueryPipelineStatisticFlagBits enumeration from vulkan/vulkan.h:932
const (
	QueryPipelineStatisticInputAssemblyVerticesBit                   QueryPipelineStatisticFlagBits = 1
	QueryPipelineStatisticInputAssemblyPrimitivesBit                 QueryPipelineStatisticFlagBits = 2
	QueryPipelineStatisticVertexShaderInvocationsBit                 QueryPipelineStatisticFlagBits = 4
	QueryPipelineStatisticGeometryShaderInvocationsBit               QueryPipelineStatisticFlagBits = 8
	QueryPipelineStatisticGeometryShaderPrimitivesBit                QueryPipelineStatisticFlagBits = 16
	QueryPipelineStatisticClippingInvocationsBit                     QueryPipelineStatisticFlagBits = 32
	QueryPipelineStatisticClippingPrimitivesBit                      QueryPipelineStatisticFlagBits = 64
	QueryPipelineStatisticFragmentShaderInvocationsBit               QueryPipelineStatisticFlagBits = 128
	QueryPipelineStatisticTessellationControlShaderPatchesBit        QueryPipelineStatisticFlagBits = 256
	QueryPipelineStatisticTessellationEvaluationShaderInvocationsBit QueryPipelineStatisticFlagBits = 512
	QueryPipelineStatisticComputeShaderInvocationsBit                QueryPipelineStatisticFlagBits = 1024
)

// PresentModeKHR as declared in vulkan/vulkan.h:3158
type PresentModeKHR uint32

// PresentModeKHR enumeration from vulkan/vulkan.h:3158
const (
	PresentModeImmediateKhr   PresentModeKHR = 0
	PresentModeMailboxKhr     PresentModeKHR = 1
	PresentModeFifoKhr        PresentModeKHR = 2
	PresentModeFifoRelaxedKhr PresentModeKHR = 3
	PresentModeBeginRange     PresentModeKHR = 0
	PresentModeEndRange       PresentModeKHR = 3
	PresentModeRangeSize      PresentModeKHR = 4
	PresentModeMaxEnum        PresentModeKHR = 2147483647
)
