// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Sun, 06 Nov 2016 00:25:27 MSK.
// By https://git.io/cgogen. DO NOT EDIT.

package vulkan

/*
#cgo CFLAGS: -I. -DVK_NO_PROTOTYPES
#include "vulkan/vulkan.h"
#include "vk_wrapper.h"
#include "vk_bridge.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// NoPrototypes as defined in vulkan/<predefine>:23
	NoPrototypes = 1
	// UsePlatformWin32 as defined in https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkVK_USE_PLATFORM_WIN32_KHR
	UsePlatformWin32 = 1
	// Version10 as defined in vulkan/vulkan.h:30
	Version10 = 1
	// ApiVersion10 as defined in vulkan/vulkan.h:40
	ApiVersion10 = 4194304
	// HeaderVersion as defined in vulkan/vulkan.h:46
	HeaderVersion = 32
	// NullHandle as defined in vulkan/vulkan.h:49
	NullHandle = 0
	// LodClampNone as defined in vulkan/vulkan.h:97
	LodClampNone = 1000.0
	// RemainingMipLevels as defined in vulkan/vulkan.h:98
	RemainingMipLevels = (^uint32(0))
	// RemainingArrayLayers as defined in vulkan/vulkan.h:99
	RemainingArrayLayers = (^uint32(0))
	// WholeSize as defined in vulkan/vulkan.h:100
	WholeSize = (^uint64(0))
	// AttachmentUnused as defined in vulkan/vulkan.h:101
	AttachmentUnused = (^uint32(0))
	// True as defined in vulkan/vulkan.h:102
	True = 1
	// False as defined in vulkan/vulkan.h:103
	False = 0
	// QueueFamilyIgnored as defined in vulkan/vulkan.h:104
	QueueFamilyIgnored = (^uint32(0))
	// SubpassExternal as defined in vulkan/vulkan.h:105
	SubpassExternal = (^uint32(0))
	// MaxPhysicalDeviceNameSize as defined in vulkan/vulkan.h:106
	MaxPhysicalDeviceNameSize = 256
	// UuidSize as defined in vulkan/vulkan.h:107
	UuidSize = 16
	// MaxMemoryTypes as defined in vulkan/vulkan.h:108
	MaxMemoryTypes = 32
	// MaxMemoryHeaps as defined in vulkan/vulkan.h:109
	MaxMemoryHeaps = 16
	// MaxExtensionNameSize as defined in vulkan/vulkan.h:110
	MaxExtensionNameSize = 256
	// MaxDescriptionSize as defined in vulkan/vulkan.h:111
	MaxDescriptionSize = 256
	// KhrSurface as defined in vulkan/vulkan.h:3190
	KhrSurface = 1
	// KhrSurfaceSpecVersion as defined in vulkan/vulkan.h:3193
	KhrSurfaceSpecVersion = 25
	// KhrSurfaceExtensionName as defined in vulkan/vulkan.h:3194
	KhrSurfaceExtensionName = "VK_KHR_surface"
	// ColorspaceSrgbNonlinear as defined in https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkVK_COLORSPACE_SRGB_NONLINEAR_KHR
	ColorspaceSrgbNonlinear = 0
	// KhrSwapchain as defined in vulkan/vulkan.h:3296
	KhrSwapchain = 1
	// KhrSwapchainSpecVersion as defined in vulkan/vulkan.h:3299
	KhrSwapchainSpecVersion = 68
	// KhrSwapchainExtensionName as defined in vulkan/vulkan.h:3300
	KhrSwapchainExtensionName = "VK_KHR_swapchain"
	// KhrDisplay as defined in vulkan/vulkan.h:3374
	KhrDisplay = 1
	// KhrDisplaySpecVersion as defined in vulkan/vulkan.h:3378
	KhrDisplaySpecVersion = 21
	// KhrDisplayExtensionName as defined in vulkan/vulkan.h:3379
	KhrDisplayExtensionName = "VK_KHR_display"
	// KhrDisplaySwapchain as defined in vulkan/vulkan.h:3502
	KhrDisplaySwapchain = 1
	// KhrDisplaySwapchainSpecVersion as defined in vulkan/vulkan.h:3503
	KhrDisplaySwapchainSpecVersion = 9
	// KhrDisplaySwapchainExtensionName as defined in vulkan/vulkan.h:3504
	KhrDisplaySwapchainExtensionName = "VK_KHR_display_swapchain"
	// KhrWin32Surface as defined in vulkan/vulkan.h:3697
	KhrWin32Surface = 1
	// KhrWin32SurfaceSpecVersion as defined in vulkan/vulkan.h:3700
	KhrWin32SurfaceSpecVersion = 5
	// KhrWin32SurfaceExtensionName as defined in vulkan/vulkan.h:3701
	KhrWin32SurfaceExtensionName = "VK_KHR_win32_surface"
	// KhrSamplerMirrorClampToEdge as defined in vulkan/vulkan.h:3730
	KhrSamplerMirrorClampToEdge = 1
	// KhrSamplerMirrorClampToEdgeSpecVersion as defined in vulkan/vulkan.h:3731
	KhrSamplerMirrorClampToEdgeSpecVersion = 1
	// KhrSamplerMirrorClampToEdgeExtensionName as defined in vulkan/vulkan.h:3732
	KhrSamplerMirrorClampToEdgeExtensionName = "VK_KHR_sampler_mirror_clamp_to_edge"
	// ExtDebugReport as defined in vulkan/vulkan.h:3735
	ExtDebugReport = 1
	// ExtDebugReportSpecVersion as defined in vulkan/vulkan.h:3738
	ExtDebugReportSpecVersion = 3
	// ExtDebugReportExtensionName as defined in vulkan/vulkan.h:3739
	ExtDebugReportExtensionName = "VK_EXT_debug_report"
	// StructureTypeDebugReportCreateInfo as defined in vulkan/vulkan.h:3740
	StructureTypeDebugReportCreateInfo = 0
	// NvGlslShader as defined in vulkan/vulkan.h:3846
	NvGlslShader = 1
	// NvGlslShaderSpecVersion as defined in vulkan/vulkan.h:3847
	NvGlslShaderSpecVersion = 1
	// NvGlslShaderExtensionName as defined in vulkan/vulkan.h:3848
	NvGlslShaderExtensionName = "VK_NV_glsl_shader"
	// ImgFilterCubic as defined in vulkan/vulkan.h:3851
	ImgFilterCubic = 1
	// ImgFilterCubicSpecVersion as defined in vulkan/vulkan.h:3852
	ImgFilterCubicSpecVersion = 1
	// ImgFilterCubicExtensionName as defined in vulkan/vulkan.h:3853
	ImgFilterCubicExtensionName = "VK_IMG_filter_cubic"
	// AmdRasterizationOrder as defined in vulkan/vulkan.h:3856
	AmdRasterizationOrder = 1
	// AmdRasterizationOrderSpecVersion as defined in vulkan/vulkan.h:3857
	AmdRasterizationOrderSpecVersion = 1
	// AmdRasterizationOrderExtensionName as defined in vulkan/vulkan.h:3858
	AmdRasterizationOrderExtensionName = "VK_AMD_rasterization_order"
	// AmdShaderTrinaryMinmax as defined in vulkan/vulkan.h:3878
	AmdShaderTrinaryMinmax = 1
	// AmdShaderTrinaryMinmaxSpecVersion as defined in vulkan/vulkan.h:3879
	AmdShaderTrinaryMinmaxSpecVersion = 1
	// AmdShaderTrinaryMinmaxExtensionName as defined in vulkan/vulkan.h:3880
	AmdShaderTrinaryMinmaxExtensionName = "VK_AMD_shader_trinary_minmax"
	// AmdShaderExplicitVertexParameter as defined in vulkan/vulkan.h:3883
	AmdShaderExplicitVertexParameter = 1
	// AmdShaderExplicitVertexParameterSpecVersion as defined in vulkan/vulkan.h:3884
	AmdShaderExplicitVertexParameterSpecVersion = 1
	// AmdShaderExplicitVertexParameterExtensionName as defined in vulkan/vulkan.h:3885
	AmdShaderExplicitVertexParameterExtensionName = "VK_AMD_shader_explicit_vertex_parameter"
	// ExtDebugMarker as defined in vulkan/vulkan.h:3888
	ExtDebugMarker = 1
	// ExtDebugMarkerSpecVersion as defined in vulkan/vulkan.h:3889
	ExtDebugMarkerSpecVersion = 3
	// ExtDebugMarkerExtensionName as defined in vulkan/vulkan.h:3890
	ExtDebugMarkerExtensionName = "VK_EXT_debug_marker"
	// AmdGcnShader as defined in vulkan/vulkan.h:3945
	AmdGcnShader = 1
	// AmdGcnShaderSpecVersion as defined in vulkan/vulkan.h:3946
	AmdGcnShaderSpecVersion = 1
	// AmdGcnShaderExtensionName as defined in vulkan/vulkan.h:3947
	AmdGcnShaderExtensionName = "VK_AMD_gcn_shader"
	// NvDedicatedAllocation as defined in vulkan/vulkan.h:3950
	NvDedicatedAllocation = 1
	// NvDedicatedAllocationSpecVersion as defined in vulkan/vulkan.h:3951
	NvDedicatedAllocationSpecVersion = 1
	// NvDedicatedAllocationExtensionName as defined in vulkan/vulkan.h:3952
	NvDedicatedAllocationExtensionName = "VK_NV_dedicated_allocation"
	// AmdDrawIndirectCount as defined in vulkan/vulkan.h:3975
	AmdDrawIndirectCount = 1
	// AmdDrawIndirectCountSpecVersion as defined in vulkan/vulkan.h:3976
	AmdDrawIndirectCountSpecVersion = 1
	// AmdDrawIndirectCountExtensionName as defined in vulkan/vulkan.h:3977
	AmdDrawIndirectCountExtensionName = "VK_AMD_draw_indirect_count"
	// AmdNegativeViewportHeight as defined in vulkan/vulkan.h:4002
	AmdNegativeViewportHeight = 1
	// AmdNegativeViewportHeightSpecVersion as defined in vulkan/vulkan.h:4003
	AmdNegativeViewportHeightSpecVersion = 1
	// AmdNegativeViewportHeightExtensionName as defined in vulkan/vulkan.h:4004
	AmdNegativeViewportHeightExtensionName = "VK_AMD_negative_viewport_height"
	// AmdGpuShaderHalfFloat as defined in vulkan/vulkan.h:4007
	AmdGpuShaderHalfFloat = 1
	// AmdGpuShaderHalfFloatSpecVersion as defined in vulkan/vulkan.h:4008
	AmdGpuShaderHalfFloatSpecVersion = 1
	// AmdGpuShaderHalfFloatExtensionName as defined in vulkan/vulkan.h:4009
	AmdGpuShaderHalfFloatExtensionName = "VK_AMD_gpu_shader_half_float"
	// AmdShaderBallot as defined in vulkan/vulkan.h:4012
	AmdShaderBallot = 1
	// AmdShaderBallotSpecVersion as defined in vulkan/vulkan.h:4013
	AmdShaderBallotSpecVersion = 1
	// AmdShaderBallotExtensionName as defined in vulkan/vulkan.h:4014
	AmdShaderBallotExtensionName = "VK_AMD_shader_ballot"
	// ImgFormatPvrtc as defined in vulkan/vulkan.h:4017
	ImgFormatPvrtc = 1
	// ImgFormatPvrtcSpecVersion as defined in vulkan/vulkan.h:4018
	ImgFormatPvrtcSpecVersion = 1
	// ImgFormatPvrtcExtensionName as defined in vulkan/vulkan.h:4019
	ImgFormatPvrtcExtensionName = "VK_IMG_format_pvrtc"
	// NvExternalMemoryCapabilities as defined in vulkan/vulkan.h:4022
	NvExternalMemoryCapabilities = 1
	// NvExternalMemoryCapabilitiesSpecVersion as defined in vulkan/vulkan.h:4023
	NvExternalMemoryCapabilitiesSpecVersion = 1
	// NvExternalMemoryCapabilitiesExtensionName as defined in vulkan/vulkan.h:4024
	NvExternalMemoryCapabilitiesExtensionName = "VK_NV_external_memory_capabilities"
	// NvExternalMemory as defined in vulkan/vulkan.h:4066
	NvExternalMemory = 1
	// NvExternalMemorySpecVersion as defined in vulkan/vulkan.h:4067
	NvExternalMemorySpecVersion = 1
	// NvExternalMemoryExtensionName as defined in vulkan/vulkan.h:4068
	NvExternalMemoryExtensionName = "VK_NV_external_memory"
	// NvExternalMemoryWin32 as defined in vulkan/vulkan.h:4085
	NvExternalMemoryWin32 = 1
	// NvExternalMemoryWin32SpecVersion as defined in vulkan/vulkan.h:4086
	NvExternalMemoryWin32SpecVersion = 1
	// NvExternalMemoryWin32ExtensionName as defined in vulkan/vulkan.h:4087
	NvExternalMemoryWin32ExtensionName = "VK_NV_external_memory_win32"
	// NvWin32KeyedMutex as defined in vulkan/vulkan.h:4116
	NvWin32KeyedMutex = 1
	// NvWin32KeyedMutexSpecVersion as defined in vulkan/vulkan.h:4117
	NvWin32KeyedMutexSpecVersion = 1
	// NvWin32KeyedMutexExtensionName as defined in vulkan/vulkan.h:4118
	NvWin32KeyedMutexExtensionName = "VK_NV_win32_keyed_mutex"
	// ExtValidationFlags as defined in vulkan/vulkan.h:4135
	ExtValidationFlags = 1
	// ExtValidationFlagsSpecVersion as defined in vulkan/vulkan.h:4136
	ExtValidationFlagsSpecVersion = 1
	// ExtValidationFlagsExtensionName as defined in vulkan/vulkan.h:4137
	ExtValidationFlagsExtensionName = "VK_EXT_validation_flags"
)

// PipelineCacheHeaderVersion as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineCacheHeaderVersion.html
type PipelineCacheHeaderVersion int32

// PipelineCacheHeaderVersion enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineCacheHeaderVersion.html
const (
	PipelineCacheHeaderVersionOne        PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionBeginRange PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionEndRange   PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionRangeSize  PipelineCacheHeaderVersion = 1
	PipelineCacheHeaderVersionMaxEnum    PipelineCacheHeaderVersion = 2147483647
)

// Result as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkResult.html
type Result int32

// Result enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkResult.html
const (
	Success                   Result = iota
	NotReady                  Result = 1
	Timeout                   Result = 2
	EventSet                  Result = 3
	EventReset                Result = 4
	Incomplete                Result = 5
	ErrorOutOfHostMemory      Result = -1
	ErrorOutOfDeviceMemory    Result = -2
	ErrorInitializationFailed Result = -3
	ErrorDeviceLost           Result = -4
	ErrorMemoryMapFailed      Result = -5
	ErrorLayerNotPresent      Result = -6
	ErrorExtensionNotPresent  Result = -7
	ErrorFeatureNotPresent    Result = -8
	ErrorIncompatibleDriver   Result = -9
	ErrorTooManyObjects       Result = -10
	ErrorFormatNotSupported   Result = -11
	ErrorFragmentedPool       Result = -12
	ErrorSurfaceLost          Result = -1000000000
	ErrorNativeWindowInUse    Result = -1000000001
	Suboptimal                Result = 1000001003
	ErrorOutOfDate            Result = -1000001004
	ErrorIncompatibleDisplay  Result = -1000003001
	ErrorValidationFailed     Result = -1000011001
	ErrorInvalidShaderNv      Result = -1000012000
	ResultBeginRange          Result = -12
	ResultEndRange            Result = 5
	ResultRangeSize           Result = 18
	ResultMaxEnum             Result = 2147483647
)

// StructureType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkStructureType.html
type StructureType int32

// StructureType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkStructureType.html
const (
	StructureTypeApplicationInfo                                 StructureType = iota
	StructureTypeInstanceCreateInfo                              StructureType = 1
	StructureTypeDeviceQueueCreateInfo                           StructureType = 2
	StructureTypeDeviceCreateInfo                                StructureType = 3
	StructureTypeSubmitInfo                                      StructureType = 4
	StructureTypeMemoryAllocateInfo                              StructureType = 5
	StructureTypeMappedMemoryRange                               StructureType = 6
	StructureTypeBindSparseInfo                                  StructureType = 7
	StructureTypeFenceCreateInfo                                 StructureType = 8
	StructureTypeSemaphoreCreateInfo                             StructureType = 9
	StructureTypeEventCreateInfo                                 StructureType = 10
	StructureTypeQueryPoolCreateInfo                             StructureType = 11
	StructureTypeBufferCreateInfo                                StructureType = 12
	StructureTypeBufferViewCreateInfo                            StructureType = 13
	StructureTypeImageCreateInfo                                 StructureType = 14
	StructureTypeImageViewCreateInfo                             StructureType = 15
	StructureTypeShaderModuleCreateInfo                          StructureType = 16
	StructureTypePipelineCacheCreateInfo                         StructureType = 17
	StructureTypePipelineShaderStageCreateInfo                   StructureType = 18
	StructureTypePipelineVertexInputStateCreateInfo              StructureType = 19
	StructureTypePipelineInputAssemblyStateCreateInfo            StructureType = 20
	StructureTypePipelineTessellationStateCreateInfo             StructureType = 21
	StructureTypePipelineViewportStateCreateInfo                 StructureType = 22
	StructureTypePipelineRasterizationStateCreateInfo            StructureType = 23
	StructureTypePipelineMultisampleStateCreateInfo              StructureType = 24
	StructureTypePipelineDepthStencilStateCreateInfo             StructureType = 25
	StructureTypePipelineColorBlendStateCreateInfo               StructureType = 26
	StructureTypePipelineDynamicStateCreateInfo                  StructureType = 27
	StructureTypeGraphicsPipelineCreateInfo                      StructureType = 28
	StructureTypeComputePipelineCreateInfo                       StructureType = 29
	StructureTypePipelineLayoutCreateInfo                        StructureType = 30
	StructureTypeSamplerCreateInfo                               StructureType = 31
	StructureTypeDescriptorSetLayoutCreateInfo                   StructureType = 32
	StructureTypeDescriptorPoolCreateInfo                        StructureType = 33
	StructureTypeDescriptorSetAllocateInfo                       StructureType = 34
	StructureTypeWriteDescriptorSet                              StructureType = 35
	StructureTypeCopyDescriptorSet                               StructureType = 36
	StructureTypeFramebufferCreateInfo                           StructureType = 37
	StructureTypeRenderPassCreateInfo                            StructureType = 38
	StructureTypeCommandPoolCreateInfo                           StructureType = 39
	StructureTypeCommandBufferAllocateInfo                       StructureType = 40
	StructureTypeCommandBufferInheritanceInfo                    StructureType = 41
	StructureTypeCommandBufferBeginInfo                          StructureType = 42
	StructureTypeRenderPassBeginInfo                             StructureType = 43
	StructureTypeBufferMemoryBarrier                             StructureType = 44
	StructureTypeImageMemoryBarrier                              StructureType = 45
	StructureTypeMemoryBarrier                                   StructureType = 46
	StructureTypeLoaderInstanceCreateInfo                        StructureType = 47
	StructureTypeLoaderDeviceCreateInfo                          StructureType = 48
	StructureTypeSwapchainCreateInfo                             StructureType = 1000001000
	StructureTypePresentInfo                                     StructureType = 1000001001
	StructureTypeDisplayModeCreateInfo                           StructureType = 1000002000
	StructureTypeDisplaySurfaceCreateInfo                        StructureType = 1000002001
	StructureTypeDisplayPresentInfo                              StructureType = 1000003000
	StructureTypeXlibSurfaceCreateInfo                           StructureType = 1000004000
	StructureTypeXcbSurfaceCreateInfo                            StructureType = 1000005000
	StructureTypeWaylandSurfaceCreateInfo                        StructureType = 1000006000
	StructureTypeMirSurfaceCreateInfo                            StructureType = 1000007000
	StructureTypeAndroidSurfaceCreateInfo                        StructureType = 1000008000
	StructureTypeWin32SurfaceCreateInfo                          StructureType = 1000009000
	StructureTypeDebugReportCallbackCreateInfo                   StructureType = 1000011000
	StructureTypePipelineRasterizationStateRasterizationOrderAmd StructureType = 1000018000
	StructureTypeDebugMarkerObjectNameInfo                       StructureType = 1000022000
	StructureTypeDebugMarkerObjectTagInfo                        StructureType = 1000022001
	StructureTypeDebugMarkerMarkerInfo                           StructureType = 1000022002
	StructureTypeDedicatedAllocationImageCreateInfoNv            StructureType = 1000026000
	StructureTypeDedicatedAllocationBufferCreateInfoNv           StructureType = 1000026001
	StructureTypeDedicatedAllocationMemoryAllocateInfoNv         StructureType = 1000026002
	StructureTypeExternalMemoryImageCreateInfoNv                 StructureType = 1000056000
	StructureTypeExportMemoryAllocateInfoNv                      StructureType = 1000056001
	StructureTypeImportMemoryWin32HandleInfoNv                   StructureType = 1000057000
	StructureTypeExportMemoryWin32HandleInfoNv                   StructureType = 1000057001
	StructureTypeWin32KeyedMutexAcquireReleaseInfoNv             StructureType = 1000058000
	StructureTypeValidationFlags                                 StructureType = 1000061000
	StructureTypeBeginRange                                      StructureType = 0
	StructureTypeEndRange                                        StructureType = 48
	StructureTypeRangeSize                                       StructureType = 49
	StructureTypeMaxEnum                                         StructureType = 2147483647
)

// SystemAllocationScope as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSystemAllocationScope.html
type SystemAllocationScope int32

// SystemAllocationScope enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSystemAllocationScope.html
const (
	SystemAllocationScopeCommand    SystemAllocationScope = iota
	SystemAllocationScopeObject     SystemAllocationScope = 1
	SystemAllocationScopeCache      SystemAllocationScope = 2
	SystemAllocationScopeDevice     SystemAllocationScope = 3
	SystemAllocationScopeInstance   SystemAllocationScope = 4
	SystemAllocationScopeBeginRange SystemAllocationScope = 0
	SystemAllocationScopeEndRange   SystemAllocationScope = 4
	SystemAllocationScopeRangeSize  SystemAllocationScope = 5
	SystemAllocationScopeMaxEnum    SystemAllocationScope = 2147483647
)

// InternalAllocationType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkInternalAllocationType.html
type InternalAllocationType int32

// InternalAllocationType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkInternalAllocationType.html
const (
	InternalAllocationTypeExecutable InternalAllocationType = iota
	InternalAllocationTypeBeginRange InternalAllocationType = 0
	InternalAllocationTypeEndRange   InternalAllocationType = 0
	InternalAllocationTypeRangeSize  InternalAllocationType = 1
	InternalAllocationTypeMaxEnum    InternalAllocationType = 2147483647
)

// Format as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFormat.html
type Format int32

// Format enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFormat.html
const (
	FormatUndefined                Format = iota
	FormatR4g4UnormPack8           Format = 1
	FormatR4g4b4a4UnormPack16      Format = 2
	FormatB4g4r4a4UnormPack16      Format = 3
	FormatR5g6b5UnormPack16        Format = 4
	FormatB5g6r5UnormPack16        Format = 5
	FormatR5g5b5a1UnormPack16      Format = 6
	FormatB5g5r5a1UnormPack16      Format = 7
	FormatA1r5g5b5UnormPack16      Format = 8
	FormatR8Unorm                  Format = 9
	FormatR8Snorm                  Format = 10
	FormatR8Uscaled                Format = 11
	FormatR8Sscaled                Format = 12
	FormatR8Uint                   Format = 13
	FormatR8Sint                   Format = 14
	FormatR8Srgb                   Format = 15
	FormatR8g8Unorm                Format = 16
	FormatR8g8Snorm                Format = 17
	FormatR8g8Uscaled              Format = 18
	FormatR8g8Sscaled              Format = 19
	FormatR8g8Uint                 Format = 20
	FormatR8g8Sint                 Format = 21
	FormatR8g8Srgb                 Format = 22
	FormatR8g8b8Unorm              Format = 23
	FormatR8g8b8Snorm              Format = 24
	FormatR8g8b8Uscaled            Format = 25
	FormatR8g8b8Sscaled            Format = 26
	FormatR8g8b8Uint               Format = 27
	FormatR8g8b8Sint               Format = 28
	FormatR8g8b8Srgb               Format = 29
	FormatB8g8r8Unorm              Format = 30
	FormatB8g8r8Snorm              Format = 31
	FormatB8g8r8Uscaled            Format = 32
	FormatB8g8r8Sscaled            Format = 33
	FormatB8g8r8Uint               Format = 34
	FormatB8g8r8Sint               Format = 35
	FormatB8g8r8Srgb               Format = 36
	FormatR8g8b8a8Unorm            Format = 37
	FormatR8g8b8a8Snorm            Format = 38
	FormatR8g8b8a8Uscaled          Format = 39
	FormatR8g8b8a8Sscaled          Format = 40
	FormatR8g8b8a8Uint             Format = 41
	FormatR8g8b8a8Sint             Format = 42
	FormatR8g8b8a8Srgb             Format = 43
	FormatB8g8r8a8Unorm            Format = 44
	FormatB8g8r8a8Snorm            Format = 45
	FormatB8g8r8a8Uscaled          Format = 46
	FormatB8g8r8a8Sscaled          Format = 47
	FormatB8g8r8a8Uint             Format = 48
	FormatB8g8r8a8Sint             Format = 49
	FormatB8g8r8a8Srgb             Format = 50
	FormatA8b8g8r8UnormPack32      Format = 51
	FormatA8b8g8r8SnormPack32      Format = 52
	FormatA8b8g8r8UscaledPack32    Format = 53
	FormatA8b8g8r8SscaledPack32    Format = 54
	FormatA8b8g8r8UintPack32       Format = 55
	FormatA8b8g8r8SintPack32       Format = 56
	FormatA8b8g8r8SrgbPack32       Format = 57
	FormatA2r10g10b10UnormPack32   Format = 58
	FormatA2r10g10b10SnormPack32   Format = 59
	FormatA2r10g10b10UscaledPack32 Format = 60
	FormatA2r10g10b10SscaledPack32 Format = 61
	FormatA2r10g10b10UintPack32    Format = 62
	FormatA2r10g10b10SintPack32    Format = 63
	FormatA2b10g10r10UnormPack32   Format = 64
	FormatA2b10g10r10SnormPack32   Format = 65
	FormatA2b10g10r10UscaledPack32 Format = 66
	FormatA2b10g10r10SscaledPack32 Format = 67
	FormatA2b10g10r10UintPack32    Format = 68
	FormatA2b10g10r10SintPack32    Format = 69
	FormatR16Unorm                 Format = 70
	FormatR16Snorm                 Format = 71
	FormatR16Uscaled               Format = 72
	FormatR16Sscaled               Format = 73
	FormatR16Uint                  Format = 74
	FormatR16Sint                  Format = 75
	FormatR16Sfloat                Format = 76
	FormatR16g16Unorm              Format = 77
	FormatR16g16Snorm              Format = 78
	FormatR16g16Uscaled            Format = 79
	FormatR16g16Sscaled            Format = 80
	FormatR16g16Uint               Format = 81
	FormatR16g16Sint               Format = 82
	FormatR16g16Sfloat             Format = 83
	FormatR16g16b16Unorm           Format = 84
	FormatR16g16b16Snorm           Format = 85
	FormatR16g16b16Uscaled         Format = 86
	FormatR16g16b16Sscaled         Format = 87
	FormatR16g16b16Uint            Format = 88
	FormatR16g16b16Sint            Format = 89
	FormatR16g16b16Sfloat          Format = 90
	FormatR16g16b16a16Unorm        Format = 91
	FormatR16g16b16a16Snorm        Format = 92
	FormatR16g16b16a16Uscaled      Format = 93
	FormatR16g16b16a16Sscaled      Format = 94
	FormatR16g16b16a16Uint         Format = 95
	FormatR16g16b16a16Sint         Format = 96
	FormatR16g16b16a16Sfloat       Format = 97
	FormatR32Uint                  Format = 98
	FormatR32Sint                  Format = 99
	FormatR32Sfloat                Format = 100
	FormatR32g32Uint               Format = 101
	FormatR32g32Sint               Format = 102
	FormatR32g32Sfloat             Format = 103
	FormatR32g32b32Uint            Format = 104
	FormatR32g32b32Sint            Format = 105
	FormatR32g32b32Sfloat          Format = 106
	FormatR32g32b32a32Uint         Format = 107
	FormatR32g32b32a32Sint         Format = 108
	FormatR32g32b32a32Sfloat       Format = 109
	FormatR64Uint                  Format = 110
	FormatR64Sint                  Format = 111
	FormatR64Sfloat                Format = 112
	FormatR64g64Uint               Format = 113
	FormatR64g64Sint               Format = 114
	FormatR64g64Sfloat             Format = 115
	FormatR64g64b64Uint            Format = 116
	FormatR64g64b64Sint            Format = 117
	FormatR64g64b64Sfloat          Format = 118
	FormatR64g64b64a64Uint         Format = 119
	FormatR64g64b64a64Sint         Format = 120
	FormatR64g64b64a64Sfloat       Format = 121
	FormatB10g11r11UfloatPack32    Format = 122
	FormatE5b9g9r9UfloatPack32     Format = 123
	FormatD16Unorm                 Format = 124
	FormatX8D24UnormPack32         Format = 125
	FormatD32Sfloat                Format = 126
	FormatS8Uint                   Format = 127
	FormatD16UnormS8Uint           Format = 128
	FormatD24UnormS8Uint           Format = 129
	FormatD32SfloatS8Uint          Format = 130
	FormatBc1RgbUnormBlock         Format = 131
	FormatBc1RgbSrgbBlock          Format = 132
	FormatBc1RgbaUnormBlock        Format = 133
	FormatBc1RgbaSrgbBlock         Format = 134
	FormatBc2UnormBlock            Format = 135
	FormatBc2SrgbBlock             Format = 136
	FormatBc3UnormBlock            Format = 137
	FormatBc3SrgbBlock             Format = 138
	FormatBc4UnormBlock            Format = 139
	FormatBc4SnormBlock            Format = 140
	FormatBc5UnormBlock            Format = 141
	FormatBc5SnormBlock            Format = 142
	FormatBc6hUfloatBlock          Format = 143
	FormatBc6hSfloatBlock          Format = 144
	FormatBc7UnormBlock            Format = 145
	FormatBc7SrgbBlock             Format = 146
	FormatEtc2R8g8b8UnormBlock     Format = 147
	FormatEtc2R8g8b8SrgbBlock      Format = 148
	FormatEtc2R8g8b8a1UnormBlock   Format = 149
	FormatEtc2R8g8b8a1SrgbBlock    Format = 150
	FormatEtc2R8g8b8a8UnormBlock   Format = 151
	FormatEtc2R8g8b8a8SrgbBlock    Format = 152
	FormatEacR11UnormBlock         Format = 153
	FormatEacR11SnormBlock         Format = 154
	FormatEacR11g11UnormBlock      Format = 155
	FormatEacR11g11SnormBlock      Format = 156
	FormatAstc4x4UnormBlock        Format = 157
	FormatAstc4x4SrgbBlock         Format = 158
	FormatAstc5x4UnormBlock        Format = 159
	FormatAstc5x4SrgbBlock         Format = 160
	FormatAstc5x5UnormBlock        Format = 161
	FormatAstc5x5SrgbBlock         Format = 162
	FormatAstc6x5UnormBlock        Format = 163
	FormatAstc6x5SrgbBlock         Format = 164
	FormatAstc6x6UnormBlock        Format = 165
	FormatAstc6x6SrgbBlock         Format = 166
	FormatAstc8x5UnormBlock        Format = 167
	FormatAstc8x5SrgbBlock         Format = 168
	FormatAstc8x6UnormBlock        Format = 169
	FormatAstc8x6SrgbBlock         Format = 170
	FormatAstc8x8UnormBlock        Format = 171
	FormatAstc8x8SrgbBlock         Format = 172
	FormatAstc10x5UnormBlock       Format = 173
	FormatAstc10x5SrgbBlock        Format = 174
	FormatAstc10x6UnormBlock       Format = 175
	FormatAstc10x6SrgbBlock        Format = 176
	FormatAstc10x8UnormBlock       Format = 177
	FormatAstc10x8SrgbBlock        Format = 178
	FormatAstc10x10UnormBlock      Format = 179
	FormatAstc10x10SrgbBlock       Format = 180
	FormatAstc12x10UnormBlock      Format = 181
	FormatAstc12x10SrgbBlock       Format = 182
	FormatAstc12x12UnormBlock      Format = 183
	FormatAstc12x12SrgbBlock       Format = 184
	FormatPvrtc12bppUnormBlockImg  Format = 1000054000
	FormatPvrtc14bppUnormBlockImg  Format = 1000054001
	FormatPvrtc22bppUnormBlockImg  Format = 1000054002
	FormatPvrtc24bppUnormBlockImg  Format = 1000054003
	FormatPvrtc12bppSrgbBlockImg   Format = 1000054004
	FormatPvrtc14bppSrgbBlockImg   Format = 1000054005
	FormatPvrtc22bppSrgbBlockImg   Format = 1000054006
	FormatPvrtc24bppSrgbBlockImg   Format = 1000054007
	FormatBeginRange               Format = 0
	FormatEndRange                 Format = 184
	FormatRangeSize                Format = 185
	FormatMaxEnum                  Format = 2147483647
)

// ImageType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageType.html
type ImageType int32

// ImageType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageType.html
const (
	ImageType1d         ImageType = iota
	ImageType2d         ImageType = 1
	ImageType3d         ImageType = 2
	ImageTypeBeginRange ImageType = 0
	ImageTypeEndRange   ImageType = 2
	ImageTypeRangeSize  ImageType = 3
	ImageTypeMaxEnum    ImageType = 2147483647
)

// ImageTiling as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageTiling.html
type ImageTiling int32

// ImageTiling enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageTiling.html
const (
	ImageTilingOptimal    ImageTiling = iota
	ImageTilingLinear     ImageTiling = 1
	ImageTilingBeginRange ImageTiling = 0
	ImageTilingEndRange   ImageTiling = 1
	ImageTilingRangeSize  ImageTiling = 2
	ImageTilingMaxEnum    ImageTiling = 2147483647
)

// PhysicalDeviceType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPhysicalDeviceType.html
type PhysicalDeviceType int32

// PhysicalDeviceType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPhysicalDeviceType.html
const (
	PhysicalDeviceTypeOther         PhysicalDeviceType = iota
	PhysicalDeviceTypeIntegratedGpu PhysicalDeviceType = 1
	PhysicalDeviceTypeDiscreteGpu   PhysicalDeviceType = 2
	PhysicalDeviceTypeVirtualGpu    PhysicalDeviceType = 3
	PhysicalDeviceTypeCpu           PhysicalDeviceType = 4
	PhysicalDeviceTypeBeginRange    PhysicalDeviceType = 0
	PhysicalDeviceTypeEndRange      PhysicalDeviceType = 4
	PhysicalDeviceTypeRangeSize     PhysicalDeviceType = 5
	PhysicalDeviceTypeMaxEnum       PhysicalDeviceType = 2147483647
)

// QueryType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryType.html
type QueryType int32

// QueryType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryType.html
const (
	QueryTypeOcclusion          QueryType = iota
	QueryTypePipelineStatistics QueryType = 1
	QueryTypeTimestamp          QueryType = 2
	QueryTypeBeginRange         QueryType = 0
	QueryTypeEndRange           QueryType = 2
	QueryTypeRangeSize          QueryType = 3
	QueryTypeMaxEnum            QueryType = 2147483647
)

// SharingMode as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSharingMode.html
type SharingMode int32

// SharingMode enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSharingMode.html
const (
	SharingModeExclusive  SharingMode = iota
	SharingModeConcurrent SharingMode = 1
	SharingModeBeginRange SharingMode = 0
	SharingModeEndRange   SharingMode = 1
	SharingModeRangeSize  SharingMode = 2
	SharingModeMaxEnum    SharingMode = 2147483647
)

// ImageLayout as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageLayout.html
type ImageLayout int32

// ImageLayout enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageLayout.html
const (
	ImageLayoutUndefined                     ImageLayout = iota
	ImageLayoutGeneral                       ImageLayout = 1
	ImageLayoutColorAttachmentOptimal        ImageLayout = 2
	ImageLayoutDepthStencilAttachmentOptimal ImageLayout = 3
	ImageLayoutDepthStencilReadOnlyOptimal   ImageLayout = 4
	ImageLayoutShaderReadOnlyOptimal         ImageLayout = 5
	ImageLayoutTransferSrcOptimal            ImageLayout = 6
	ImageLayoutTransferDstOptimal            ImageLayout = 7
	ImageLayoutPreinitialized                ImageLayout = 8
	ImageLayoutPresentSrc                    ImageLayout = 1000001002
	ImageLayoutBeginRange                    ImageLayout = 0
	ImageLayoutEndRange                      ImageLayout = 8
	ImageLayoutRangeSize                     ImageLayout = 9
	ImageLayoutMaxEnum                       ImageLayout = 2147483647
)

// ImageViewType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageViewType.html
type ImageViewType int32

// ImageViewType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageViewType.html
const (
	ImageViewType1d         ImageViewType = iota
	ImageViewType2d         ImageViewType = 1
	ImageViewType3d         ImageViewType = 2
	ImageViewTypeCube       ImageViewType = 3
	ImageViewType1dArray    ImageViewType = 4
	ImageViewType2dArray    ImageViewType = 5
	ImageViewTypeCubeArray  ImageViewType = 6
	ImageViewTypeBeginRange ImageViewType = 0
	ImageViewTypeEndRange   ImageViewType = 6
	ImageViewTypeRangeSize  ImageViewType = 7
	ImageViewTypeMaxEnum    ImageViewType = 2147483647
)

// ComponentSwizzle as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkComponentSwizzle.html
type ComponentSwizzle int32

// ComponentSwizzle enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkComponentSwizzle.html
const (
	ComponentSwizzleIdentity   ComponentSwizzle = iota
	ComponentSwizzleZero       ComponentSwizzle = 1
	ComponentSwizzleOne        ComponentSwizzle = 2
	ComponentSwizzleR          ComponentSwizzle = 3
	ComponentSwizzleG          ComponentSwizzle = 4
	ComponentSwizzleB          ComponentSwizzle = 5
	ComponentSwizzleA          ComponentSwizzle = 6
	ComponentSwizzleBeginRange ComponentSwizzle = 0
	ComponentSwizzleEndRange   ComponentSwizzle = 6
	ComponentSwizzleRangeSize  ComponentSwizzle = 7
	ComponentSwizzleMaxEnum    ComponentSwizzle = 2147483647
)

// VertexInputRate as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkVertexInputRate.html
type VertexInputRate int32

// VertexInputRate enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkVertexInputRate.html
const (
	VertexInputRateVertex     VertexInputRate = iota
	VertexInputRateInstance   VertexInputRate = 1
	VertexInputRateBeginRange VertexInputRate = 0
	VertexInputRateEndRange   VertexInputRate = 1
	VertexInputRateRangeSize  VertexInputRate = 2
	VertexInputRateMaxEnum    VertexInputRate = 2147483647
)

// PrimitiveTopology as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPrimitiveTopology.html
type PrimitiveTopology int32

// PrimitiveTopology enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPrimitiveTopology.html
const (
	PrimitiveTopologyPointList                  PrimitiveTopology = iota
	PrimitiveTopologyLineList                   PrimitiveTopology = 1
	PrimitiveTopologyLineStrip                  PrimitiveTopology = 2
	PrimitiveTopologyTriangleList               PrimitiveTopology = 3
	PrimitiveTopologyTriangleStrip              PrimitiveTopology = 4
	PrimitiveTopologyTriangleFan                PrimitiveTopology = 5
	PrimitiveTopologyLineListWithAdjacency      PrimitiveTopology = 6
	PrimitiveTopologyLineStripWithAdjacency     PrimitiveTopology = 7
	PrimitiveTopologyTriangleListWithAdjacency  PrimitiveTopology = 8
	PrimitiveTopologyTriangleStripWithAdjacency PrimitiveTopology = 9
	PrimitiveTopologyPatchList                  PrimitiveTopology = 10
	PrimitiveTopologyBeginRange                 PrimitiveTopology = 0
	PrimitiveTopologyEndRange                   PrimitiveTopology = 10
	PrimitiveTopologyRangeSize                  PrimitiveTopology = 11
	PrimitiveTopologyMaxEnum                    PrimitiveTopology = 2147483647
)

// PolygonMode as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPolygonMode.html
type PolygonMode int32

// PolygonMode enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPolygonMode.html
const (
	PolygonModeFill       PolygonMode = iota
	PolygonModeLine       PolygonMode = 1
	PolygonModePoint      PolygonMode = 2
	PolygonModeBeginRange PolygonMode = 0
	PolygonModeEndRange   PolygonMode = 2
	PolygonModeRangeSize  PolygonMode = 3
	PolygonModeMaxEnum    PolygonMode = 2147483647
)

// FrontFace as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFrontFace.html
type FrontFace int32

// FrontFace enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFrontFace.html
const (
	FrontFaceCounterClockwise FrontFace = iota
	FrontFaceClockwise        FrontFace = 1
	FrontFaceBeginRange       FrontFace = 0
	FrontFaceEndRange         FrontFace = 1
	FrontFaceRangeSize        FrontFace = 2
	FrontFaceMaxEnum          FrontFace = 2147483647
)

// CompareOp as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCompareOp.html
type CompareOp int32

// CompareOp enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCompareOp.html
const (
	CompareOpNever          CompareOp = iota
	CompareOpLess           CompareOp = 1
	CompareOpEqual          CompareOp = 2
	CompareOpLessOrEqual    CompareOp = 3
	CompareOpGreater        CompareOp = 4
	CompareOpNotEqual       CompareOp = 5
	CompareOpGreaterOrEqual CompareOp = 6
	CompareOpAlways         CompareOp = 7
	CompareOpBeginRange     CompareOp = 0
	CompareOpEndRange       CompareOp = 7
	CompareOpRangeSize      CompareOp = 8
	CompareOpMaxEnum        CompareOp = 2147483647
)

// StencilOp as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkStencilOp.html
type StencilOp int32

// StencilOp enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkStencilOp.html
const (
	StencilOpKeep              StencilOp = iota
	StencilOpZero              StencilOp = 1
	StencilOpReplace           StencilOp = 2
	StencilOpIncrementAndClamp StencilOp = 3
	StencilOpDecrementAndClamp StencilOp = 4
	StencilOpInvert            StencilOp = 5
	StencilOpIncrementAndWrap  StencilOp = 6
	StencilOpDecrementAndWrap  StencilOp = 7
	StencilOpBeginRange        StencilOp = 0
	StencilOpEndRange          StencilOp = 7
	StencilOpRangeSize         StencilOp = 8
	StencilOpMaxEnum           StencilOp = 2147483647
)

// LogicOp as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkLogicOp.html
type LogicOp int32

// LogicOp enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkLogicOp.html
const (
	LogicOpClear        LogicOp = iota
	LogicOpAnd          LogicOp = 1
	LogicOpAndReverse   LogicOp = 2
	LogicOpCopy         LogicOp = 3
	LogicOpAndInverted  LogicOp = 4
	LogicOpNoOp         LogicOp = 5
	LogicOpXor          LogicOp = 6
	LogicOpOr           LogicOp = 7
	LogicOpNor          LogicOp = 8
	LogicOpEquivalent   LogicOp = 9
	LogicOpInvert       LogicOp = 10
	LogicOpOrReverse    LogicOp = 11
	LogicOpCopyInverted LogicOp = 12
	LogicOpOrInverted   LogicOp = 13
	LogicOpNand         LogicOp = 14
	LogicOpSet          LogicOp = 15
	LogicOpBeginRange   LogicOp = 0
	LogicOpEndRange     LogicOp = 15
	LogicOpRangeSize    LogicOp = 16
	LogicOpMaxEnum      LogicOp = 2147483647
)

// BlendFactor as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBlendFactor.html
type BlendFactor int32

// BlendFactor enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBlendFactor.html
const (
	BlendFactorZero                  BlendFactor = iota
	BlendFactorOne                   BlendFactor = 1
	BlendFactorSrcColor              BlendFactor = 2
	BlendFactorOneMinusSrcColor      BlendFactor = 3
	BlendFactorDstColor              BlendFactor = 4
	BlendFactorOneMinusDstColor      BlendFactor = 5
	BlendFactorSrcAlpha              BlendFactor = 6
	BlendFactorOneMinusSrcAlpha      BlendFactor = 7
	BlendFactorDstAlpha              BlendFactor = 8
	BlendFactorOneMinusDstAlpha      BlendFactor = 9
	BlendFactorConstantColor         BlendFactor = 10
	BlendFactorOneMinusConstantColor BlendFactor = 11
	BlendFactorConstantAlpha         BlendFactor = 12
	BlendFactorOneMinusConstantAlpha BlendFactor = 13
	BlendFactorSrcAlphaSaturate      BlendFactor = 14
	BlendFactorSrc1Color             BlendFactor = 15
	BlendFactorOneMinusSrc1Color     BlendFactor = 16
	BlendFactorSrc1Alpha             BlendFactor = 17
	BlendFactorOneMinusSrc1Alpha     BlendFactor = 18
	BlendFactorBeginRange            BlendFactor = 0
	BlendFactorEndRange              BlendFactor = 18
	BlendFactorRangeSize             BlendFactor = 19
	BlendFactorMaxEnum               BlendFactor = 2147483647
)

// BlendOp as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBlendOp.html
type BlendOp int32

// BlendOp enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBlendOp.html
const (
	BlendOpAdd             BlendOp = iota
	BlendOpSubtract        BlendOp = 1
	BlendOpReverseSubtract BlendOp = 2
	BlendOpMin             BlendOp = 3
	BlendOpMax             BlendOp = 4
	BlendOpBeginRange      BlendOp = 0
	BlendOpEndRange        BlendOp = 4
	BlendOpRangeSize       BlendOp = 5
	BlendOpMaxEnum         BlendOp = 2147483647
)

// DynamicState as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDynamicState.html
type DynamicState int32

// DynamicState enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDynamicState.html
const (
	DynamicStateViewport           DynamicState = iota
	DynamicStateScissor            DynamicState = 1
	DynamicStateLineWidth          DynamicState = 2
	DynamicStateDepthBias          DynamicState = 3
	DynamicStateBlendConstants     DynamicState = 4
	DynamicStateDepthBounds        DynamicState = 5
	DynamicStateStencilCompareMask DynamicState = 6
	DynamicStateStencilWriteMask   DynamicState = 7
	DynamicStateStencilReference   DynamicState = 8
	DynamicStateBeginRange         DynamicState = 0
	DynamicStateEndRange           DynamicState = 8
	DynamicStateRangeSize          DynamicState = 9
	DynamicStateMaxEnum            DynamicState = 2147483647
)

// Filter as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFilter.html
type Filter int32

// Filter enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFilter.html
const (
	FilterNearest    Filter = iota
	FilterLinear     Filter = 1
	FilterCubicImg   Filter = 1000015000
	FilterBeginRange Filter = 0
	FilterEndRange   Filter = 1
	FilterRangeSize  Filter = 2
	FilterMaxEnum    Filter = 2147483647
)

// SamplerMipmapMode as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSamplerMipmapMode.html
type SamplerMipmapMode int32

// SamplerMipmapMode enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSamplerMipmapMode.html
const (
	SamplerMipmapModeNearest    SamplerMipmapMode = iota
	SamplerMipmapModeLinear     SamplerMipmapMode = 1
	SamplerMipmapModeBeginRange SamplerMipmapMode = 0
	SamplerMipmapModeEndRange   SamplerMipmapMode = 1
	SamplerMipmapModeRangeSize  SamplerMipmapMode = 2
	SamplerMipmapModeMaxEnum    SamplerMipmapMode = 2147483647
)

// SamplerAddressMode as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSamplerAddressMode.html
type SamplerAddressMode int32

// SamplerAddressMode enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSamplerAddressMode.html
const (
	SamplerAddressModeRepeat            SamplerAddressMode = iota
	SamplerAddressModeMirroredRepeat    SamplerAddressMode = 1
	SamplerAddressModeClampToEdge       SamplerAddressMode = 2
	SamplerAddressModeClampToBorder     SamplerAddressMode = 3
	SamplerAddressModeMirrorClampToEdge SamplerAddressMode = 4
	SamplerAddressModeBeginRange        SamplerAddressMode = 0
	SamplerAddressModeEndRange          SamplerAddressMode = 3
	SamplerAddressModeRangeSize         SamplerAddressMode = 4
	SamplerAddressModeMaxEnum           SamplerAddressMode = 2147483647
)

// BorderColor as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBorderColor.html
type BorderColor int32

// BorderColor enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBorderColor.html
const (
	BorderColorFloatTransparentBlack BorderColor = iota
	BorderColorIntTransparentBlack   BorderColor = 1
	BorderColorFloatOpaqueBlack      BorderColor = 2
	BorderColorIntOpaqueBlack        BorderColor = 3
	BorderColorFloatOpaqueWhite      BorderColor = 4
	BorderColorIntOpaqueWhite        BorderColor = 5
	BorderColorBeginRange            BorderColor = 0
	BorderColorEndRange              BorderColor = 5
	BorderColorRangeSize             BorderColor = 6
	BorderColorMaxEnum               BorderColor = 2147483647
)

// DescriptorType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDescriptorType.html
type DescriptorType int32

// DescriptorType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDescriptorType.html
const (
	DescriptorTypeSampler              DescriptorType = iota
	DescriptorTypeCombinedImageSampler DescriptorType = 1
	DescriptorTypeSampledImage         DescriptorType = 2
	DescriptorTypeStorageImage         DescriptorType = 3
	DescriptorTypeUniformTexelBuffer   DescriptorType = 4
	DescriptorTypeStorageTexelBuffer   DescriptorType = 5
	DescriptorTypeUniformBuffer        DescriptorType = 6
	DescriptorTypeStorageBuffer        DescriptorType = 7
	DescriptorTypeUniformBufferDynamic DescriptorType = 8
	DescriptorTypeStorageBufferDynamic DescriptorType = 9
	DescriptorTypeInputAttachment      DescriptorType = 10
	DescriptorTypeBeginRange           DescriptorType = 0
	DescriptorTypeEndRange             DescriptorType = 10
	DescriptorTypeRangeSize            DescriptorType = 11
	DescriptorTypeMaxEnum              DescriptorType = 2147483647
)

// AttachmentLoadOp as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentLoadOp.html
type AttachmentLoadOp int32

// AttachmentLoadOp enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentLoadOp.html
const (
	AttachmentLoadOpLoad       AttachmentLoadOp = iota
	AttachmentLoadOpClear      AttachmentLoadOp = 1
	AttachmentLoadOpDontCare   AttachmentLoadOp = 2
	AttachmentLoadOpBeginRange AttachmentLoadOp = 0
	AttachmentLoadOpEndRange   AttachmentLoadOp = 2
	AttachmentLoadOpRangeSize  AttachmentLoadOp = 3
	AttachmentLoadOpMaxEnum    AttachmentLoadOp = 2147483647
)

// AttachmentStoreOp as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentStoreOp.html
type AttachmentStoreOp int32

// AttachmentStoreOp enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentStoreOp.html
const (
	AttachmentStoreOpStore      AttachmentStoreOp = iota
	AttachmentStoreOpDontCare   AttachmentStoreOp = 1
	AttachmentStoreOpBeginRange AttachmentStoreOp = 0
	AttachmentStoreOpEndRange   AttachmentStoreOp = 1
	AttachmentStoreOpRangeSize  AttachmentStoreOp = 2
	AttachmentStoreOpMaxEnum    AttachmentStoreOp = 2147483647
)

// PipelineBindPoint as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineBindPoint.html
type PipelineBindPoint int32

// PipelineBindPoint enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineBindPoint.html
const (
	PipelineBindPointGraphics   PipelineBindPoint = iota
	PipelineBindPointCompute    PipelineBindPoint = 1
	PipelineBindPointBeginRange PipelineBindPoint = 0
	PipelineBindPointEndRange   PipelineBindPoint = 1
	PipelineBindPointRangeSize  PipelineBindPoint = 2
	PipelineBindPointMaxEnum    PipelineBindPoint = 2147483647
)

// CommandBufferLevel as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandBufferLevel.html
type CommandBufferLevel int32

// CommandBufferLevel enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandBufferLevel.html
const (
	CommandBufferLevelPrimary    CommandBufferLevel = iota
	CommandBufferLevelSecondary  CommandBufferLevel = 1
	CommandBufferLevelBeginRange CommandBufferLevel = 0
	CommandBufferLevelEndRange   CommandBufferLevel = 1
	CommandBufferLevelRangeSize  CommandBufferLevel = 2
	CommandBufferLevelMaxEnum    CommandBufferLevel = 2147483647
)

// IndexType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkIndexType.html
type IndexType int32

// IndexType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkIndexType.html
const (
	IndexTypeUint16     IndexType = iota
	IndexTypeUint32     IndexType = 1
	IndexTypeBeginRange IndexType = 0
	IndexTypeEndRange   IndexType = 1
	IndexTypeRangeSize  IndexType = 2
	IndexTypeMaxEnum    IndexType = 2147483647
)

// SubpassContents as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSubpassContents.html
type SubpassContents int32

// SubpassContents enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSubpassContents.html
const (
	SubpassContentsInline                  SubpassContents = iota
	SubpassContentsSecondaryCommandBuffers SubpassContents = 1
	SubpassContentsBeginRange              SubpassContents = 0
	SubpassContentsEndRange                SubpassContents = 1
	SubpassContentsRangeSize               SubpassContents = 2
	SubpassContentsMaxEnum                 SubpassContents = 2147483647
)

// FormatFeatureFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFormatFeatureFlagBits.html
type FormatFeatureFlagBits int32

// FormatFeatureFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFormatFeatureFlagBits.html
const (
	FormatFeatureSampledImageBit               FormatFeatureFlagBits = 1
	FormatFeatureStorageImageBit               FormatFeatureFlagBits = 2
	FormatFeatureStorageImageAtomicBit         FormatFeatureFlagBits = 4
	FormatFeatureUniformTexelBufferBit         FormatFeatureFlagBits = 8
	FormatFeatureStorageTexelBufferBit         FormatFeatureFlagBits = 16
	FormatFeatureStorageTexelBufferAtomicBit   FormatFeatureFlagBits = 32
	FormatFeatureVertexBufferBit               FormatFeatureFlagBits = 64
	FormatFeatureColorAttachmentBit            FormatFeatureFlagBits = 128
	FormatFeatureColorAttachmentBlendBit       FormatFeatureFlagBits = 256
	FormatFeatureDepthStencilAttachmentBit     FormatFeatureFlagBits = 512
	FormatFeatureBlitSrcBit                    FormatFeatureFlagBits = 1024
	FormatFeatureBlitDstBit                    FormatFeatureFlagBits = 2048
	FormatFeatureSampledImageFilterLinearBit   FormatFeatureFlagBits = 4096
	FormatFeatureSampledImageFilterCubicBitImg FormatFeatureFlagBits = 8192
	FormatFeatureFlagBitsMaxEnum               FormatFeatureFlagBits = 2147483647
)

// ImageUsageFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageUsageFlagBits.html
type ImageUsageFlagBits int32

// ImageUsageFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageUsageFlagBits.html
const (
	ImageUsageTransferSrcBit            ImageUsageFlagBits = 1
	ImageUsageTransferDstBit            ImageUsageFlagBits = 2
	ImageUsageSampledBit                ImageUsageFlagBits = 4
	ImageUsageStorageBit                ImageUsageFlagBits = 8
	ImageUsageColorAttachmentBit        ImageUsageFlagBits = 16
	ImageUsageDepthStencilAttachmentBit ImageUsageFlagBits = 32
	ImageUsageTransientAttachmentBit    ImageUsageFlagBits = 64
	ImageUsageInputAttachmentBit        ImageUsageFlagBits = 128
	ImageUsageFlagBitsMaxEnum           ImageUsageFlagBits = 2147483647
)

// ImageCreateFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageCreateFlagBits.html
type ImageCreateFlagBits int32

// ImageCreateFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageCreateFlagBits.html
const (
	ImageCreateSparseBindingBit   ImageCreateFlagBits = 1
	ImageCreateSparseResidencyBit ImageCreateFlagBits = 2
	ImageCreateSparseAliasedBit   ImageCreateFlagBits = 4
	ImageCreateMutableFormatBit   ImageCreateFlagBits = 8
	ImageCreateCubeCompatibleBit  ImageCreateFlagBits = 16
	ImageCreateFlagBitsMaxEnum    ImageCreateFlagBits = 2147483647
)

// SampleCountFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSampleCountFlagBits.html
type SampleCountFlagBits int32

// SampleCountFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSampleCountFlagBits.html
const (
	SampleCount1Bit            SampleCountFlagBits = 1
	SampleCount2Bit            SampleCountFlagBits = 2
	SampleCount4Bit            SampleCountFlagBits = 4
	SampleCount8Bit            SampleCountFlagBits = 8
	SampleCount16Bit           SampleCountFlagBits = 16
	SampleCount32Bit           SampleCountFlagBits = 32
	SampleCount64Bit           SampleCountFlagBits = 64
	SampleCountFlagBitsMaxEnum SampleCountFlagBits = 2147483647
)

// QueueFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueueFlagBits.html
type QueueFlagBits int32

// QueueFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueueFlagBits.html
const (
	QueueGraphicsBit      QueueFlagBits = 1
	QueueComputeBit       QueueFlagBits = 2
	QueueTransferBit      QueueFlagBits = 4
	QueueSparseBindingBit QueueFlagBits = 8
	QueueFlagBitsMaxEnum  QueueFlagBits = 2147483647
)

// MemoryPropertyFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkMemoryPropertyFlagBits.html
type MemoryPropertyFlagBits int32

// MemoryPropertyFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkMemoryPropertyFlagBits.html
const (
	MemoryPropertyDeviceLocalBit     MemoryPropertyFlagBits = 1
	MemoryPropertyHostVisibleBit     MemoryPropertyFlagBits = 2
	MemoryPropertyHostCoherentBit    MemoryPropertyFlagBits = 4
	MemoryPropertyHostCachedBit      MemoryPropertyFlagBits = 8
	MemoryPropertyLazilyAllocatedBit MemoryPropertyFlagBits = 16
	MemoryPropertyFlagBitsMaxEnum    MemoryPropertyFlagBits = 2147483647
)

// MemoryHeapFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkMemoryHeapFlagBits.html
type MemoryHeapFlagBits int32

// MemoryHeapFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkMemoryHeapFlagBits.html
const (
	MemoryHeapDeviceLocalBit  MemoryHeapFlagBits = 1
	MemoryHeapFlagBitsMaxEnum MemoryHeapFlagBits = 2147483647
)

// PipelineStageFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineStageFlagBits.html
type PipelineStageFlagBits int32

// PipelineStageFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineStageFlagBits.html
const (
	PipelineStageTopOfPipeBit                    PipelineStageFlagBits = 1
	PipelineStageDrawIndirectBit                 PipelineStageFlagBits = 2
	PipelineStageVertexInputBit                  PipelineStageFlagBits = 4
	PipelineStageVertexShaderBit                 PipelineStageFlagBits = 8
	PipelineStageTessellationControlShaderBit    PipelineStageFlagBits = 16
	PipelineStageTessellationEvaluationShaderBit PipelineStageFlagBits = 32
	PipelineStageGeometryShaderBit               PipelineStageFlagBits = 64
	PipelineStageFragmentShaderBit               PipelineStageFlagBits = 128
	PipelineStageEarlyFragmentTestsBit           PipelineStageFlagBits = 256
	PipelineStageLateFragmentTestsBit            PipelineStageFlagBits = 512
	PipelineStageColorAttachmentOutputBit        PipelineStageFlagBits = 1024
	PipelineStageComputeShaderBit                PipelineStageFlagBits = 2048
	PipelineStageTransferBit                     PipelineStageFlagBits = 4096
	PipelineStageBottomOfPipeBit                 PipelineStageFlagBits = 8192
	PipelineStageHostBit                         PipelineStageFlagBits = 16384
	PipelineStageAllGraphicsBit                  PipelineStageFlagBits = 32768
	PipelineStageAllCommandsBit                  PipelineStageFlagBits = 65536
	PipelineStageFlagBitsMaxEnum                 PipelineStageFlagBits = 2147483647
)

// ImageAspectFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageAspectFlagBits.html
type ImageAspectFlagBits int32

// ImageAspectFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkImageAspectFlagBits.html
const (
	ImageAspectColorBit        ImageAspectFlagBits = 1
	ImageAspectDepthBit        ImageAspectFlagBits = 2
	ImageAspectStencilBit      ImageAspectFlagBits = 4
	ImageAspectMetadataBit     ImageAspectFlagBits = 8
	ImageAspectFlagBitsMaxEnum ImageAspectFlagBits = 2147483647
)

// SparseImageFormatFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSparseImageFormatFlagBits.html
type SparseImageFormatFlagBits int32

// SparseImageFormatFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSparseImageFormatFlagBits.html
const (
	SparseImageFormatSingleMiptailBit        SparseImageFormatFlagBits = 1
	SparseImageFormatAlignedMipSizeBit       SparseImageFormatFlagBits = 2
	SparseImageFormatNonstandardBlockSizeBit SparseImageFormatFlagBits = 4
	SparseImageFormatFlagBitsMaxEnum         SparseImageFormatFlagBits = 2147483647
)

// SparseMemoryBindFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSparseMemoryBindFlagBits.html
type SparseMemoryBindFlagBits int32

// SparseMemoryBindFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkSparseMemoryBindFlagBits.html
const (
	SparseMemoryBindMetadataBit     SparseMemoryBindFlagBits = 1
	SparseMemoryBindFlagBitsMaxEnum SparseMemoryBindFlagBits = 2147483647
)

// FenceCreateFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFenceCreateFlagBits.html
type FenceCreateFlagBits int32

// FenceCreateFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkFenceCreateFlagBits.html
const (
	FenceCreateSignaledBit     FenceCreateFlagBits = 1
	FenceCreateFlagBitsMaxEnum FenceCreateFlagBits = 2147483647
)

// QueryPipelineStatisticFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryPipelineStatisticFlagBits.html
type QueryPipelineStatisticFlagBits int32

// QueryPipelineStatisticFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryPipelineStatisticFlagBits.html
const (
	QueryPipelineStatisticInputAssemblyVerticesBit                   QueryPipelineStatisticFlagBits = 1
	QueryPipelineStatisticInputAssemblyPrimitivesBit                 QueryPipelineStatisticFlagBits = 2
	QueryPipelineStatisticVertexShaderInvocationsBit                 QueryPipelineStatisticFlagBits = 4
	QueryPipelineStatisticGeometryShaderInvocationsBit               QueryPipelineStatisticFlagBits = 8
	QueryPipelineStatisticGeometryShaderPrimitivesBit                QueryPipelineStatisticFlagBits = 16
	QueryPipelineStatisticClippingInvocationsBit                     QueryPipelineStatisticFlagBits = 32
	QueryPipelineStatisticClippingPrimitivesBit                      QueryPipelineStatisticFlagBits = 64
	QueryPipelineStatisticFragmentShaderInvocationsBit               QueryPipelineStatisticFlagBits = 128
	QueryPipelineStatisticTessellationControlShaderPatchesBit        QueryPipelineStatisticFlagBits = 256
	QueryPipelineStatisticTessellationEvaluationShaderInvocationsBit QueryPipelineStatisticFlagBits = 512
	QueryPipelineStatisticComputeShaderInvocationsBit                QueryPipelineStatisticFlagBits = 1024
	QueryPipelineStatisticFlagBitsMaxEnum                            QueryPipelineStatisticFlagBits = 2147483647
)

// QueryResultFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryResultFlagBits.html
type QueryResultFlagBits int32

// QueryResultFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryResultFlagBits.html
const (
	QueryResult64Bit               QueryResultFlagBits = 1
	QueryResultWaitBit             QueryResultFlagBits = 2
	QueryResultWithAvailabilityBit QueryResultFlagBits = 4
	QueryResultPartialBit          QueryResultFlagBits = 8
	QueryResultFlagBitsMaxEnum     QueryResultFlagBits = 2147483647
)

// BufferCreateFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBufferCreateFlagBits.html
type BufferCreateFlagBits int32

// BufferCreateFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBufferCreateFlagBits.html
const (
	BufferCreateSparseBindingBit   BufferCreateFlagBits = 1
	BufferCreateSparseResidencyBit BufferCreateFlagBits = 2
	BufferCreateSparseAliasedBit   BufferCreateFlagBits = 4
	BufferCreateFlagBitsMaxEnum    BufferCreateFlagBits = 2147483647
)

// BufferUsageFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBufferUsageFlagBits.html
type BufferUsageFlagBits int32

// BufferUsageFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkBufferUsageFlagBits.html
const (
	BufferUsageTransferSrcBit        BufferUsageFlagBits = 1
	BufferUsageTransferDstBit        BufferUsageFlagBits = 2
	BufferUsageUniformTexelBufferBit BufferUsageFlagBits = 4
	BufferUsageStorageTexelBufferBit BufferUsageFlagBits = 8
	BufferUsageUniformBufferBit      BufferUsageFlagBits = 16
	BufferUsageStorageBufferBit      BufferUsageFlagBits = 32
	BufferUsageIndexBufferBit        BufferUsageFlagBits = 64
	BufferUsageVertexBufferBit       BufferUsageFlagBits = 128
	BufferUsageIndirectBufferBit     BufferUsageFlagBits = 256
	BufferUsageFlagBitsMaxEnum       BufferUsageFlagBits = 2147483647
)

// PipelineCreateFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineCreateFlagBits.html
type PipelineCreateFlagBits int32

// PipelineCreateFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkPipelineCreateFlagBits.html
const (
	PipelineCreateDisableOptimizationBit PipelineCreateFlagBits = 1
	PipelineCreateAllowDerivativesBit    PipelineCreateFlagBits = 2
	PipelineCreateDerivativeBit          PipelineCreateFlagBits = 4
	PipelineCreateFlagBitsMaxEnum        PipelineCreateFlagBits = 2147483647
)

// ShaderStageFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkShaderStageFlagBits.html
type ShaderStageFlagBits int32

// ShaderStageFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkShaderStageFlagBits.html
const (
	ShaderStageVertexBit                 ShaderStageFlagBits = 1
	ShaderStageTessellationControlBit    ShaderStageFlagBits = 2
	ShaderStageTessellationEvaluationBit ShaderStageFlagBits = 4
	ShaderStageGeometryBit               ShaderStageFlagBits = 8
	ShaderStageFragmentBit               ShaderStageFlagBits = 16
	ShaderStageComputeBit                ShaderStageFlagBits = 32
	ShaderStageAllGraphics               ShaderStageFlagBits = 31
	ShaderStageAll                       ShaderStageFlagBits = 2147483647
	ShaderStageFlagBitsMaxEnum           ShaderStageFlagBits = 2147483647
)

// CullModeFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCullModeFlagBits.html
type CullModeFlagBits int32

// CullModeFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCullModeFlagBits.html
const (
	CullModeNone            CullModeFlagBits = iota
	CullModeFrontBit        CullModeFlagBits = 1
	CullModeBackBit         CullModeFlagBits = 2
	CullModeFrontAndBack    CullModeFlagBits = 3
	CullModeFlagBitsMaxEnum CullModeFlagBits = 2147483647
)

// ColorComponentFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkColorComponentFlagBits.html
type ColorComponentFlagBits int32

// ColorComponentFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkColorComponentFlagBits.html
const (
	ColorComponentRBit            ColorComponentFlagBits = 1
	ColorComponentGBit            ColorComponentFlagBits = 2
	ColorComponentBBit            ColorComponentFlagBits = 4
	ColorComponentABit            ColorComponentFlagBits = 8
	ColorComponentFlagBitsMaxEnum ColorComponentFlagBits = 2147483647
)

// DescriptorPoolCreateFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDescriptorPoolCreateFlagBits.html
type DescriptorPoolCreateFlagBits int32

// DescriptorPoolCreateFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDescriptorPoolCreateFlagBits.html
const (
	DescriptorPoolCreateFreeDescriptorSetBit DescriptorPoolCreateFlagBits = 1
	DescriptorPoolCreateFlagBitsMaxEnum      DescriptorPoolCreateFlagBits = 2147483647
)

// AttachmentDescriptionFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentDescriptionFlagBits.html
type AttachmentDescriptionFlagBits int32

// AttachmentDescriptionFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAttachmentDescriptionFlagBits.html
const (
	AttachmentDescriptionMayAliasBit     AttachmentDescriptionFlagBits = 1
	AttachmentDescriptionFlagBitsMaxEnum AttachmentDescriptionFlagBits = 2147483647
)

// AccessFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAccessFlagBits.html
type AccessFlagBits int32

// AccessFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkAccessFlagBits.html
const (
	AccessIndirectCommandReadBit         AccessFlagBits = 1
	AccessIndexReadBit                   AccessFlagBits = 2
	AccessVertexAttributeReadBit         AccessFlagBits = 4
	AccessUniformReadBit                 AccessFlagBits = 8
	AccessInputAttachmentReadBit         AccessFlagBits = 16
	AccessShaderReadBit                  AccessFlagBits = 32
	AccessShaderWriteBit                 AccessFlagBits = 64
	AccessColorAttachmentReadBit         AccessFlagBits = 128
	AccessColorAttachmentWriteBit        AccessFlagBits = 256
	AccessDepthStencilAttachmentReadBit  AccessFlagBits = 512
	AccessDepthStencilAttachmentWriteBit AccessFlagBits = 1024
	AccessTransferReadBit                AccessFlagBits = 2048
	AccessTransferWriteBit               AccessFlagBits = 4096
	AccessHostReadBit                    AccessFlagBits = 8192
	AccessHostWriteBit                   AccessFlagBits = 16384
	AccessMemoryReadBit                  AccessFlagBits = 32768
	AccessMemoryWriteBit                 AccessFlagBits = 65536
	AccessFlagBitsMaxEnum                AccessFlagBits = 2147483647
)

// DependencyFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDependencyFlagBits.html
type DependencyFlagBits int32

// DependencyFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDependencyFlagBits.html
const (
	DependencyByRegionBit     DependencyFlagBits = 1
	DependencyFlagBitsMaxEnum DependencyFlagBits = 2147483647
)

// CommandPoolCreateFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandPoolCreateFlagBits.html
type CommandPoolCreateFlagBits int32

// CommandPoolCreateFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandPoolCreateFlagBits.html
const (
	CommandPoolCreateTransientBit          CommandPoolCreateFlagBits = 1
	CommandPoolCreateResetCommandBufferBit CommandPoolCreateFlagBits = 2
	CommandPoolCreateFlagBitsMaxEnum       CommandPoolCreateFlagBits = 2147483647
)

// CommandPoolResetFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandPoolResetFlagBits.html
type CommandPoolResetFlagBits int32

// CommandPoolResetFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandPoolResetFlagBits.html
const (
	CommandPoolResetReleaseResourcesBit CommandPoolResetFlagBits = 1
	CommandPoolResetFlagBitsMaxEnum     CommandPoolResetFlagBits = 2147483647
)

// CommandBufferUsageFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandBufferUsageFlagBits.html
type CommandBufferUsageFlagBits int32

// CommandBufferUsageFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandBufferUsageFlagBits.html
const (
	CommandBufferUsageOneTimeSubmitBit      CommandBufferUsageFlagBits = 1
	CommandBufferUsageRenderPassContinueBit CommandBufferUsageFlagBits = 2
	CommandBufferUsageSimultaneousUseBit    CommandBufferUsageFlagBits = 4
	CommandBufferUsageFlagBitsMaxEnum       CommandBufferUsageFlagBits = 2147483647
)

// QueryControlFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryControlFlagBits.html
type QueryControlFlagBits int32

// QueryControlFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkQueryControlFlagBits.html
const (
	QueryControlPreciseBit      QueryControlFlagBits = 1
	QueryControlFlagBitsMaxEnum QueryControlFlagBits = 2147483647
)

// CommandBufferResetFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandBufferResetFlagBits.html
type CommandBufferResetFlagBits int32

// CommandBufferResetFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkCommandBufferResetFlagBits.html
const (
	CommandBufferResetReleaseResourcesBit CommandBufferResetFlagBits = 1
	CommandBufferResetFlagBitsMaxEnum     CommandBufferResetFlagBits = 2147483647
)

// StencilFaceFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkStencilFaceFlagBits.html
type StencilFaceFlagBits int32

// StencilFaceFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkStencilFaceFlagBits.html
const (
	StencilFaceFrontBit        StencilFaceFlagBits = 1
	StencilFaceBackBit         StencilFaceFlagBits = 2
	StencilFrontAndBack        StencilFaceFlagBits = 3
	StencilFaceFlagBitsMaxEnum StencilFaceFlagBits = 2147483647
)

// ColorSpace as declared in https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkColorSpaceKHR
type ColorSpace int32

// ColorSpace enumeration from https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkColorSpaceKHR
const (
	ColorSpaceSrgbNonlinear ColorSpace = iota
	ColorSpaceBeginRange    ColorSpace = 0
	ColorSpaceEndRange      ColorSpace = 0
	ColorSpaceRangeSize     ColorSpace = 1
	ColorSpaceMaxEnum       ColorSpace = 2147483647
)

// PresentMode as declared in https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkPresentModeKHR
type PresentMode int32

// PresentMode enumeration from https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkPresentModeKHR
const (
	PresentModeImmediate   PresentMode = iota
	PresentModeMailbox     PresentMode = 1
	PresentModeFifo        PresentMode = 2
	PresentModeFifoRelaxed PresentMode = 3
	PresentModeBeginRange  PresentMode = 0
	PresentModeEndRange    PresentMode = 3
	PresentModeRangeSize   PresentMode = 4
	PresentModeMaxEnum     PresentMode = 2147483647
)

// SurfaceTransformFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkSurfaceTransformFlagBitsKHR
type SurfaceTransformFlagBits int32

// SurfaceTransformFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkSurfaceTransformFlagBitsKHR
const (
	SurfaceTransformIdentityBit                  SurfaceTransformFlagBits = 1
	SurfaceTransformRotate90Bit                  SurfaceTransformFlagBits = 2
	SurfaceTransformRotate180Bit                 SurfaceTransformFlagBits = 4
	SurfaceTransformRotate270Bit                 SurfaceTransformFlagBits = 8
	SurfaceTransformHorizontalMirrorBit          SurfaceTransformFlagBits = 16
	SurfaceTransformHorizontalMirrorRotate90Bit  SurfaceTransformFlagBits = 32
	SurfaceTransformHorizontalMirrorRotate180Bit SurfaceTransformFlagBits = 64
	SurfaceTransformHorizontalMirrorRotate270Bit SurfaceTransformFlagBits = 128
	SurfaceTransformInheritBit                   SurfaceTransformFlagBits = 256
	SurfaceTransformFlagBitsMaxEnum              SurfaceTransformFlagBits = 2147483647
)

// CompositeAlphaFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkCompositeAlphaFlagBitsKHR
type CompositeAlphaFlagBits int32

// CompositeAlphaFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkCompositeAlphaFlagBitsKHR
const (
	CompositeAlphaOpaqueBit         CompositeAlphaFlagBits = 1
	CompositeAlphaPreMultipliedBit  CompositeAlphaFlagBits = 2
	CompositeAlphaPostMultipliedBit CompositeAlphaFlagBits = 4
	CompositeAlphaInheritBit        CompositeAlphaFlagBits = 8
	CompositeAlphaFlagBitsMaxEnum   CompositeAlphaFlagBits = 2147483647
)

// DisplayPlaneAlphaFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkDisplayPlaneAlphaFlagBitsKHR
type DisplayPlaneAlphaFlagBits int32

// DisplayPlaneAlphaFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0-wsi_extensions/xhtml/vkspec.html#vkDisplayPlaneAlphaFlagBitsKHR
const (
	DisplayPlaneAlphaOpaqueBit                DisplayPlaneAlphaFlagBits = 1
	DisplayPlaneAlphaGlobalBit                DisplayPlaneAlphaFlagBits = 2
	DisplayPlaneAlphaPerPixelBit              DisplayPlaneAlphaFlagBits = 4
	DisplayPlaneAlphaPerPixelPremultipliedBit DisplayPlaneAlphaFlagBits = 8
	DisplayPlaneAlphaFlagBitsMaxEnum          DisplayPlaneAlphaFlagBits = 2147483647
)

// DebugReportObjectType as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDebugReportObjectTypeEXT.html
type DebugReportObjectType int32

// DebugReportObjectType enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDebugReportObjectTypeEXT.html
const (
	DebugReportObjectTypeUnknown             DebugReportObjectType = iota
	DebugReportObjectTypeInstance            DebugReportObjectType = 1
	DebugReportObjectTypePhysicalDevice      DebugReportObjectType = 2
	DebugReportObjectTypeDevice              DebugReportObjectType = 3
	DebugReportObjectTypeQueue               DebugReportObjectType = 4
	DebugReportObjectTypeSemaphore           DebugReportObjectType = 5
	DebugReportObjectTypeCommandBuffer       DebugReportObjectType = 6
	DebugReportObjectTypeFence               DebugReportObjectType = 7
	DebugReportObjectTypeDeviceMemory        DebugReportObjectType = 8
	DebugReportObjectTypeBuffer              DebugReportObjectType = 9
	DebugReportObjectTypeImage               DebugReportObjectType = 10
	DebugReportObjectTypeEvent               DebugReportObjectType = 11
	DebugReportObjectTypeQueryPool           DebugReportObjectType = 12
	DebugReportObjectTypeBufferView          DebugReportObjectType = 13
	DebugReportObjectTypeImageView           DebugReportObjectType = 14
	DebugReportObjectTypeShaderModule        DebugReportObjectType = 15
	DebugReportObjectTypePipelineCache       DebugReportObjectType = 16
	DebugReportObjectTypePipelineLayout      DebugReportObjectType = 17
	DebugReportObjectTypeRenderPass          DebugReportObjectType = 18
	DebugReportObjectTypePipeline            DebugReportObjectType = 19
	DebugReportObjectTypeDescriptorSetLayout DebugReportObjectType = 20
	DebugReportObjectTypeSampler             DebugReportObjectType = 21
	DebugReportObjectTypeDescriptorPool      DebugReportObjectType = 22
	DebugReportObjectTypeDescriptorSet       DebugReportObjectType = 23
	DebugReportObjectTypeFramebuffer         DebugReportObjectType = 24
	DebugReportObjectTypeCommandPool         DebugReportObjectType = 25
	DebugReportObjectTypeSurfaceKhr          DebugReportObjectType = 26
	DebugReportObjectTypeSwapchainKhr        DebugReportObjectType = 27
	DebugReportObjectTypeDebugReport         DebugReportObjectType = 28
	DebugReportObjectTypeBeginRange          DebugReportObjectType = 0
	DebugReportObjectTypeEndRange            DebugReportObjectType = 28
	DebugReportObjectTypeRangeSize           DebugReportObjectType = 29
	DebugReportObjectTypeMaxEnum             DebugReportObjectType = 2147483647
)

// DebugReportError as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDebugReportErrorEXT.html
type DebugReportError int32

// DebugReportError enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDebugReportErrorEXT.html
const (
	DebugReportErrorNone        DebugReportError = iota
	DebugReportErrorCallbackRef DebugReportError = 1
	DebugReportErrorBeginRange  DebugReportError = 0
	DebugReportErrorEndRange    DebugReportError = 1
	DebugReportErrorRangeSize   DebugReportError = 2
	DebugReportErrorMaxEnum     DebugReportError = 2147483647
)

// DebugReportFlagBits as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDebugReportFlagBitsEXT.html
type DebugReportFlagBits int32

// DebugReportFlagBits enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkDebugReportFlagBitsEXT.html
const (
	DebugReportInformationBit        DebugReportFlagBits = 1
	DebugReportWarningBit            DebugReportFlagBits = 2
	DebugReportPerformanceWarningBit DebugReportFlagBits = 4
	DebugReportErrorBit              DebugReportFlagBits = 8
	DebugReportDebugBit              DebugReportFlagBits = 16
	DebugReportFlagBitsMaxEnum       DebugReportFlagBits = 2147483647
)

// RasterizationOrderAMD as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkRasterizationOrderAMD.html
type RasterizationOrderAMD int32

// RasterizationOrderAMD enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkRasterizationOrderAMD.html
const (
	RasterizationOrderStrictAmd     RasterizationOrderAMD = iota
	RasterizationOrderRelaxedAmd    RasterizationOrderAMD = 1
	RasterizationOrderBeginRangeAmd RasterizationOrderAMD = 0
	RasterizationOrderEndRangeAmd   RasterizationOrderAMD = 1
	RasterizationOrderRangeSizeAmd  RasterizationOrderAMD = 2
	RasterizationOrderMaxEnumAmd    RasterizationOrderAMD = 2147483647
)

// ExternalMemoryHandleTypeFlagBitsNV as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkExternalMemoryHandleTypeFlagBitsNV.html
type ExternalMemoryHandleTypeFlagBitsNV int32

// ExternalMemoryHandleTypeFlagBitsNV enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkExternalMemoryHandleTypeFlagBitsNV.html
const (
	ExternalMemoryHandleTypeOpaqueWin32BitNv    ExternalMemoryHandleTypeFlagBitsNV = 1
	ExternalMemoryHandleTypeOpaqueWin32KmtBitNv ExternalMemoryHandleTypeFlagBitsNV = 2
	ExternalMemoryHandleTypeD3d11ImageBitNv     ExternalMemoryHandleTypeFlagBitsNV = 4
	ExternalMemoryHandleTypeD3d11ImageKmtBitNv  ExternalMemoryHandleTypeFlagBitsNV = 8
	ExternalMemoryHandleTypeFlagBitsMaxEnumNv   ExternalMemoryHandleTypeFlagBitsNV = 2147483647
)

// ExternalMemoryFeatureFlagBitsNV as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkExternalMemoryFeatureFlagBitsNV.html
type ExternalMemoryFeatureFlagBitsNV int32

// ExternalMemoryFeatureFlagBitsNV enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkExternalMemoryFeatureFlagBitsNV.html
const (
	ExternalMemoryFeatureDedicatedOnlyBitNv ExternalMemoryFeatureFlagBitsNV = 1
	ExternalMemoryFeatureExportableBitNv    ExternalMemoryFeatureFlagBitsNV = 2
	ExternalMemoryFeatureImportableBitNv    ExternalMemoryFeatureFlagBitsNV = 4
	ExternalMemoryFeatureFlagBitsMaxEnumNv  ExternalMemoryFeatureFlagBitsNV = 2147483647
)

// ValidationCheck as declared in https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkValidationCheckEXT.html
type ValidationCheck int32

// ValidationCheck enumeration from https://www.khronos.org/registry/vulkan/specs/1.0/man/html/VkValidationCheckEXT.html
const (
	ValidationCheckAll        ValidationCheck = iota
	ValidationCheckBeginRange ValidationCheck = 0
	ValidationCheckEndRange   ValidationCheck = 0
	ValidationCheckRangeSize  ValidationCheck = 1
	ValidationCheckMaxEnum    ValidationCheck = 2147483647
)
