// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 31 May 2017 00:23:17 MSK.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package vulkan provides Go bindings for vulkan.h
*/
package vulkan
