all:
	c-for-go -ccdefs -out .. vulkan.yml

clean:
	rm -f doc.go types.go const.go
	rm -f cgo_helpers.go cgo_helpers.c cgo_helpers.h
	rm -f vulkan.go

test:
	go build
	
# NOTE: MUST update version number here prior to running 'make release'
VERS=v1.0.5
PACKAGE=vulkan
GIT_COMMIT=`git rev-parse --short HEAD`
VERS_DATE=`date -u +%Y-%m-%d\ %H:%M`
VERS_FILE=version.go

release:
	/bin/rm -f $(VERS_FILE)
	@echo "// WARNING: auto-generated by Makefile release target -- run 'make release' to update" > $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	@echo "package $(PACKAGE)" >> $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	@echo "const (" >> $(VERS_FILE)
	@echo "	GoVersion     = \"$(VERS)\"" >> $(VERS_FILE)
	@echo "	GitCommit   = \"$(GIT_COMMIT)\" // the commit JUST BEFORE the release" >> $(VERS_FILE)
	@echo "	VersionDate = \"$(VERS_DATE)\" // UTC" >> $(VERS_FILE)
	@echo ")" >> $(VERS_FILE)
	@echo "" >> $(VERS_FILE)
	goimports -w $(VERS_FILE)
	/bin/cat $(VERS_FILE)
	git commit -am "$(VERS) release -- $(VERS_FILE) updated"
	git tag -a $(VERS) -m "$(VERS) release"
	git push
	git push origin --tags

