// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 03 Mar 2016 02:03:17 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package vulkan

/*
#include "vulkan.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// CommandBuffer as declared in vulkan/vulkan.h:54
type CommandBuffer C.VkCommandBuffer

// Device as declared in vulkan/vulkan.h:54
type Device C.VkDevice

// Instance as declared in vulkan/vulkan.h:54
type Instance C.VkInstance

// PhysicalDevice as declared in vulkan/vulkan.h:54
type PhysicalDevice C.VkPhysicalDevice

// Queue as declared in vulkan/vulkan.h:54
type Queue C.VkQueue

// Buffer as declared in vulkan/vulkan.h:58
type Buffer C.VkBuffer

// BufferView as declared in vulkan/vulkan.h:58
type BufferView C.VkBufferView

// CommandPool as declared in vulkan/vulkan.h:58
type CommandPool C.VkCommandPool

// DebugReportCallbackEXT as declared in vulkan/vulkan.h:58
type DebugReportCallbackEXT C.VkDebugReportCallbackEXT

// DescriptorPool as declared in vulkan/vulkan.h:58
type DescriptorPool C.VkDescriptorPool

// DescriptorSet as declared in vulkan/vulkan.h:58
type DescriptorSet C.VkDescriptorSet

// DescriptorSetLayout as declared in vulkan/vulkan.h:58
type DescriptorSetLayout C.VkDescriptorSetLayout

// DeviceMemory as declared in vulkan/vulkan.h:58
type DeviceMemory C.VkDeviceMemory

// DisplayKHR as declared in vulkan/vulkan.h:58
type DisplayKHR C.VkDisplayKHR

// DisplayModeKHR as declared in vulkan/vulkan.h:58
type DisplayModeKHR C.VkDisplayModeKHR

// Event as declared in vulkan/vulkan.h:58
type Event C.VkEvent

// Fence as declared in vulkan/vulkan.h:58
type Fence C.VkFence

// Framebuffer as declared in vulkan/vulkan.h:58
type Framebuffer C.VkFramebuffer

// Image as declared in vulkan/vulkan.h:58
type Image C.VkImage

// ImageView as declared in vulkan/vulkan.h:58
type ImageView C.VkImageView

// Pipeline as declared in vulkan/vulkan.h:58
type Pipeline C.VkPipeline

// PipelineCache as declared in vulkan/vulkan.h:58
type PipelineCache C.VkPipelineCache

// PipelineLayout as declared in vulkan/vulkan.h:58
type PipelineLayout C.VkPipelineLayout

// QueryPool as declared in vulkan/vulkan.h:58
type QueryPool C.VkQueryPool

// RenderPass as declared in vulkan/vulkan.h:58
type RenderPass C.VkRenderPass

// Sampler as declared in vulkan/vulkan.h:58
type Sampler C.VkSampler

// Semaphore as declared in vulkan/vulkan.h:58
type Semaphore C.VkSemaphore

// ShaderModule as declared in vulkan/vulkan.h:58
type ShaderModule C.VkShaderModule

// SurfaceKHR as declared in vulkan/vulkan.h:58
type SurfaceKHR C.VkSurfaceKHR

// SwapchainKHR as declared in vulkan/vulkan.h:58
type SwapchainKHR C.VkSwapchainKHR

// Flags type as declared in vulkan/vulkan.h:65
type Flags uint32

// Bool32 type as declared in vulkan/vulkan.h:66
type Bool32 uint32

// DeviceSize type as declared in vulkan/vulkan.h:67
type DeviceSize uint64

// SampleMask type as declared in vulkan/vulkan.h:68
type SampleMask uint32

// InstanceCreateFlags type as declared in vulkan/vulkan.h:795
type InstanceCreateFlags uint32

// FormatFeatureFlags type as declared in vulkan/vulkan.h:812
type FormatFeatureFlags uint32

// ImageUsageFlags type as declared in vulkan/vulkan.h:824
type ImageUsageFlags uint32

// ImageCreateFlags type as declared in vulkan/vulkan.h:833
type ImageCreateFlags uint32

// SampleCountFlags type as declared in vulkan/vulkan.h:844
type SampleCountFlags uint32

// QueueFlags type as declared in vulkan/vulkan.h:852
type QueueFlags uint32

// MemoryPropertyFlags type as declared in vulkan/vulkan.h:861
type MemoryPropertyFlags uint32

// MemoryHeapFlags type as declared in vulkan/vulkan.h:866
type MemoryHeapFlags uint32

// DeviceCreateFlags type as declared in vulkan/vulkan.h:867
type DeviceCreateFlags uint32

// DeviceQueueCreateFlags type as declared in vulkan/vulkan.h:868
type DeviceQueueCreateFlags uint32

// PipelineStageFlags type as declared in vulkan/vulkan.h:889
type PipelineStageFlags uint32

// MemoryMapFlags type as declared in vulkan/vulkan.h:890
type MemoryMapFlags uint32

// ImageAspectFlags type as declared in vulkan/vulkan.h:898
type ImageAspectFlags uint32

// SparseImageFormatFlags type as declared in vulkan/vulkan.h:905
type SparseImageFormatFlags uint32

// SparseMemoryBindFlags type as declared in vulkan/vulkan.h:910
type SparseMemoryBindFlags uint32

// FenceCreateFlags type as declared in vulkan/vulkan.h:915
type FenceCreateFlags uint32

// SemaphoreCreateFlags type as declared in vulkan/vulkan.h:916
type SemaphoreCreateFlags uint32

// EventCreateFlags type as declared in vulkan/vulkan.h:917
type EventCreateFlags uint32

// QueryPoolCreateFlags type as declared in vulkan/vulkan.h:918
type QueryPoolCreateFlags uint32

// QueryPipelineStatisticFlags type as declared in vulkan/vulkan.h:933
type QueryPipelineStatisticFlags uint32

// QueryResultFlags type as declared in vulkan/vulkan.h:941
type QueryResultFlags uint32

// BufferCreateFlags type as declared in vulkan/vulkan.h:948
type BufferCreateFlags uint32

// BufferUsageFlags type as declared in vulkan/vulkan.h:961
type BufferUsageFlags uint32

// BufferViewCreateFlags type as declared in vulkan/vulkan.h:962
type BufferViewCreateFlags uint32

// ImageViewCreateFlags type as declared in vulkan/vulkan.h:963
type ImageViewCreateFlags uint32

// ShaderModuleCreateFlags type as declared in vulkan/vulkan.h:964
type ShaderModuleCreateFlags uint32

// PipelineCacheCreateFlags type as declared in vulkan/vulkan.h:965
type PipelineCacheCreateFlags uint32

// PipelineCreateFlags type as declared in vulkan/vulkan.h:972
type PipelineCreateFlags uint32

// PipelineShaderStageCreateFlags type as declared in vulkan/vulkan.h:973
type PipelineShaderStageCreateFlags uint32

// PipelineVertexInputStateCreateFlags type as declared in vulkan/vulkan.h:985
type PipelineVertexInputStateCreateFlags uint32

// PipelineInputAssemblyStateCreateFlags type as declared in vulkan/vulkan.h:986
type PipelineInputAssemblyStateCreateFlags uint32

// PipelineTessellationStateCreateFlags type as declared in vulkan/vulkan.h:987
type PipelineTessellationStateCreateFlags uint32

// PipelineViewportStateCreateFlags type as declared in vulkan/vulkan.h:988
type PipelineViewportStateCreateFlags uint32

// PipelineRasterizationStateCreateFlags type as declared in vulkan/vulkan.h:989
type PipelineRasterizationStateCreateFlags uint32

// CullModeFlags type as declared in vulkan/vulkan.h:997
type CullModeFlags uint32

// PipelineMultisampleStateCreateFlags type as declared in vulkan/vulkan.h:998
type PipelineMultisampleStateCreateFlags uint32

// PipelineDepthStencilStateCreateFlags type as declared in vulkan/vulkan.h:999
type PipelineDepthStencilStateCreateFlags uint32

// PipelineColorBlendStateCreateFlags type as declared in vulkan/vulkan.h:1000
type PipelineColorBlendStateCreateFlags uint32

// ColorComponentFlags type as declared in vulkan/vulkan.h:1008
type ColorComponentFlags uint32

// PipelineDynamicStateCreateFlags type as declared in vulkan/vulkan.h:1009
type PipelineDynamicStateCreateFlags uint32

// PipelineLayoutCreateFlags type as declared in vulkan/vulkan.h:1010
type PipelineLayoutCreateFlags uint32

// ShaderStageFlags type as declared in vulkan/vulkan.h:1011
type ShaderStageFlags uint32

// SamplerCreateFlags type as declared in vulkan/vulkan.h:1012
type SamplerCreateFlags uint32

// DescriptorSetLayoutCreateFlags type as declared in vulkan/vulkan.h:1013
type DescriptorSetLayoutCreateFlags uint32

// DescriptorPoolCreateFlags type as declared in vulkan/vulkan.h:1018
type DescriptorPoolCreateFlags uint32

// DescriptorPoolResetFlags type as declared in vulkan/vulkan.h:1019
type DescriptorPoolResetFlags uint32

// FramebufferCreateFlags type as declared in vulkan/vulkan.h:1020
type FramebufferCreateFlags uint32

// RenderPassCreateFlags type as declared in vulkan/vulkan.h:1021
type RenderPassCreateFlags uint32

// AttachmentDescriptionFlags type as declared in vulkan/vulkan.h:1026
type AttachmentDescriptionFlags uint32

// SubpassDescriptionFlags type as declared in vulkan/vulkan.h:1027
type SubpassDescriptionFlags uint32

// AccessFlags type as declared in vulkan/vulkan.h:1048
type AccessFlags uint32

// DependencyFlags type as declared in vulkan/vulkan.h:1053
type DependencyFlags uint32

// CommandPoolCreateFlags type as declared in vulkan/vulkan.h:1059
type CommandPoolCreateFlags uint32

// CommandPoolResetFlags type as declared in vulkan/vulkan.h:1064
type CommandPoolResetFlags uint32

// CommandBufferUsageFlags type as declared in vulkan/vulkan.h:1071
type CommandBufferUsageFlags uint32

// QueryControlFlags type as declared in vulkan/vulkan.h:1076
type QueryControlFlags uint32

// CommandBufferResetFlags type as declared in vulkan/vulkan.h:1081
type CommandBufferResetFlags uint32

// StencilFaceFlags type as declared in vulkan/vulkan.h:1088
type StencilFaceFlags uint32

// ApplicationInfo as declared in vulkan/vulkan.h:1129
type ApplicationInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	PApplicationName   string
	ApplicationVersion uint32
	PEngineName        string
	EngineVersion      uint32
	ApiVersion         uint32
	refb0af7378        *C.VkApplicationInfo
	allocsb0af7378     interface{}
}

// InstanceCreateInfo as declared in vulkan/vulkan.h:1140
type InstanceCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   InstanceCreateFlags
	PApplicationInfo        []ApplicationInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
	ref9b760798             *C.VkInstanceCreateInfo
	allocs9b760798          interface{}
}

// AllocationCallbacks as declared in vulkan/vulkan.h:1149
type AllocationCallbacks struct {
	PUserData             unsafe.Pointer
	PfnAllocation         PFN_vkAllocationFunction
	PfnReallocation       PFN_vkReallocationFunction
	PfnFree               PFN_vkFreeFunction
	PfnInternalAllocation PFN_vkInternalAllocationNotification
	PfnInternalFree       PFN_vkInternalFreeNotification
	ref9638e01            *C.VkAllocationCallbacks
	allocs9638e01         interface{}
}

// PhysicalDeviceFeatures as declared in vulkan/vulkan.h:1207
type PhysicalDeviceFeatures struct {
	RobustBufferAccess                      Bool32
	FullDrawIndexUint32                     Bool32
	ImageCubeArray                          Bool32
	IndependentBlend                        Bool32
	GeometryShader                          Bool32
	TessellationShader                      Bool32
	SampleRateShading                       Bool32
	DualSrcBlend                            Bool32
	LogicOp                                 Bool32
	MultiDrawIndirect                       Bool32
	DrawIndirectFirstInstance               Bool32
	DepthClamp                              Bool32
	DepthBiasClamp                          Bool32
	FillModeNonSolid                        Bool32
	DepthBounds                             Bool32
	WideLines                               Bool32
	LargePoints                             Bool32
	AlphaToOne                              Bool32
	MultiViewport                           Bool32
	SamplerAnisotropy                       Bool32
	TextureCompressionETC2                  Bool32
	TextureCompressionASTC_LDR              Bool32
	TextureCompressionBC                    Bool32
	OcclusionQueryPrecise                   Bool32
	PipelineStatisticsQuery                 Bool32
	VertexPipelineStoresAndAtomics          Bool32
	FragmentStoresAndAtomics                Bool32
	ShaderTessellationAndGeometryPointSize  Bool32
	ShaderImageGatherExtended               Bool32
	ShaderStorageImageExtendedFormats       Bool32
	ShaderStorageImageMultisample           Bool32
	ShaderStorageImageReadWithoutFormat     Bool32
	ShaderStorageImageWriteWithoutFormat    Bool32
	ShaderUniformBufferArrayDynamicIndexing Bool32
	ShaderSampledImageArrayDynamicIndexing  Bool32
	ShaderStorageBufferArrayDynamicIndexing Bool32
	ShaderStorageImageArrayDynamicIndexing  Bool32
	ShaderClipDistance                      Bool32
	ShaderCullDistance                      Bool32
	ShaderFloat64                           Bool32
	ShaderInt64                             Bool32
	ShaderInt16                             Bool32
	ShaderResourceResidency                 Bool32
	ShaderResourceMinLod                    Bool32
	SparseBinding                           Bool32
	SparseResidencyBuffer                   Bool32
	SparseResidencyImage2D                  Bool32
	SparseResidencyImage3D                  Bool32
	SparseResidency2Samples                 Bool32
	SparseResidency4Samples                 Bool32
	SparseResidency8Samples                 Bool32
	SparseResidency16Samples                Bool32
	SparseResidencyAliased                  Bool32
	VariableMultisampleRate                 Bool32
	InheritedQueries                        Bool32
	reff97e405d                             *C.VkPhysicalDeviceFeatures
	allocsf97e405d                          interface{}
}

// FormatProperties as declared in vulkan/vulkan.h:1213
type FormatProperties struct {
	LinearTilingFeatures  FormatFeatureFlags
	OptimalTilingFeatures FormatFeatureFlags
	BufferFeatures        FormatFeatureFlags
	refc4b9937b           *C.VkFormatProperties
	allocsc4b9937b        interface{}
}

// Extent3D as declared in vulkan/vulkan.h:1219
type Extent3D struct {
	Width          uint32
	Height         uint32
	Depth          uint32
	reffbf6c42a    *C.VkExtent3D
	allocsfbf6c42a interface{}
}

// ImageFormatProperties as declared in vulkan/vulkan.h:1227
type ImageFormatProperties struct {
	MaxExtent       Extent3D
	MaxMipLevels    uint32
	MaxArrayLayers  uint32
	SampleCounts    SampleCountFlags
	MaxResourceSize DeviceSize
	ref4cfb2ea2     *C.VkImageFormatProperties
	allocs4cfb2ea2  interface{}
}

// PhysicalDeviceLimits as declared in vulkan/vulkan.h:1336
type PhysicalDeviceLimits struct {
	MaxImageDimension1D                             uint32
	MaxImageDimension2D                             uint32
	MaxImageDimension3D                             uint32
	MaxImageDimensionCube                           uint32
	MaxImageArrayLayers                             uint32
	MaxTexelBufferElements                          uint32
	MaxUniformBufferRange                           uint32
	MaxStorageBufferRange                           uint32
	MaxPushConstantsSize                            uint32
	MaxMemoryAllocationCount                        uint32
	MaxSamplerAllocationCount                       uint32
	BufferImageGranularity                          DeviceSize
	SparseAddressSpaceSize                          DeviceSize
	MaxBoundDescriptorSets                          uint32
	MaxPerStageDescriptorSamplers                   uint32
	MaxPerStageDescriptorUniformBuffers             uint32
	MaxPerStageDescriptorStorageBuffers             uint32
	MaxPerStageDescriptorSampledImages              uint32
	MaxPerStageDescriptorStorageImages              uint32
	MaxPerStageDescriptorInputAttachments           uint32
	MaxPerStageResources                            uint32
	MaxDescriptorSetSamplers                        uint32
	MaxDescriptorSetUniformBuffers                  uint32
	MaxDescriptorSetUniformBuffersDynamic           uint32
	MaxDescriptorSetStorageBuffers                  uint32
	MaxDescriptorSetStorageBuffersDynamic           uint32
	MaxDescriptorSetSampledImages                   uint32
	MaxDescriptorSetStorageImages                   uint32
	MaxDescriptorSetInputAttachments                uint32
	MaxVertexInputAttributes                        uint32
	MaxVertexInputBindings                          uint32
	MaxVertexInputAttributeOffset                   uint32
	MaxVertexInputBindingStride                     uint32
	MaxVertexOutputComponents                       uint32
	MaxTessellationGenerationLevel                  uint32
	MaxTessellationPatchSize                        uint32
	MaxTessellationControlPerVertexInputComponents  uint32
	MaxTessellationControlPerVertexOutputComponents uint32
	MaxTessellationControlPerPatchOutputComponents  uint32
	MaxTessellationControlTotalOutputComponents     uint32
	MaxTessellationEvaluationInputComponents        uint32
	MaxTessellationEvaluationOutputComponents       uint32
	MaxGeometryShaderInvocations                    uint32
	MaxGeometryInputComponents                      uint32
	MaxGeometryOutputComponents                     uint32
	MaxGeometryOutputVertices                       uint32
	MaxGeometryTotalOutputComponents                uint32
	MaxFragmentInputComponents                      uint32
	MaxFragmentOutputAttachments                    uint32
	MaxFragmentDualSrcAttachments                   uint32
	MaxFragmentCombinedOutputResources              uint32
	MaxComputeSharedMemorySize                      uint32
	MaxComputeWorkGroupCount                        [3]uint32
	MaxComputeWorkGroupInvocations                  uint32
	MaxComputeWorkGroupSize                         [3]uint32
	SubPixelPrecisionBits                           uint32
	SubTexelPrecisionBits                           uint32
	MipmapPrecisionBits                             uint32
	MaxDrawIndexedIndexValue                        uint32
	MaxDrawIndirectCount                            uint32
	MaxSamplerLodBias                               float32
	MaxSamplerAnisotropy                            float32
	MaxViewports                                    uint32
	MaxViewportDimensions                           [2]uint32
	ViewportBoundsRange                             [2]float32
	ViewportSubPixelBits                            uint32
	MinMemoryMapAlignment                           uint
	MinTexelBufferOffsetAlignment                   DeviceSize
	MinUniformBufferOffsetAlignment                 DeviceSize
	MinStorageBufferOffsetAlignment                 DeviceSize
	MinTexelOffset                                  int32
	MaxTexelOffset                                  uint32
	MinTexelGatherOffset                            int32
	MaxTexelGatherOffset                            uint32
	MinInterpolationOffset                          float32
	MaxInterpolationOffset                          float32
	SubPixelInterpolationOffsetBits                 uint32
	MaxFramebufferWidth                             uint32
	MaxFramebufferHeight                            uint32
	MaxFramebufferLayers                            uint32
	FramebufferColorSampleCounts                    SampleCountFlags
	FramebufferDepthSampleCounts                    SampleCountFlags
	FramebufferStencilSampleCounts                  SampleCountFlags
	FramebufferNoAttachmentsSampleCounts            SampleCountFlags
	MaxColorAttachments                             uint32
	SampledImageColorSampleCounts                   SampleCountFlags
	SampledImageIntegerSampleCounts                 SampleCountFlags
	SampledImageDepthSampleCounts                   SampleCountFlags
	SampledImageStencilSampleCounts                 SampleCountFlags
	StorageImageSampleCounts                        SampleCountFlags
	MaxSampleMaskWords                              uint32
	TimestampComputeAndGraphics                     Bool32
	TimestampPeriod                                 float32
	MaxClipDistances                                uint32
	MaxCullDistances                                uint32
	MaxCombinedClipAndCullDistances                 uint32
	DiscreteQueuePriorities                         uint32
	PointSizeRange                                  [2]float32
	LineWidthRange                                  [2]float32
	PointSizeGranularity                            float32
	LineWidthGranularity                            float32
	StrictLines                                     Bool32
	StandardSampleLocations                         Bool32
	OptimalBufferCopyOffsetAlignment                DeviceSize
	OptimalBufferCopyRowPitchAlignment              DeviceSize
	NonCoherentAtomSize                             DeviceSize
	ref7926795a                                     *C.VkPhysicalDeviceLimits
	allocs7926795a                                  interface{}
}

// PhysicalDeviceSparseProperties as declared in vulkan/vulkan.h:1344
type PhysicalDeviceSparseProperties struct {
	ResidencyStandard2DBlockShape            Bool32
	ResidencyStandard2DMultisampleBlockShape Bool32
	ResidencyStandard3DBlockShape            Bool32
	ResidencyAlignedMipSize                  Bool32
	ResidencyNonResidentStrict               Bool32
	ref6d7c11e6                              *C.VkPhysicalDeviceSparseProperties
	allocs6d7c11e6                           interface{}
}

// PhysicalDeviceProperties as declared in vulkan/vulkan.h:1356
type PhysicalDeviceProperties struct {
	ApiVersion        uint32
	DriverVersion     uint32
	VendorID          uint32
	DeviceID          uint32
	DeviceType        PhysicalDeviceType
	DeviceName        [256]byte
	PipelineCacheUUID [16]byte
	Limits            PhysicalDeviceLimits
	SparseProperties  PhysicalDeviceSparseProperties
	ref1080ca9d       *C.VkPhysicalDeviceProperties
	allocs1080ca9d    interface{}
}

// QueueFamilyProperties as declared in vulkan/vulkan.h:1363
type QueueFamilyProperties struct {
	QueueFlags                  QueueFlags
	QueueCount                  uint32
	TimestampValidBits          uint32
	MinImageTransferGranularity Extent3D
	refd538c446                 *C.VkQueueFamilyProperties
	allocsd538c446              interface{}
}

// MemoryType as declared in vulkan/vulkan.h:1368
type MemoryType struct {
	PropertyFlags  MemoryPropertyFlags
	HeapIndex      uint32
	ref2f46e01d    *C.VkMemoryType
	allocs2f46e01d interface{}
}

// MemoryHeap as declared in vulkan/vulkan.h:1373
type MemoryHeap struct {
	Size           DeviceSize
	Flags          MemoryHeapFlags
	ref1eb195d5    *C.VkMemoryHeap
	allocs1eb195d5 interface{}
}

// PhysicalDeviceMemoryProperties as declared in vulkan/vulkan.h:1380
type PhysicalDeviceMemoryProperties struct {
	MemoryTypeCount uint32
	MemoryTypes     [32]MemoryType
	MemoryHeapCount uint32
	MemoryHeaps     [16]MemoryHeap
	ref3aabb5fd     *C.VkPhysicalDeviceMemoryProperties
	allocs3aabb5fd  interface{}
}

// DeviceQueueCreateInfo as declared in vulkan/vulkan.h:1389
type DeviceQueueCreateInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            DeviceQueueCreateFlags
	QueueFamilyIndex uint32
	QueueCount       uint32
	PQueuePriorities []float32
	ref6087b30d      *C.VkDeviceQueueCreateInfo
	allocs6087b30d   interface{}
}

// DeviceCreateInfo as declared in vulkan/vulkan.h:1402
type DeviceCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   DeviceCreateFlags
	QueueCreateInfoCount    uint32
	PQueueCreateInfos       []DeviceQueueCreateInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
	PEnabledFeatures        []PhysicalDeviceFeatures
	refc0d8b997             *C.VkDeviceCreateInfo
	allocsc0d8b997          interface{}
}

// ExtensionProperties as declared in vulkan/vulkan.h:1407
type ExtensionProperties struct {
	ExtensionName  [256]byte
	SpecVersion    uint32
	ref2f001956    *C.VkExtensionProperties
	allocs2f001956 interface{}
}

// LayerProperties as declared in vulkan/vulkan.h:1414
type LayerProperties struct {
	LayerName             [256]byte
	SpecVersion           uint32
	ImplementationVersion uint32
	Description           [256]byte
	refd9407ce7           *C.VkLayerProperties
	allocsd9407ce7        interface{}
}

// SubmitInfo as declared in vulkan/vulkan.h:1426
type SubmitInfo struct {
	SType                StructureType
	PNext                unsafe.Pointer
	WaitSemaphoreCount   uint32
	PWaitSemaphores      [][]Semaphore
	PWaitDstStageMask    []PipelineStageFlags
	CommandBufferCount   uint32
	PCommandBuffers      [][]CommandBuffer
	SignalSemaphoreCount uint32
	PSignalSemaphores    [][]Semaphore
	ref22884025          *C.VkSubmitInfo
	allocs22884025       interface{}
}

// MemoryAllocateInfo as declared in vulkan/vulkan.h:1433
type MemoryAllocateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	AllocationSize  DeviceSize
	MemoryTypeIndex uint32
	ref31032b       *C.VkMemoryAllocateInfo
	allocs31032b    interface{}
}

// MappedMemoryRange as declared in vulkan/vulkan.h:1441
type MappedMemoryRange struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Memory         []DeviceMemory
	Offset         DeviceSize
	Size           DeviceSize
	ref42a37320    *C.VkMappedMemoryRange
	allocs42a37320 interface{}
}

// MemoryRequirements as declared in vulkan/vulkan.h:1447
type MemoryRequirements struct {
	Size           DeviceSize
	Alignment      DeviceSize
	MemoryTypeBits uint32
	ref5259fc6b    *C.VkMemoryRequirements
	allocs5259fc6b interface{}
}

// SparseImageFormatProperties as declared in vulkan/vulkan.h:1453
type SparseImageFormatProperties struct {
	AspectMask       ImageAspectFlags
	ImageGranularity Extent3D
	Flags            SparseImageFormatFlags
	ref2c12cf44      *C.VkSparseImageFormatProperties
	allocs2c12cf44   interface{}
}

// SparseImageMemoryRequirements as declared in vulkan/vulkan.h:1461
type SparseImageMemoryRequirements struct {
	FormatProperties     SparseImageFormatProperties
	ImageMipTailFirstLod uint32
	ImageMipTailSize     DeviceSize
	ImageMipTailOffset   DeviceSize
	ImageMipTailStride   DeviceSize
	ref685a2323          *C.VkSparseImageMemoryRequirements
	allocs685a2323       interface{}
}

// SparseMemoryBind as declared in vulkan/vulkan.h:1469
type SparseMemoryBind struct {
	ResourceOffset DeviceSize
	Size           DeviceSize
	Memory         []DeviceMemory
	MemoryOffset   DeviceSize
	Flags          SparseMemoryBindFlags
	ref5bf418e8    *C.VkSparseMemoryBind
	allocs5bf418e8 interface{}
}

// SparseBufferMemoryBindInfo as declared in vulkan/vulkan.h:1475
type SparseBufferMemoryBindInfo struct {
	Buffer         []Buffer
	BindCount      uint32
	PBinds         []SparseMemoryBind
	refebcaf40c    *C.VkSparseBufferMemoryBindInfo
	allocsebcaf40c interface{}
}

// SparseImageOpaqueMemoryBindInfo as declared in vulkan/vulkan.h:1481
type SparseImageOpaqueMemoryBindInfo struct {
	Image          []Image
	BindCount      uint32
	PBinds         []SparseMemoryBind
	reffb1b3d56    *C.VkSparseImageOpaqueMemoryBindInfo
	allocsfb1b3d56 interface{}
}

// ImageSubresource as declared in vulkan/vulkan.h:1487
type ImageSubresource struct {
	AspectMask     ImageAspectFlags
	MipLevel       uint32
	ArrayLayer     uint32
	reffeaa0d8a    *C.VkImageSubresource
	allocsfeaa0d8a interface{}
}

// Offset3D as declared in vulkan/vulkan.h:1493
type Offset3D struct {
	X              int32
	Y              int32
	Z              int32
	ref2b6879c2    *C.VkOffset3D
	allocs2b6879c2 interface{}
}

// SparseImageMemoryBind as declared in vulkan/vulkan.h:1502
type SparseImageMemoryBind struct {
	Subresource    ImageSubresource
	Offset         Offset3D
	Extent         Extent3D
	Memory         []DeviceMemory
	MemoryOffset   DeviceSize
	Flags          SparseMemoryBindFlags
	ref41b516d7    *C.VkSparseImageMemoryBind
	allocs41b516d7 interface{}
}

// SparseImageMemoryBindInfo as declared in vulkan/vulkan.h:1508
type SparseImageMemoryBindInfo struct {
	Image          []Image
	BindCount      uint32
	PBinds         []SparseImageMemoryBind
	ref50faeb70    *C.VkSparseImageMemoryBindInfo
	allocs50faeb70 interface{}
}

// BindSparseInfo as declared in vulkan/vulkan.h:1523
type BindSparseInfo struct {
	SType                StructureType
	PNext                unsafe.Pointer
	WaitSemaphoreCount   uint32
	PWaitSemaphores      [][]Semaphore
	BufferBindCount      uint32
	PBufferBinds         []SparseBufferMemoryBindInfo
	ImageOpaqueBindCount uint32
	PImageOpaqueBinds    []SparseImageOpaqueMemoryBindInfo
	ImageBindCount       uint32
	PImageBinds          []SparseImageMemoryBindInfo
	SignalSemaphoreCount uint32
	PSignalSemaphores    [][]Semaphore
	refb0cbe910          *C.VkBindSparseInfo
	allocsb0cbe910       interface{}
}

// FenceCreateInfo as declared in vulkan/vulkan.h:1529
type FenceCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          FenceCreateFlags
	refb8ff4840    *C.VkFenceCreateInfo
	allocsb8ff4840 interface{}
}

// SemaphoreCreateInfo as declared in vulkan/vulkan.h:1535
type SemaphoreCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          SemaphoreCreateFlags
	reff130cd2b    *C.VkSemaphoreCreateInfo
	allocsf130cd2b interface{}
}

// EventCreateInfo as declared in vulkan/vulkan.h:1541
type EventCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          EventCreateFlags
	refa54f9ec8    *C.VkEventCreateInfo
	allocsa54f9ec8 interface{}
}

// QueryPoolCreateInfo as declared in vulkan/vulkan.h:1550
type QueryPoolCreateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	Flags              QueryPoolCreateFlags
	QueryType          QueryType
	QueryCount         uint32
	PipelineStatistics QueryPipelineStatisticFlags
	ref85dfcd4a        *C.VkQueryPoolCreateInfo
	allocs85dfcd4a     interface{}
}

// BufferCreateInfo as declared in vulkan/vulkan.h:1561
type BufferCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 BufferCreateFlags
	Size                  DeviceSize
	Usage                 BufferUsageFlags
	SharingMode           SharingMode
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	reffe19d2cd           *C.VkBufferCreateInfo
	allocsfe19d2cd        interface{}
}

// BufferViewCreateInfo as declared in vulkan/vulkan.h:1571
type BufferViewCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          BufferViewCreateFlags
	Buffer         []Buffer
	Format         Format
	Offset         DeviceSize
	_range         DeviceSize
	ref49b97027    *C.VkBufferViewCreateInfo
	allocs49b97027 interface{}
}

// ImageCreateInfo as declared in vulkan/vulkan.h:1589
type ImageCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 ImageCreateFlags
	ImageType             ImageType
	Format                Format
	Extent                Extent3D
	MipLevels             uint32
	ArrayLayers           uint32
	Samples               SampleCountFlagBits
	Tiling                ImageTiling
	Usage                 ImageUsageFlags
	SharingMode           SharingMode
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	InitialLayout         ImageLayout
	reffb587ba1           *C.VkImageCreateInfo
	allocsfb587ba1        interface{}
}

// SubresourceLayout as declared in vulkan/vulkan.h:1597
type SubresourceLayout struct {
	Offset         DeviceSize
	Size           DeviceSize
	RowPitch       DeviceSize
	ArrayPitch     DeviceSize
	DepthPitch     DeviceSize
	ref182612ad    *C.VkSubresourceLayout
	allocs182612ad interface{}
}

// ComponentMapping as declared in vulkan/vulkan.h:1604
type ComponentMapping struct {
	R              ComponentSwizzle
	G              ComponentSwizzle
	B              ComponentSwizzle
	A              ComponentSwizzle
	ref63d3d563    *C.VkComponentMapping
	allocs63d3d563 interface{}
}

// ImageSubresourceRange as declared in vulkan/vulkan.h:1612
type ImageSubresourceRange struct {
	AspectMask     ImageAspectFlags
	BaseMipLevel   uint32
	LevelCount     uint32
	BaseArrayLayer uint32
	LayerCount     uint32
	ref5aa1126     *C.VkImageSubresourceRange
	allocs5aa1126  interface{}
}

// ImageViewCreateInfo as declared in vulkan/vulkan.h:1623
type ImageViewCreateInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            ImageViewCreateFlags
	Image            []Image
	ViewType         ImageViewType
	Format           Format
	Components       ComponentMapping
	SubresourceRange ImageSubresourceRange
	ref77e8d4b8      *C.VkImageViewCreateInfo
	allocs77e8d4b8   interface{}
}

// ShaderModuleCreateInfo as declared in vulkan/vulkan.h:1631
type ShaderModuleCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          ShaderModuleCreateFlags
	CodeSize       uint
	PCode          []uint32
	refc663d23e    *C.VkShaderModuleCreateInfo
	allocsc663d23e interface{}
}

// PipelineCacheCreateInfo as declared in vulkan/vulkan.h:1639
type PipelineCacheCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           PipelineCacheCreateFlags
	InitialDataSize uint
	PInitialData    unsafe.Pointer
	reff11e7dd1     *C.VkPipelineCacheCreateInfo
	allocsf11e7dd1  interface{}
}

// SpecializationMapEntry as declared in vulkan/vulkan.h:1645
type SpecializationMapEntry struct {
	ConstantID     uint32
	Offset         uint32
	Size           uint
	ref2fd815d1    *C.VkSpecializationMapEntry
	allocs2fd815d1 interface{}
}

// SpecializationInfo as declared in vulkan/vulkan.h:1652
type SpecializationInfo struct {
	MapEntryCount  uint32
	PMapEntries    []SpecializationMapEntry
	DataSize       uint
	PData          unsafe.Pointer
	ref6bc395a3    *C.VkSpecializationInfo
	allocs6bc395a3 interface{}
}

// PipelineShaderStageCreateInfo as declared in vulkan/vulkan.h:1662
type PipelineShaderStageCreateInfo struct {
	SType               StructureType
	PNext               unsafe.Pointer
	Flags               PipelineShaderStageCreateFlags
	Stage               ShaderStageFlagBits
	Module              []ShaderModule
	PName               string
	PSpecializationInfo []SpecializationInfo
	ref50ba8b60         *C.VkPipelineShaderStageCreateInfo
	allocs50ba8b60      interface{}
}

// VertexInputBindingDescription as declared in vulkan/vulkan.h:1668
type VertexInputBindingDescription struct {
	Binding        uint32
	Stride         uint32
	InputRate      VertexInputRate
	ref5c9d8c23    *C.VkVertexInputBindingDescription
	allocs5c9d8c23 interface{}
}

// VertexInputAttributeDescription as declared in vulkan/vulkan.h:1675
type VertexInputAttributeDescription struct {
	Location       uint32
	Binding        uint32
	Format         Format
	Offset         uint32
	refdc4635ff    *C.VkVertexInputAttributeDescription
	allocsdc4635ff interface{}
}

// PipelineVertexInputStateCreateInfo as declared in vulkan/vulkan.h:1685
type PipelineVertexInputStateCreateInfo struct {
	SType                           StructureType
	PNext                           unsafe.Pointer
	Flags                           PipelineVertexInputStateCreateFlags
	VertexBindingDescriptionCount   uint32
	PVertexBindingDescriptions      []VertexInputBindingDescription
	VertexAttributeDescriptionCount uint32
	PVertexAttributeDescriptions    []VertexInputAttributeDescription
	ref5fe4aa50                     *C.VkPipelineVertexInputStateCreateInfo
	allocs5fe4aa50                  interface{}
}

// PipelineInputAssemblyStateCreateInfo as declared in vulkan/vulkan.h:1693
type PipelineInputAssemblyStateCreateInfo struct {
	SType                  StructureType
	PNext                  unsafe.Pointer
	Flags                  PipelineInputAssemblyStateCreateFlags
	Topology               PrimitiveTopology
	PrimitiveRestartEnable Bool32
	ref22e1691d            *C.VkPipelineInputAssemblyStateCreateInfo
	allocs22e1691d         interface{}
}

// PipelineTessellationStateCreateInfo as declared in vulkan/vulkan.h:1700
type PipelineTessellationStateCreateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	Flags              PipelineTessellationStateCreateFlags
	PatchControlPoints uint32
	ref4ef3997a        *C.VkPipelineTessellationStateCreateInfo
	allocs4ef3997a     interface{}
}

// Viewport as declared in vulkan/vulkan.h:1709
type Viewport struct {
	X              float32
	Y              float32
	Width          float32
	Height         float32
	MinDepth       float32
	MaxDepth       float32
	ref75cf5291    *C.VkViewport
	allocs75cf5291 interface{}
}

// Offset2D as declared in vulkan/vulkan.h:1714
type Offset2D struct {
	X              int32
	Y              int32
	ref32734883    *C.VkOffset2D
	allocs32734883 interface{}
}

// Extent2D as declared in vulkan/vulkan.h:1719
type Extent2D struct {
	Width          uint32
	Height         uint32
	refe2edf56b    *C.VkExtent2D
	allocse2edf56b interface{}
}

// Rect2D as declared in vulkan/vulkan.h:1724
type Rect2D struct {
	Offset         Offset2D
	Extent         Extent2D
	ref89e4256f    *C.VkRect2D
	allocs89e4256f interface{}
}

// PipelineViewportStateCreateInfo as declared in vulkan/vulkan.h:1734
type PipelineViewportStateCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          PipelineViewportStateCreateFlags
	ViewportCount  uint32
	PViewports     []Viewport
	ScissorCount   uint32
	PScissors      []Rect2D
	refc4705791    *C.VkPipelineViewportStateCreateInfo
	allocsc4705791 interface{}
}

// PipelineRasterizationStateCreateInfo as declared in vulkan/vulkan.h:1750
type PipelineRasterizationStateCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   PipelineRasterizationStateCreateFlags
	DepthClampEnable        Bool32
	RasterizerDiscardEnable Bool32
	PolygonMode             PolygonMode
	CullMode                CullModeFlags
	FrontFace               FrontFace
	DepthBiasEnable         Bool32
	DepthBiasConstantFactor float32
	DepthBiasClamp          float32
	DepthBiasSlopeFactor    float32
	LineWidth               float32
	ref48cb9fad             *C.VkPipelineRasterizationStateCreateInfo
	allocs48cb9fad          interface{}
}

// PipelineMultisampleStateCreateInfo as declared in vulkan/vulkan.h:1762
type PipelineMultisampleStateCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 PipelineMultisampleStateCreateFlags
	RasterizationSamples  SampleCountFlagBits
	SampleShadingEnable   Bool32
	MinSampleShading      float32
	PSampleMask           []SampleMask
	AlphaToCoverageEnable Bool32
	AlphaToOneEnable      Bool32
	refb6538bfb           *C.VkPipelineMultisampleStateCreateInfo
	allocsb6538bfb        interface{}
}

// StencilOpState as declared in vulkan/vulkan.h:1772
type StencilOpState struct {
	FailOp         StencilOp
	PassOp         StencilOp
	DepthFailOp    StencilOp
	CompareOp      CompareOp
	CompareMask    uint32
	WriteMask      uint32
	Reference      uint32
	ref28886871    *C.VkStencilOpState
	allocs28886871 interface{}
}

// PipelineDepthStencilStateCreateInfo as declared in vulkan/vulkan.h:1787
type PipelineDepthStencilStateCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 PipelineDepthStencilStateCreateFlags
	DepthTestEnable       Bool32
	DepthWriteEnable      Bool32
	DepthCompareOp        CompareOp
	DepthBoundsTestEnable Bool32
	StencilTestEnable     Bool32
	Front                 StencilOpState
	Back                  StencilOpState
	MinDepthBounds        float32
	MaxDepthBounds        float32
	refeabfcf1            *C.VkPipelineDepthStencilStateCreateInfo
	allocseabfcf1         interface{}
}

// PipelineColorBlendAttachmentState as declared in vulkan/vulkan.h:1798
type PipelineColorBlendAttachmentState struct {
	BlendEnable         Bool32
	SrcColorBlendFactor BlendFactor
	DstColorBlendFactor BlendFactor
	ColorBlendOp        BlendOp
	SrcAlphaBlendFactor BlendFactor
	DstAlphaBlendFactor BlendFactor
	AlphaBlendOp        BlendOp
	ColorWriteMask      ColorComponentFlags
	ref9e889477         *C.VkPipelineColorBlendAttachmentState
	allocs9e889477      interface{}
}

// PipelineColorBlendStateCreateInfo as declared in vulkan/vulkan.h:1809
type PipelineColorBlendStateCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           PipelineColorBlendStateCreateFlags
	LogicOpEnable   Bool32
	LogicOp         LogicOp
	AttachmentCount uint32
	PAttachments    []PipelineColorBlendAttachmentState
	BlendConstants  [4]float32
	ref2a9b490b     *C.VkPipelineColorBlendStateCreateInfo
	allocs2a9b490b  interface{}
}

// PipelineDynamicStateCreateInfo as declared in vulkan/vulkan.h:1817
type PipelineDynamicStateCreateInfo struct {
	SType             StructureType
	PNext             unsafe.Pointer
	Flags             PipelineDynamicStateCreateFlags
	DynamicStateCount uint32
	PDynamicStates    []DynamicState
	ref246d7bc8       *C.VkPipelineDynamicStateCreateInfo
	allocs246d7bc8    interface{}
}

// GraphicsPipelineCreateInfo as declared in vulkan/vulkan.h:1839
type GraphicsPipelineCreateInfo struct {
	SType               StructureType
	PNext               unsafe.Pointer
	Flags               PipelineCreateFlags
	StageCount          uint32
	PStages             []PipelineShaderStageCreateInfo
	PVertexInputState   []PipelineVertexInputStateCreateInfo
	PInputAssemblyState []PipelineInputAssemblyStateCreateInfo
	PTessellationState  []PipelineTessellationStateCreateInfo
	PViewportState      []PipelineViewportStateCreateInfo
	PRasterizationState []PipelineRasterizationStateCreateInfo
	PMultisampleState   []PipelineMultisampleStateCreateInfo
	PDepthStencilState  []PipelineDepthStencilStateCreateInfo
	PColorBlendState    []PipelineColorBlendStateCreateInfo
	PDynamicState       []PipelineDynamicStateCreateInfo
	Layout              []PipelineLayout
	RenderPass          []RenderPass
	Subpass             uint32
	BasePipelineHandle  []Pipeline
	BasePipelineIndex   int32
	ref178f88b6         *C.VkGraphicsPipelineCreateInfo
	allocs178f88b6      interface{}
}

// ComputePipelineCreateInfo as declared in vulkan/vulkan.h:1849
type ComputePipelineCreateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	Flags              PipelineCreateFlags
	Stage              PipelineShaderStageCreateInfo
	Layout             []PipelineLayout
	BasePipelineHandle []Pipeline
	BasePipelineIndex  int32
	ref77823220        *C.VkComputePipelineCreateInfo
	allocs77823220     interface{}
}

// PushConstantRange as declared in vulkan/vulkan.h:1855
type PushConstantRange struct {
	StageFlags     ShaderStageFlags
	Offset         uint32
	Size           uint32
	ref6f025856    *C.VkPushConstantRange
	allocs6f025856 interface{}
}

// PipelineLayoutCreateInfo as declared in vulkan/vulkan.h:1865
type PipelineLayoutCreateInfo struct {
	SType                  StructureType
	PNext                  unsafe.Pointer
	Flags                  PipelineLayoutCreateFlags
	SetLayoutCount         uint32
	PSetLayouts            [][]DescriptorSetLayout
	PushConstantRangeCount uint32
	PPushConstantRanges    []PushConstantRange
	ref64cc4eed            *C.VkPipelineLayoutCreateInfo
	allocs64cc4eed         interface{}
}

// SamplerCreateInfo as declared in vulkan/vulkan.h:1886
type SamplerCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   SamplerCreateFlags
	MagFilter               Filter
	MinFilter               Filter
	MipmapMode              SamplerMipmapMode
	AddressModeU            SamplerAddressMode
	AddressModeV            SamplerAddressMode
	AddressModeW            SamplerAddressMode
	MipLodBias              float32
	AnisotropyEnable        Bool32
	MaxAnisotropy           float32
	CompareEnable           Bool32
	CompareOp               CompareOp
	MinLod                  float32
	MaxLod                  float32
	BorderColor             BorderColor
	UnnormalizedCoordinates Bool32
	refce034abf             *C.VkSamplerCreateInfo
	allocsce034abf          interface{}
}

// DescriptorSetLayoutBinding as declared in vulkan/vulkan.h:1894
type DescriptorSetLayoutBinding struct {
	Binding            uint32
	DescriptorType     DescriptorType
	DescriptorCount    uint32
	StageFlags         ShaderStageFlags
	PImmutableSamplers [][]Sampler
	ref8b50b4ec        *C.VkDescriptorSetLayoutBinding
	allocs8b50b4ec     interface{}
}

// DescriptorSetLayoutCreateInfo as declared in vulkan/vulkan.h:1902
type DescriptorSetLayoutCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DescriptorSetLayoutCreateFlags
	BindingCount   uint32
	PBindings      []DescriptorSetLayoutBinding
	ref5ee8e0ed    *C.VkDescriptorSetLayoutCreateInfo
	allocs5ee8e0ed interface{}
}

// DescriptorPoolSize as declared in vulkan/vulkan.h:1907
type DescriptorPoolSize struct {
	_type           DescriptorType
	DescriptorCount uint32
	refe15137da     *C.VkDescriptorPoolSize
	allocse15137da  interface{}
}

// DescriptorPoolCreateInfo as declared in vulkan/vulkan.h:1916
type DescriptorPoolCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DescriptorPoolCreateFlags
	MaxSets        uint32
	PoolSizeCount  uint32
	PPoolSizes     []DescriptorPoolSize
	ref19868463    *C.VkDescriptorPoolCreateInfo
	allocs19868463 interface{}
}

// DescriptorSetAllocateInfo as declared in vulkan/vulkan.h:1924
type DescriptorSetAllocateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	DescriptorPool     []DescriptorPool
	DescriptorSetCount uint32
	PSetLayouts        [][]DescriptorSetLayout
	ref2dd6cc22        *C.VkDescriptorSetAllocateInfo
	allocs2dd6cc22     interface{}
}

// DescriptorImageInfo as declared in vulkan/vulkan.h:1930
type DescriptorImageInfo struct {
	Sampler        []Sampler
	ImageView      []ImageView
	ImageLayout    ImageLayout
	refaf073b07    *C.VkDescriptorImageInfo
	allocsaf073b07 interface{}
}

// DescriptorBufferInfo as declared in vulkan/vulkan.h:1936
type DescriptorBufferInfo struct {
	Buffer         []Buffer
	Offset         DeviceSize
	_range         DeviceSize
	refe64bec0e    *C.VkDescriptorBufferInfo
	allocse64bec0e interface{}
}

// WriteDescriptorSet as declared in vulkan/vulkan.h:1949
type WriteDescriptorSet struct {
	SType            StructureType
	PNext            unsafe.Pointer
	DstSet           []DescriptorSet
	DstBinding       uint32
	DstArrayElement  uint32
	DescriptorCount  uint32
	DescriptorType   DescriptorType
	PImageInfo       []DescriptorImageInfo
	PBufferInfo      []DescriptorBufferInfo
	PTexelBufferView [][]BufferView
	ref3cec3f3f      *C.VkWriteDescriptorSet
	allocs3cec3f3f   interface{}
}

// CopyDescriptorSet as declared in vulkan/vulkan.h:1961
type CopyDescriptorSet struct {
	SType           StructureType
	PNext           unsafe.Pointer
	SrcSet          []DescriptorSet
	SrcBinding      uint32
	SrcArrayElement uint32
	DstSet          []DescriptorSet
	DstBinding      uint32
	DstArrayElement uint32
	DescriptorCount uint32
	reffe237a3a     *C.VkCopyDescriptorSet
	allocsfe237a3a  interface{}
}

// FramebufferCreateInfo as declared in vulkan/vulkan.h:1973
type FramebufferCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           FramebufferCreateFlags
	RenderPass      []RenderPass
	AttachmentCount uint32
	PAttachments    [][]ImageView
	Width           uint32
	Height          uint32
	Layers          uint32
	refa3ad85cc     *C.VkFramebufferCreateInfo
	allocsa3ad85cc  interface{}
}

// AttachmentDescription as declared in vulkan/vulkan.h:1985
type AttachmentDescription struct {
	Flags          AttachmentDescriptionFlags
	Format         Format
	Samples        SampleCountFlagBits
	LoadOp         AttachmentLoadOp
	StoreOp        AttachmentStoreOp
	StencilLoadOp  AttachmentLoadOp
	StencilStoreOp AttachmentStoreOp
	InitialLayout  ImageLayout
	FinalLayout    ImageLayout
	refa5d685fc    *C.VkAttachmentDescription
	allocsa5d685fc interface{}
}

// AttachmentReference as declared in vulkan/vulkan.h:1990
type AttachmentReference struct {
	Attachment     uint32
	Layout         ImageLayout
	refef4776de    *C.VkAttachmentReference
	allocsef4776de interface{}
}

// SubpassDescription as declared in vulkan/vulkan.h:2003
type SubpassDescription struct {
	Flags                   SubpassDescriptionFlags
	PipelineBindPoint       PipelineBindPoint
	InputAttachmentCount    uint32
	PInputAttachments       []AttachmentReference
	ColorAttachmentCount    uint32
	PColorAttachments       []AttachmentReference
	PResolveAttachments     []AttachmentReference
	PDepthStencilAttachment []AttachmentReference
	PreserveAttachmentCount uint32
	PPreserveAttachments    []uint32
	refc7bfeda              *C.VkSubpassDescription
	allocsc7bfeda           interface{}
}

// SubpassDependency as declared in vulkan/vulkan.h:2013
type SubpassDependency struct {
	SrcSubpass      uint32
	DstSubpass      uint32
	SrcStageMask    PipelineStageFlags
	DstStageMask    PipelineStageFlags
	SrcAccessMask   AccessFlags
	DstAccessMask   AccessFlags
	DependencyFlags DependencyFlags
	refdb197adb     *C.VkSubpassDependency
	allocsdb197adb  interface{}
}

// RenderPassCreateInfo as declared in vulkan/vulkan.h:2025
type RenderPassCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           RenderPassCreateFlags
	AttachmentCount uint32
	PAttachments    []AttachmentDescription
	SubpassCount    uint32
	PSubpasses      []SubpassDescription
	DependencyCount uint32
	PDependencies   []SubpassDependency
	ref886d7d86     *C.VkRenderPassCreateInfo
	allocs886d7d86  interface{}
}

// CommandPoolCreateInfo as declared in vulkan/vulkan.h:2032
type CommandPoolCreateInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            CommandPoolCreateFlags
	QueueFamilyIndex uint32
	ref73550de0      *C.VkCommandPoolCreateInfo
	allocs73550de0   interface{}
}

// CommandBufferAllocateInfo as declared in vulkan/vulkan.h:2040
type CommandBufferAllocateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	CommandPool        []CommandPool
	Level              CommandBufferLevel
	CommandBufferCount uint32
	refd1a0a7c8        *C.VkCommandBufferAllocateInfo
	allocsd1a0a7c8     interface{}
}

// CommandBufferInheritanceInfo as declared in vulkan/vulkan.h:2051
type CommandBufferInheritanceInfo struct {
	SType                StructureType
	PNext                unsafe.Pointer
	RenderPass           []RenderPass
	Subpass              uint32
	Framebuffer          []Framebuffer
	OcclusionQueryEnable Bool32
	QueryFlags           QueryControlFlags
	PipelineStatistics   QueryPipelineStatisticFlags
	ref737f8019          *C.VkCommandBufferInheritanceInfo
	allocs737f8019       interface{}
}

// CommandBufferBeginInfo as declared in vulkan/vulkan.h:2058
type CommandBufferBeginInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            CommandBufferUsageFlags
	PInheritanceInfo []CommandBufferInheritanceInfo
	ref266762df      *C.VkCommandBufferBeginInfo
	allocs266762df   interface{}
}

// BufferCopy as declared in vulkan/vulkan.h:2064
type BufferCopy struct {
	SrcOffset      DeviceSize
	DstOffset      DeviceSize
	Size           DeviceSize
	ref12184ffd    *C.VkBufferCopy
	allocs12184ffd interface{}
}

// ImageSubresourceLayers as declared in vulkan/vulkan.h:2071
type ImageSubresourceLayers struct {
	AspectMask     ImageAspectFlags
	MipLevel       uint32
	BaseArrayLayer uint32
	LayerCount     uint32
	ref3b13bcd2    *C.VkImageSubresourceLayers
	allocs3b13bcd2 interface{}
}

// ImageCopy as declared in vulkan/vulkan.h:2079
type ImageCopy struct {
	SrcSubresource ImageSubresourceLayers
	SrcOffset      Offset3D
	DstSubresource ImageSubresourceLayers
	DstOffset      Offset3D
	Extent         Extent3D
	ref4e7a1214    *C.VkImageCopy
	allocs4e7a1214 interface{}
}

// ImageBlit as declared in vulkan/vulkan.h:2086
type ImageBlit struct {
	SrcSubresource ImageSubresourceLayers
	SrcOffsets     [2]Offset3D
	DstSubresource ImageSubresourceLayers
	DstOffsets     [2]Offset3D
	ref11311e8d    *C.VkImageBlit
	allocs11311e8d interface{}
}

// BufferImageCopy as declared in vulkan/vulkan.h:2095
type BufferImageCopy struct {
	BufferOffset      DeviceSize
	BufferRowLength   uint32
	BufferImageHeight uint32
	ImageSubresource  ImageSubresourceLayers
	ImageOffset       Offset3D
	ImageExtent       Extent3D
	ref6d50e36e       *C.VkBufferImageCopy
	allocs6d50e36e    interface{}
}

// ClearColorValue type as declared in vulkan/vulkan.h:2101
type ClearColorValue [16]byte

// ClearDepthStencilValue as declared in vulkan/vulkan.h:2106
type ClearDepthStencilValue struct {
	Depth          float32
	Stencil        uint32
	refa7d07c03    *C.VkClearDepthStencilValue
	allocsa7d07c03 interface{}
}

// ClearValue type as declared in vulkan/vulkan.h:2111
type ClearValue [16]byte

// ClearAttachment as declared in vulkan/vulkan.h:2117
type ClearAttachment struct {
	AspectMask      ImageAspectFlags
	ColorAttachment uint32
	ClearValue      [16]ClearValue
	refe9150303     *C.VkClearAttachment
	allocse9150303  interface{}
}

// ClearRect as declared in vulkan/vulkan.h:2123
type ClearRect struct {
	Rect           Rect2D
	BaseArrayLayer uint32
	LayerCount     uint32
	ref1d449c8b    *C.VkClearRect
	allocs1d449c8b interface{}
}

// ImageResolve as declared in vulkan/vulkan.h:2131
type ImageResolve struct {
	SrcSubresource ImageSubresourceLayers
	SrcOffset      Offset3D
	DstSubresource ImageSubresourceLayers
	DstOffset      Offset3D
	Extent         Extent3D
	ref7bda856d    *C.VkImageResolve
	allocs7bda856d interface{}
}

// MemoryBarrier as declared in vulkan/vulkan.h:2138
type MemoryBarrier struct {
	SType          StructureType
	PNext          unsafe.Pointer
	SrcAccessMask  AccessFlags
	DstAccessMask  AccessFlags
	ref977c944e    *C.VkMemoryBarrier
	allocs977c944e interface{}
}

// BufferMemoryBarrier as declared in vulkan/vulkan.h:2150
type BufferMemoryBarrier struct {
	SType               StructureType
	PNext               unsafe.Pointer
	SrcAccessMask       AccessFlags
	DstAccessMask       AccessFlags
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Buffer              []Buffer
	Offset              DeviceSize
	Size                DeviceSize
	refeaf4700b         *C.VkBufferMemoryBarrier
	allocseaf4700b      interface{}
}

// ImageMemoryBarrier as declared in vulkan/vulkan.h:2163
type ImageMemoryBarrier struct {
	SType               StructureType
	PNext               unsafe.Pointer
	SrcAccessMask       AccessFlags
	DstAccessMask       AccessFlags
	OldLayout           ImageLayout
	NewLayout           ImageLayout
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Image               []Image
	SubresourceRange    ImageSubresourceRange
	refd52734ec         *C.VkImageMemoryBarrier
	allocsd52734ec      interface{}
}

// RenderPassBeginInfo as declared in vulkan/vulkan.h:2173
type RenderPassBeginInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	RenderPass      []RenderPass
	Framebuffer     []Framebuffer
	RenderArea      Rect2D
	ClearValueCount uint32
	PClearValues    [16]ClearValue
	ref3c3752c8     *C.VkRenderPassBeginInfo
	allocs3c3752c8  interface{}
}

// DispatchIndirectCommand as declared in vulkan/vulkan.h:2179
type DispatchIndirectCommand struct {
	X              uint32
	Y              uint32
	Z              uint32
	refd298ba27    *C.VkDispatchIndirectCommand
	allocsd298ba27 interface{}
}

// DrawIndexedIndirectCommand as declared in vulkan/vulkan.h:2187
type DrawIndexedIndirectCommand struct {
	IndexCount     uint32
	InstanceCount  uint32
	FirstIndex     uint32
	VertexOffset   int32
	FirstInstance  uint32
	ref4c78b5c3    *C.VkDrawIndexedIndirectCommand
	allocs4c78b5c3 interface{}
}

// DrawIndirectCommand as declared in vulkan/vulkan.h:2194
type DrawIndirectCommand struct {
	VertexCount    uint32
	InstanceCount  uint32
	FirstVertex    uint32
	FirstInstance  uint32
	ref2b5b67c4    *C.VkDrawIndirectCommand
	allocs2b5b67c4 interface{}
}

// SurfaceTransformFlagsKHR type as declared in vulkan/vulkan.h:3172
type SurfaceTransformFlagsKHR uint32

// CompositeAlphaFlagsKHR type as declared in vulkan/vulkan.h:3180
type CompositeAlphaFlagsKHR uint32

// SurfaceCapabilitiesKHR as declared in vulkan/vulkan.h:3193
type SurfaceCapabilitiesKHR struct {
	MinImageCount           uint32
	MaxImageCount           uint32
	CurrentExtent           Extent2D
	MinImageExtent          Extent2D
	MaxImageExtent          Extent2D
	MaxImageArrayLayers     uint32
	SupportedTransforms     SurfaceTransformFlagsKHR
	CurrentTransform        SurfaceTransformFlagBitsKHR
	SupportedCompositeAlpha CompositeAlphaFlagsKHR
	SupportedUsageFlags     ImageUsageFlags
	ref11d5f596             *C.VkSurfaceCapabilitiesKHR
	allocs11d5f596          interface{}
}

// SurfaceFormatKHR as declared in vulkan/vulkan.h:3198
type SurfaceFormatKHR struct {
	Format         Format
	ColorSpace     ColorSpaceKHR
	refedaf82ca    *C.VkSurfaceFormatKHR
	allocsedaf82ca interface{}
}

// SwapchainCreateFlagsKHR type as declared in vulkan/vulkan.h:3243
type SwapchainCreateFlagsKHR uint32

// SwapchainCreateInfoKHR as declared in vulkan/vulkan.h:3264
type SwapchainCreateInfoKHR struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 SwapchainCreateFlagsKHR
	Surface               []SurfaceKHR
	MinImageCount         uint32
	ImageFormat           Format
	ImageColorSpace       ColorSpaceKHR
	ImageExtent           Extent2D
	ImageArrayLayers      uint32
	ImageUsage            ImageUsageFlags
	ImageSharingMode      SharingMode
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	PreTransform          SurfaceTransformFlagBitsKHR
	CompositeAlpha        CompositeAlphaFlagBitsKHR
	PresentMode           PresentModeKHR
	Clipped               Bool32
	OldSwapchain          []SwapchainKHR
	refdb619e1c           *C.VkSwapchainCreateInfoKHR
	allocsdb619e1c        interface{}
}

// PresentInfoKHR as declared in vulkan/vulkan.h:3275
type PresentInfoKHR struct {
	SType              StructureType
	PNext              unsafe.Pointer
	WaitSemaphoreCount uint32
	PWaitSemaphores    [][]Semaphore
	SwapchainCount     uint32
	PSwapchains        [][]SwapchainKHR
	PImageIndices      []uint32
	PResults           []Result
	ref1d0e82d4        *C.VkPresentInfoKHR
	allocs1d0e82d4     interface{}
}

// DisplayPlaneAlphaFlagsKHR type as declared in vulkan/vulkan.h:3329
type DisplayPlaneAlphaFlagsKHR uint32

// DisplayModeCreateFlagsKHR type as declared in vulkan/vulkan.h:3330
type DisplayModeCreateFlagsKHR uint32

// DisplaySurfaceCreateFlagsKHR type as declared in vulkan/vulkan.h:3331
type DisplaySurfaceCreateFlagsKHR uint32

// DisplayPropertiesKHR as declared in vulkan/vulkan.h:3341
type DisplayPropertiesKHR struct {
	Display              []DisplayKHR
	DisplayName          string
	PhysicalDimensions   Extent2D
	PhysicalResolution   Extent2D
	SupportedTransforms  SurfaceTransformFlagsKHR
	PlaneReorderPossible Bool32
	PersistentContent    Bool32
	reffe2a7187          *C.VkDisplayPropertiesKHR
	allocsfe2a7187       interface{}
}

// DisplayModeParametersKHR as declared in vulkan/vulkan.h:3346
type DisplayModeParametersKHR struct {
	VisibleRegion  Extent2D
	RefreshRate    uint32
	refe016f77f    *C.VkDisplayModeParametersKHR
	allocse016f77f interface{}
}

// DisplayModePropertiesKHR as declared in vulkan/vulkan.h:3351
type DisplayModePropertiesKHR struct {
	DisplayMode    []DisplayModeKHR
	Parameters     DisplayModeParametersKHR
	ref5e3abaaa    *C.VkDisplayModePropertiesKHR
	allocs5e3abaaa interface{}
}

// DisplayModeCreateInfoKHR as declared in vulkan/vulkan.h:3358
type DisplayModeCreateInfoKHR struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DisplayModeCreateFlagsKHR
	Parameters     DisplayModeParametersKHR
	ref392fca31    *C.VkDisplayModeCreateInfoKHR
	allocs392fca31 interface{}
}

// DisplayPlaneCapabilitiesKHR as declared in vulkan/vulkan.h:3370
type DisplayPlaneCapabilitiesKHR struct {
	SupportedAlpha DisplayPlaneAlphaFlagsKHR
	MinSrcPosition Offset2D
	MaxSrcPosition Offset2D
	MinSrcExtent   Extent2D
	MaxSrcExtent   Extent2D
	MinDstPosition Offset2D
	MaxDstPosition Offset2D
	MinDstExtent   Extent2D
	MaxDstExtent   Extent2D
	ref6f31fcaf    *C.VkDisplayPlaneCapabilitiesKHR
	allocs6f31fcaf interface{}
}

// DisplayPlanePropertiesKHR as declared in vulkan/vulkan.h:3375
type DisplayPlanePropertiesKHR struct {
	CurrentDisplay    []DisplayKHR
	CurrentStackIndex uint32
	refce3db3f6       *C.VkDisplayPlanePropertiesKHR
	allocsce3db3f6    interface{}
}

// DisplaySurfaceCreateInfoKHR as declared in vulkan/vulkan.h:3388
type DisplaySurfaceCreateInfoKHR struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           DisplaySurfaceCreateFlagsKHR
	DisplayMode     []DisplayModeKHR
	PlaneIndex      uint32
	PlaneStackIndex uint32
	Transform       SurfaceTransformFlagBitsKHR
	GlobalAlpha     float32
	AlphaMode       DisplayPlaneAlphaFlagBitsKHR
	ImageExtent     Extent2D
	ref58445c35     *C.VkDisplaySurfaceCreateInfoKHR
	allocs58445c35  interface{}
}

// DisplayPresentInfoKHR as declared in vulkan/vulkan.h:3452
type DisplayPresentInfoKHR struct {
	SType          StructureType
	PNext          unsafe.Pointer
	SrcRect        Rect2D
	DstRect        Rect2D
	Persistent     Bool32
	ref8d2571e4    *C.VkDisplayPresentInfoKHR
	allocs8d2571e4 interface{}
}

// DebugReportFlagsEXT type as declared in vulkan/vulkan.h:3728
type DebugReportFlagsEXT uint32

// DebugReportCallbackCreateInfoEXT as declared in vulkan/vulkan.h:3747
type DebugReportCallbackCreateInfoEXT struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DebugReportFlagsEXT
	PfnCallback    PFN_vkDebugReportCallbackEXT
	PUserData      unsafe.Pointer
	refc8238563    *C.VkDebugReportCallbackCreateInfoEXT
	allocsc8238563 interface{}
}
