// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 17 May 2016 03:29:29 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package vulkan

/*
#cgo CFLAGS: -I. -DVK_USE_PLATFORM_ANDROID_KHR -DVK_NO_PROTOTYPES -D__ARM_ARCH_7A__
#include "vulkan/vulkan.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// Flags type as declared in vulkan/vulkan.h:64
type Flags uint32

// Bool32 type as declared in vulkan/vulkan.h:65
type Bool32 uint32

// DeviceSize type as declared in vulkan/vulkan.h:66
type DeviceSize uint64

// SampleMask type as declared in vulkan/vulkan.h:67
type SampleMask uint32

// Instance as declared in vulkan/vulkan.h:69
type Instance C.VkInstance

// PhysicalDevice as declared in vulkan/vulkan.h:70
type PhysicalDevice C.VkPhysicalDevice

// Device as declared in vulkan/vulkan.h:71
type Device C.VkDevice

// Queue as declared in vulkan/vulkan.h:72
type Queue C.VkQueue

// Semaphore as declared in vulkan/vulkan.h:73
type Semaphore C.VkSemaphore

// CommandBuffer as declared in vulkan/vulkan.h:74
type CommandBuffer C.VkCommandBuffer

// Fence as declared in vulkan/vulkan.h:75
type Fence C.VkFence

// DeviceMemory as declared in vulkan/vulkan.h:76
type DeviceMemory C.VkDeviceMemory

// Buffer as declared in vulkan/vulkan.h:77
type Buffer C.VkBuffer

// Image as declared in vulkan/vulkan.h:78
type Image C.VkImage

// Event as declared in vulkan/vulkan.h:79
type Event C.VkEvent

// QueryPool as declared in vulkan/vulkan.h:80
type QueryPool C.VkQueryPool

// BufferView as declared in vulkan/vulkan.h:81
type BufferView C.VkBufferView

// ImageView as declared in vulkan/vulkan.h:82
type ImageView C.VkImageView

// ShaderModule as declared in vulkan/vulkan.h:83
type ShaderModule C.VkShaderModule

// PipelineCache as declared in vulkan/vulkan.h:84
type PipelineCache C.VkPipelineCache

// PipelineLayout as declared in vulkan/vulkan.h:85
type PipelineLayout C.VkPipelineLayout

// RenderPass as declared in vulkan/vulkan.h:86
type RenderPass C.VkRenderPass

// Pipeline as declared in vulkan/vulkan.h:87
type Pipeline C.VkPipeline

// DescriptorSetLayout as declared in vulkan/vulkan.h:88
type DescriptorSetLayout C.VkDescriptorSetLayout

// Sampler as declared in vulkan/vulkan.h:89
type Sampler C.VkSampler

// DescriptorPool as declared in vulkan/vulkan.h:90
type DescriptorPool C.VkDescriptorPool

// DescriptorSet as declared in vulkan/vulkan.h:91
type DescriptorSet C.VkDescriptorSet

// Framebuffer as declared in vulkan/vulkan.h:92
type Framebuffer C.VkFramebuffer

// CommandPool as declared in vulkan/vulkan.h:93
type CommandPool C.VkCommandPool

// InstanceCreateFlags type as declared in vulkan/vulkan.h:800
type InstanceCreateFlags uint32

// FormatFeatureFlags type as declared in vulkan/vulkan.h:819
type FormatFeatureFlags uint32

// ImageUsageFlags type as declared in vulkan/vulkan.h:832
type ImageUsageFlags uint32

// ImageCreateFlags type as declared in vulkan/vulkan.h:842
type ImageCreateFlags uint32

// SampleCountFlags type as declared in vulkan/vulkan.h:854
type SampleCountFlags uint32

// QueueFlags type as declared in vulkan/vulkan.h:863
type QueueFlags uint32

// MemoryPropertyFlags type as declared in vulkan/vulkan.h:873
type MemoryPropertyFlags uint32

// MemoryHeapFlags type as declared in vulkan/vulkan.h:879
type MemoryHeapFlags uint32

// DeviceCreateFlags type as declared in vulkan/vulkan.h:880
type DeviceCreateFlags uint32

// DeviceQueueCreateFlags type as declared in vulkan/vulkan.h:881
type DeviceQueueCreateFlags uint32

// PipelineStageFlags type as declared in vulkan/vulkan.h:903
type PipelineStageFlags uint32

// MemoryMapFlags type as declared in vulkan/vulkan.h:904
type MemoryMapFlags uint32

// ImageAspectFlags type as declared in vulkan/vulkan.h:913
type ImageAspectFlags uint32

// SparseImageFormatFlags type as declared in vulkan/vulkan.h:921
type SparseImageFormatFlags uint32

// SparseMemoryBindFlags type as declared in vulkan/vulkan.h:927
type SparseMemoryBindFlags uint32

// FenceCreateFlags type as declared in vulkan/vulkan.h:933
type FenceCreateFlags uint32

// SemaphoreCreateFlags type as declared in vulkan/vulkan.h:934
type SemaphoreCreateFlags uint32

// EventCreateFlags type as declared in vulkan/vulkan.h:935
type EventCreateFlags uint32

// QueryPoolCreateFlags type as declared in vulkan/vulkan.h:936
type QueryPoolCreateFlags uint32

// QueryPipelineStatisticFlags type as declared in vulkan/vulkan.h:952
type QueryPipelineStatisticFlags uint32

// QueryResultFlags type as declared in vulkan/vulkan.h:961
type QueryResultFlags uint32

// BufferCreateFlags type as declared in vulkan/vulkan.h:969
type BufferCreateFlags uint32

// BufferUsageFlags type as declared in vulkan/vulkan.h:983
type BufferUsageFlags uint32

// BufferViewCreateFlags type as declared in vulkan/vulkan.h:984
type BufferViewCreateFlags uint32

// ImageViewCreateFlags type as declared in vulkan/vulkan.h:985
type ImageViewCreateFlags uint32

// ShaderModuleCreateFlags type as declared in vulkan/vulkan.h:986
type ShaderModuleCreateFlags uint32

// PipelineCacheCreateFlags type as declared in vulkan/vulkan.h:987
type PipelineCacheCreateFlags uint32

// PipelineCreateFlags type as declared in vulkan/vulkan.h:995
type PipelineCreateFlags uint32

// PipelineShaderStageCreateFlags type as declared in vulkan/vulkan.h:996
type PipelineShaderStageCreateFlags uint32

// PipelineVertexInputStateCreateFlags type as declared in vulkan/vulkan.h:1009
type PipelineVertexInputStateCreateFlags uint32

// PipelineInputAssemblyStateCreateFlags type as declared in vulkan/vulkan.h:1010
type PipelineInputAssemblyStateCreateFlags uint32

// PipelineTessellationStateCreateFlags type as declared in vulkan/vulkan.h:1011
type PipelineTessellationStateCreateFlags uint32

// PipelineViewportStateCreateFlags type as declared in vulkan/vulkan.h:1012
type PipelineViewportStateCreateFlags uint32

// PipelineRasterizationStateCreateFlags type as declared in vulkan/vulkan.h:1013
type PipelineRasterizationStateCreateFlags uint32

// CullModeFlags type as declared in vulkan/vulkan.h:1022
type CullModeFlags uint32

// PipelineMultisampleStateCreateFlags type as declared in vulkan/vulkan.h:1023
type PipelineMultisampleStateCreateFlags uint32

// PipelineDepthStencilStateCreateFlags type as declared in vulkan/vulkan.h:1024
type PipelineDepthStencilStateCreateFlags uint32

// PipelineColorBlendStateCreateFlags type as declared in vulkan/vulkan.h:1025
type PipelineColorBlendStateCreateFlags uint32

// ColorComponentFlags type as declared in vulkan/vulkan.h:1034
type ColorComponentFlags uint32

// PipelineDynamicStateCreateFlags type as declared in vulkan/vulkan.h:1035
type PipelineDynamicStateCreateFlags uint32

// PipelineLayoutCreateFlags type as declared in vulkan/vulkan.h:1036
type PipelineLayoutCreateFlags uint32

// ShaderStageFlags type as declared in vulkan/vulkan.h:1037
type ShaderStageFlags uint32

// SamplerCreateFlags type as declared in vulkan/vulkan.h:1038
type SamplerCreateFlags uint32

// DescriptorSetLayoutCreateFlags type as declared in vulkan/vulkan.h:1039
type DescriptorSetLayoutCreateFlags uint32

// DescriptorPoolCreateFlags type as declared in vulkan/vulkan.h:1045
type DescriptorPoolCreateFlags uint32

// DescriptorPoolResetFlags type as declared in vulkan/vulkan.h:1046
type DescriptorPoolResetFlags uint32

// FramebufferCreateFlags type as declared in vulkan/vulkan.h:1047
type FramebufferCreateFlags uint32

// RenderPassCreateFlags type as declared in vulkan/vulkan.h:1048
type RenderPassCreateFlags uint32

// AttachmentDescriptionFlags type as declared in vulkan/vulkan.h:1054
type AttachmentDescriptionFlags uint32

// SubpassDescriptionFlags type as declared in vulkan/vulkan.h:1055
type SubpassDescriptionFlags uint32

// AccessFlags type as declared in vulkan/vulkan.h:1077
type AccessFlags uint32

// DependencyFlags type as declared in vulkan/vulkan.h:1083
type DependencyFlags uint32

// CommandPoolCreateFlags type as declared in vulkan/vulkan.h:1090
type CommandPoolCreateFlags uint32

// CommandPoolResetFlags type as declared in vulkan/vulkan.h:1096
type CommandPoolResetFlags uint32

// CommandBufferUsageFlags type as declared in vulkan/vulkan.h:1104
type CommandBufferUsageFlags uint32

// QueryControlFlags type as declared in vulkan/vulkan.h:1110
type QueryControlFlags uint32

// CommandBufferResetFlags type as declared in vulkan/vulkan.h:1116
type CommandBufferResetFlags uint32

// StencilFaceFlags type as declared in vulkan/vulkan.h:1124
type StencilFaceFlags uint32

// PFNAllocationFunction type as declared in vulkan/vulkan.h:1126
type PFNAllocationFunction func(PUserData unsafe.Pointer, Size uint, Alignment uint, AllocationScope SystemAllocationScope) unsafe.Pointer

// PFNReallocationFunction type as declared in vulkan/vulkan.h:1132
type PFNReallocationFunction func(PUserData unsafe.Pointer, POriginal unsafe.Pointer, Size uint, Alignment uint, AllocationScope SystemAllocationScope) unsafe.Pointer

// PFNFreeFunction type as declared in vulkan/vulkan.h:1139
type PFNFreeFunction func(PUserData unsafe.Pointer, PMemory unsafe.Pointer)

// PFNInternalAllocationNotification type as declared in vulkan/vulkan.h:1143
type PFNInternalAllocationNotification func(PUserData unsafe.Pointer, Size uint, AllocationType InternalAllocationType, AllocationScope SystemAllocationScope)

// PFNInternalFreeNotification type as declared in vulkan/vulkan.h:1149
type PFNInternalFreeNotification func(PUserData unsafe.Pointer, Size uint, AllocationType InternalAllocationType, AllocationScope SystemAllocationScope)

// PFNVoidFunction type as declared in vulkan/vulkan.h:1155
type PFNVoidFunction func()

// ApplicationInfo as declared in vulkan/vulkan.h:1165
type ApplicationInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	PApplicationName   string
	ApplicationVersion uint32
	PEngineName        string
	EngineVersion      uint32
	ApiVersion         uint32
	refb0af7378        *C.VkApplicationInfo
	allocsb0af7378     interface{}
}

// InstanceCreateInfo as declared in vulkan/vulkan.h:1176
type InstanceCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   InstanceCreateFlags
	PApplicationInfo        []ApplicationInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
	ref9b760798             *C.VkInstanceCreateInfo
	allocs9b760798          interface{}
}

// AllocationCallbacks as declared in vulkan/vulkan.h:1185
type AllocationCallbacks struct {
	PUserData             unsafe.Pointer
	PfnAllocation         PFNAllocationFunction
	PfnReallocation       PFNReallocationFunction
	PfnFree               PFNFreeFunction
	PfnInternalAllocation PFNInternalAllocationNotification
	PfnInternalFree       PFNInternalFreeNotification
	ref9638e01            *C.VkAllocationCallbacks
	allocs9638e01         interface{}
}

// PhysicalDeviceFeatures as declared in vulkan/vulkan.h:1243
type PhysicalDeviceFeatures struct {
	RobustBufferAccess                      Bool32
	FullDrawIndexUint32                     Bool32
	ImageCubeArray                          Bool32
	IndependentBlend                        Bool32
	GeometryShader                          Bool32
	TessellationShader                      Bool32
	SampleRateShading                       Bool32
	DualSrcBlend                            Bool32
	LogicOp                                 Bool32
	MultiDrawIndirect                       Bool32
	DrawIndirectFirstInstance               Bool32
	DepthClamp                              Bool32
	DepthBiasClamp                          Bool32
	FillModeNonSolid                        Bool32
	DepthBounds                             Bool32
	WideLines                               Bool32
	LargePoints                             Bool32
	AlphaToOne                              Bool32
	MultiViewport                           Bool32
	SamplerAnisotropy                       Bool32
	TextureCompressionETC2                  Bool32
	TextureCompressionASTC_LDR              Bool32
	TextureCompressionBC                    Bool32
	OcclusionQueryPrecise                   Bool32
	PipelineStatisticsQuery                 Bool32
	VertexPipelineStoresAndAtomics          Bool32
	FragmentStoresAndAtomics                Bool32
	ShaderTessellationAndGeometryPointSize  Bool32
	ShaderImageGatherExtended               Bool32
	ShaderStorageImageExtendedFormats       Bool32
	ShaderStorageImageMultisample           Bool32
	ShaderStorageImageReadWithoutFormat     Bool32
	ShaderStorageImageWriteWithoutFormat    Bool32
	ShaderUniformBufferArrayDynamicIndexing Bool32
	ShaderSampledImageArrayDynamicIndexing  Bool32
	ShaderStorageBufferArrayDynamicIndexing Bool32
	ShaderStorageImageArrayDynamicIndexing  Bool32
	ShaderClipDistance                      Bool32
	ShaderCullDistance                      Bool32
	ShaderFloat64                           Bool32
	ShaderInt64                             Bool32
	ShaderInt16                             Bool32
	ShaderResourceResidency                 Bool32
	ShaderResourceMinLod                    Bool32
	SparseBinding                           Bool32
	SparseResidencyBuffer                   Bool32
	SparseResidencyImage2D                  Bool32
	SparseResidencyImage3D                  Bool32
	SparseResidency2Samples                 Bool32
	SparseResidency4Samples                 Bool32
	SparseResidency8Samples                 Bool32
	SparseResidency16Samples                Bool32
	SparseResidencyAliased                  Bool32
	VariableMultisampleRate                 Bool32
	InheritedQueries                        Bool32
	reff97e405d                             *C.VkPhysicalDeviceFeatures
	allocsf97e405d                          interface{}
}

// FormatProperties as declared in vulkan/vulkan.h:1249
type FormatProperties struct {
	LinearTilingFeatures  FormatFeatureFlags
	OptimalTilingFeatures FormatFeatureFlags
	BufferFeatures        FormatFeatureFlags
	refc4b9937b           *C.VkFormatProperties
	allocsc4b9937b        interface{}
}

// Extent3D as declared in vulkan/vulkan.h:1255
type Extent3D struct {
	Width          uint32
	Height         uint32
	Depth          uint32
	reffbf6c42a    *C.VkExtent3D
	allocsfbf6c42a interface{}
}

// ImageFormatProperties as declared in vulkan/vulkan.h:1263
type ImageFormatProperties struct {
	MaxExtent       Extent3D
	MaxMipLevels    uint32
	MaxArrayLayers  uint32
	SampleCounts    SampleCountFlags
	MaxResourceSize DeviceSize
	ref4cfb2ea2     *C.VkImageFormatProperties
	allocs4cfb2ea2  interface{}
}

// PhysicalDeviceLimits as declared in vulkan/vulkan.h:1372
type PhysicalDeviceLimits struct {
	MaxImageDimension1D                             uint32
	MaxImageDimension2D                             uint32
	MaxImageDimension3D                             uint32
	MaxImageDimensionCube                           uint32
	MaxImageArrayLayers                             uint32
	MaxTexelBufferElements                          uint32
	MaxUniformBufferRange                           uint32
	MaxStorageBufferRange                           uint32
	MaxPushConstantsSize                            uint32
	MaxMemoryAllocationCount                        uint32
	MaxSamplerAllocationCount                       uint32
	BufferImageGranularity                          DeviceSize
	SparseAddressSpaceSize                          DeviceSize
	MaxBoundDescriptorSets                          uint32
	MaxPerStageDescriptorSamplers                   uint32
	MaxPerStageDescriptorUniformBuffers             uint32
	MaxPerStageDescriptorStorageBuffers             uint32
	MaxPerStageDescriptorSampledImages              uint32
	MaxPerStageDescriptorStorageImages              uint32
	MaxPerStageDescriptorInputAttachments           uint32
	MaxPerStageResources                            uint32
	MaxDescriptorSetSamplers                        uint32
	MaxDescriptorSetUniformBuffers                  uint32
	MaxDescriptorSetUniformBuffersDynamic           uint32
	MaxDescriptorSetStorageBuffers                  uint32
	MaxDescriptorSetStorageBuffersDynamic           uint32
	MaxDescriptorSetSampledImages                   uint32
	MaxDescriptorSetStorageImages                   uint32
	MaxDescriptorSetInputAttachments                uint32
	MaxVertexInputAttributes                        uint32
	MaxVertexInputBindings                          uint32
	MaxVertexInputAttributeOffset                   uint32
	MaxVertexInputBindingStride                     uint32
	MaxVertexOutputComponents                       uint32
	MaxTessellationGenerationLevel                  uint32
	MaxTessellationPatchSize                        uint32
	MaxTessellationControlPerVertexInputComponents  uint32
	MaxTessellationControlPerVertexOutputComponents uint32
	MaxTessellationControlPerPatchOutputComponents  uint32
	MaxTessellationControlTotalOutputComponents     uint32
	MaxTessellationEvaluationInputComponents        uint32
	MaxTessellationEvaluationOutputComponents       uint32
	MaxGeometryShaderInvocations                    uint32
	MaxGeometryInputComponents                      uint32
	MaxGeometryOutputComponents                     uint32
	MaxGeometryOutputVertices                       uint32
	MaxGeometryTotalOutputComponents                uint32
	MaxFragmentInputComponents                      uint32
	MaxFragmentOutputAttachments                    uint32
	MaxFragmentDualSrcAttachments                   uint32
	MaxFragmentCombinedOutputResources              uint32
	MaxComputeSharedMemorySize                      uint32
	MaxComputeWorkGroupCount                        [3]uint32
	MaxComputeWorkGroupInvocations                  uint32
	MaxComputeWorkGroupSize                         [3]uint32
	SubPixelPrecisionBits                           uint32
	SubTexelPrecisionBits                           uint32
	MipmapPrecisionBits                             uint32
	MaxDrawIndexedIndexValue                        uint32
	MaxDrawIndirectCount                            uint32
	MaxSamplerLodBias                               float32
	MaxSamplerAnisotropy                            float32
	MaxViewports                                    uint32
	MaxViewportDimensions                           [2]uint32
	ViewportBoundsRange                             [2]float32
	ViewportSubPixelBits                            uint32
	MinMemoryMapAlignment                           uint
	MinTexelBufferOffsetAlignment                   DeviceSize
	MinUniformBufferOffsetAlignment                 DeviceSize
	MinStorageBufferOffsetAlignment                 DeviceSize
	MinTexelOffset                                  int32
	MaxTexelOffset                                  uint32
	MinTexelGatherOffset                            int32
	MaxTexelGatherOffset                            uint32
	MinInterpolationOffset                          float32
	MaxInterpolationOffset                          float32
	SubPixelInterpolationOffsetBits                 uint32
	MaxFramebufferWidth                             uint32
	MaxFramebufferHeight                            uint32
	MaxFramebufferLayers                            uint32
	FramebufferColorSampleCounts                    SampleCountFlags
	FramebufferDepthSampleCounts                    SampleCountFlags
	FramebufferStencilSampleCounts                  SampleCountFlags
	FramebufferNoAttachmentsSampleCounts            SampleCountFlags
	MaxColorAttachments                             uint32
	SampledImageColorSampleCounts                   SampleCountFlags
	SampledImageIntegerSampleCounts                 SampleCountFlags
	SampledImageDepthSampleCounts                   SampleCountFlags
	SampledImageStencilSampleCounts                 SampleCountFlags
	StorageImageSampleCounts                        SampleCountFlags
	MaxSampleMaskWords                              uint32
	TimestampComputeAndGraphics                     Bool32
	TimestampPeriod                                 float32
	MaxClipDistances                                uint32
	MaxCullDistances                                uint32
	MaxCombinedClipAndCullDistances                 uint32
	DiscreteQueuePriorities                         uint32
	PointSizeRange                                  [2]float32
	LineWidthRange                                  [2]float32
	PointSizeGranularity                            float32
	LineWidthGranularity                            float32
	StrictLines                                     Bool32
	StandardSampleLocations                         Bool32
	OptimalBufferCopyOffsetAlignment                DeviceSize
	OptimalBufferCopyRowPitchAlignment              DeviceSize
	NonCoherentAtomSize                             DeviceSize
	ref7926795a                                     *C.VkPhysicalDeviceLimits
	allocs7926795a                                  interface{}
}

// PhysicalDeviceSparseProperties as declared in vulkan/vulkan.h:1380
type PhysicalDeviceSparseProperties struct {
	ResidencyStandard2DBlockShape            Bool32
	ResidencyStandard2DMultisampleBlockShape Bool32
	ResidencyStandard3DBlockShape            Bool32
	ResidencyAlignedMipSize                  Bool32
	ResidencyNonResidentStrict               Bool32
	ref6d7c11e6                              *C.VkPhysicalDeviceSparseProperties
	allocs6d7c11e6                           interface{}
}

// PhysicalDeviceProperties as declared in vulkan/vulkan.h:1392
type PhysicalDeviceProperties struct {
	ApiVersion        uint32
	DriverVersion     uint32
	VendorID          uint32
	DeviceID          uint32
	DeviceType        PhysicalDeviceType
	DeviceName        [256]byte
	PipelineCacheUUID [16]byte
	Limits            PhysicalDeviceLimits
	SparseProperties  PhysicalDeviceSparseProperties
	ref1080ca9d       *C.VkPhysicalDeviceProperties
	allocs1080ca9d    interface{}
}

// QueueFamilyProperties as declared in vulkan/vulkan.h:1399
type QueueFamilyProperties struct {
	QueueFlags                  QueueFlags
	QueueCount                  uint32
	TimestampValidBits          uint32
	MinImageTransferGranularity Extent3D
	refd538c446                 *C.VkQueueFamilyProperties
	allocsd538c446              interface{}
}

// MemoryType as declared in vulkan/vulkan.h:1404
type MemoryType struct {
	PropertyFlags  MemoryPropertyFlags
	HeapIndex      uint32
	ref2f46e01d    *C.VkMemoryType
	allocs2f46e01d interface{}
}

// MemoryHeap as declared in vulkan/vulkan.h:1409
type MemoryHeap struct {
	Size           DeviceSize
	Flags          MemoryHeapFlags
	ref1eb195d5    *C.VkMemoryHeap
	allocs1eb195d5 interface{}
}

// PhysicalDeviceMemoryProperties as declared in vulkan/vulkan.h:1416
type PhysicalDeviceMemoryProperties struct {
	MemoryTypeCount uint32
	MemoryTypes     [32]MemoryType
	MemoryHeapCount uint32
	MemoryHeaps     [16]MemoryHeap
	ref3aabb5fd     *C.VkPhysicalDeviceMemoryProperties
	allocs3aabb5fd  interface{}
}

// DeviceQueueCreateInfo as declared in vulkan/vulkan.h:1425
type DeviceQueueCreateInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            DeviceQueueCreateFlags
	QueueFamilyIndex uint32
	QueueCount       uint32
	PQueuePriorities []float32
	ref6087b30d      *C.VkDeviceQueueCreateInfo
	allocs6087b30d   interface{}
}

// DeviceCreateInfo as declared in vulkan/vulkan.h:1438
type DeviceCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   DeviceCreateFlags
	QueueCreateInfoCount    uint32
	PQueueCreateInfos       []DeviceQueueCreateInfo
	EnabledLayerCount       uint32
	PpEnabledLayerNames     []string
	EnabledExtensionCount   uint32
	PpEnabledExtensionNames []string
	PEnabledFeatures        []PhysicalDeviceFeatures
	refc0d8b997             *C.VkDeviceCreateInfo
	allocsc0d8b997          interface{}
}

// ExtensionProperties as declared in vulkan/vulkan.h:1443
type ExtensionProperties struct {
	ExtensionName  [256]byte
	SpecVersion    uint32
	ref2f001956    *C.VkExtensionProperties
	allocs2f001956 interface{}
}

// LayerProperties as declared in vulkan/vulkan.h:1450
type LayerProperties struct {
	LayerName             [256]byte
	SpecVersion           uint32
	ImplementationVersion uint32
	Description           [256]byte
	refd9407ce7           *C.VkLayerProperties
	allocsd9407ce7        interface{}
}

// SubmitInfo as declared in vulkan/vulkan.h:1462
type SubmitInfo struct {
	SType                StructureType
	PNext                unsafe.Pointer
	WaitSemaphoreCount   uint32
	PWaitSemaphores      []Semaphore
	PWaitDstStageMask    []PipelineStageFlags
	CommandBufferCount   uint32
	PCommandBuffers      []CommandBuffer
	SignalSemaphoreCount uint32
	PSignalSemaphores    []Semaphore
	ref22884025          *C.VkSubmitInfo
	allocs22884025       interface{}
}

// MemoryAllocateInfo as declared in vulkan/vulkan.h:1469
type MemoryAllocateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	AllocationSize  DeviceSize
	MemoryTypeIndex uint32
	ref31032b       *C.VkMemoryAllocateInfo
	allocs31032b    interface{}
}

// MappedMemoryRange as declared in vulkan/vulkan.h:1477
type MappedMemoryRange struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Memory         DeviceMemory
	Offset         DeviceSize
	Size           DeviceSize
	ref42a37320    *C.VkMappedMemoryRange
	allocs42a37320 interface{}
}

// MemoryRequirements as declared in vulkan/vulkan.h:1483
type MemoryRequirements struct {
	Size           DeviceSize
	Alignment      DeviceSize
	MemoryTypeBits uint32
	ref5259fc6b    *C.VkMemoryRequirements
	allocs5259fc6b interface{}
}

// SparseImageFormatProperties as declared in vulkan/vulkan.h:1489
type SparseImageFormatProperties struct {
	AspectMask       ImageAspectFlags
	ImageGranularity Extent3D
	Flags            SparseImageFormatFlags
	ref2c12cf44      *C.VkSparseImageFormatProperties
	allocs2c12cf44   interface{}
}

// SparseImageMemoryRequirements as declared in vulkan/vulkan.h:1497
type SparseImageMemoryRequirements struct {
	FormatProperties     SparseImageFormatProperties
	ImageMipTailFirstLod uint32
	ImageMipTailSize     DeviceSize
	ImageMipTailOffset   DeviceSize
	ImageMipTailStride   DeviceSize
	ref685a2323          *C.VkSparseImageMemoryRequirements
	allocs685a2323       interface{}
}

// SparseMemoryBind as declared in vulkan/vulkan.h:1505
type SparseMemoryBind struct {
	ResourceOffset DeviceSize
	Size           DeviceSize
	Memory         DeviceMemory
	MemoryOffset   DeviceSize
	Flags          SparseMemoryBindFlags
	ref5bf418e8    *C.VkSparseMemoryBind
	allocs5bf418e8 interface{}
}

// SparseBufferMemoryBindInfo as declared in vulkan/vulkan.h:1511
type SparseBufferMemoryBindInfo struct {
	Buffer         Buffer
	BindCount      uint32
	PBinds         []SparseMemoryBind
	refebcaf40c    *C.VkSparseBufferMemoryBindInfo
	allocsebcaf40c interface{}
}

// SparseImageOpaqueMemoryBindInfo as declared in vulkan/vulkan.h:1517
type SparseImageOpaqueMemoryBindInfo struct {
	Image          Image
	BindCount      uint32
	PBinds         []SparseMemoryBind
	reffb1b3d56    *C.VkSparseImageOpaqueMemoryBindInfo
	allocsfb1b3d56 interface{}
}

// ImageSubresource as declared in vulkan/vulkan.h:1523
type ImageSubresource struct {
	AspectMask     ImageAspectFlags
	MipLevel       uint32
	ArrayLayer     uint32
	reffeaa0d8a    *C.VkImageSubresource
	allocsfeaa0d8a interface{}
}

// Offset3D as declared in vulkan/vulkan.h:1529
type Offset3D struct {
	X              int32
	Y              int32
	Z              int32
	ref2b6879c2    *C.VkOffset3D
	allocs2b6879c2 interface{}
}

// SparseImageMemoryBind as declared in vulkan/vulkan.h:1538
type SparseImageMemoryBind struct {
	Subresource    ImageSubresource
	Offset         Offset3D
	Extent         Extent3D
	Memory         DeviceMemory
	MemoryOffset   DeviceSize
	Flags          SparseMemoryBindFlags
	ref41b516d7    *C.VkSparseImageMemoryBind
	allocs41b516d7 interface{}
}

// SparseImageMemoryBindInfo as declared in vulkan/vulkan.h:1544
type SparseImageMemoryBindInfo struct {
	Image          Image
	BindCount      uint32
	PBinds         []SparseImageMemoryBind
	ref50faeb70    *C.VkSparseImageMemoryBindInfo
	allocs50faeb70 interface{}
}

// BindSparseInfo as declared in vulkan/vulkan.h:1559
type BindSparseInfo struct {
	SType                StructureType
	PNext                unsafe.Pointer
	WaitSemaphoreCount   uint32
	PWaitSemaphores      []Semaphore
	BufferBindCount      uint32
	PBufferBinds         []SparseBufferMemoryBindInfo
	ImageOpaqueBindCount uint32
	PImageOpaqueBinds    []SparseImageOpaqueMemoryBindInfo
	ImageBindCount       uint32
	PImageBinds          []SparseImageMemoryBindInfo
	SignalSemaphoreCount uint32
	PSignalSemaphores    []Semaphore
	refb0cbe910          *C.VkBindSparseInfo
	allocsb0cbe910       interface{}
}

// FenceCreateInfo as declared in vulkan/vulkan.h:1565
type FenceCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          FenceCreateFlags
	refb8ff4840    *C.VkFenceCreateInfo
	allocsb8ff4840 interface{}
}

// SemaphoreCreateInfo as declared in vulkan/vulkan.h:1571
type SemaphoreCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          SemaphoreCreateFlags
	reff130cd2b    *C.VkSemaphoreCreateInfo
	allocsf130cd2b interface{}
}

// EventCreateInfo as declared in vulkan/vulkan.h:1577
type EventCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          EventCreateFlags
	refa54f9ec8    *C.VkEventCreateInfo
	allocsa54f9ec8 interface{}
}

// QueryPoolCreateInfo as declared in vulkan/vulkan.h:1586
type QueryPoolCreateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	Flags              QueryPoolCreateFlags
	QueryType          QueryType
	QueryCount         uint32
	PipelineStatistics QueryPipelineStatisticFlags
	ref85dfcd4a        *C.VkQueryPoolCreateInfo
	allocs85dfcd4a     interface{}
}

// BufferCreateInfo as declared in vulkan/vulkan.h:1597
type BufferCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 BufferCreateFlags
	Size                  DeviceSize
	Usage                 BufferUsageFlags
	SharingMode           SharingMode
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	reffe19d2cd           *C.VkBufferCreateInfo
	allocsfe19d2cd        interface{}
}

// BufferViewCreateInfo as declared in vulkan/vulkan.h:1607
type BufferViewCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          BufferViewCreateFlags
	Buffer         Buffer
	Format         Format
	Offset         DeviceSize
	_range         DeviceSize
	ref49b97027    *C.VkBufferViewCreateInfo
	allocs49b97027 interface{}
}

// ImageCreateInfo as declared in vulkan/vulkan.h:1625
type ImageCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 ImageCreateFlags
	ImageType             ImageType
	Format                Format
	Extent                Extent3D
	MipLevels             uint32
	ArrayLayers           uint32
	Samples               SampleCountFlagBits
	Tiling                ImageTiling
	Usage                 ImageUsageFlags
	SharingMode           SharingMode
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	InitialLayout         ImageLayout
	reffb587ba1           *C.VkImageCreateInfo
	allocsfb587ba1        interface{}
}

// SubresourceLayout as declared in vulkan/vulkan.h:1633
type SubresourceLayout struct {
	Offset         DeviceSize
	Size           DeviceSize
	RowPitch       DeviceSize
	ArrayPitch     DeviceSize
	DepthPitch     DeviceSize
	ref182612ad    *C.VkSubresourceLayout
	allocs182612ad interface{}
}

// ComponentMapping as declared in vulkan/vulkan.h:1640
type ComponentMapping struct {
	R              ComponentSwizzle
	G              ComponentSwizzle
	B              ComponentSwizzle
	A              ComponentSwizzle
	ref63d3d563    *C.VkComponentMapping
	allocs63d3d563 interface{}
}

// ImageSubresourceRange as declared in vulkan/vulkan.h:1648
type ImageSubresourceRange struct {
	AspectMask     ImageAspectFlags
	BaseMipLevel   uint32
	LevelCount     uint32
	BaseArrayLayer uint32
	LayerCount     uint32
	ref5aa1126     *C.VkImageSubresourceRange
	allocs5aa1126  interface{}
}

// ImageViewCreateInfo as declared in vulkan/vulkan.h:1659
type ImageViewCreateInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            ImageViewCreateFlags
	Image            Image
	ViewType         ImageViewType
	Format           Format
	Components       ComponentMapping
	SubresourceRange ImageSubresourceRange
	ref77e8d4b8      *C.VkImageViewCreateInfo
	allocs77e8d4b8   interface{}
}

// ShaderModuleCreateInfo as declared in vulkan/vulkan.h:1667
type ShaderModuleCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          ShaderModuleCreateFlags
	CodeSize       uint
	PCode          []uint32
	refc663d23e    *C.VkShaderModuleCreateInfo
	allocsc663d23e interface{}
}

// PipelineCacheCreateInfo as declared in vulkan/vulkan.h:1675
type PipelineCacheCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           PipelineCacheCreateFlags
	InitialDataSize uint
	PInitialData    unsafe.Pointer
	reff11e7dd1     *C.VkPipelineCacheCreateInfo
	allocsf11e7dd1  interface{}
}

// SpecializationMapEntry as declared in vulkan/vulkan.h:1681
type SpecializationMapEntry struct {
	ConstantID     uint32
	Offset         uint32
	Size           uint
	ref2fd815d1    *C.VkSpecializationMapEntry
	allocs2fd815d1 interface{}
}

// SpecializationInfo as declared in vulkan/vulkan.h:1688
type SpecializationInfo struct {
	MapEntryCount  uint32
	PMapEntries    []SpecializationMapEntry
	DataSize       uint
	PData          unsafe.Pointer
	ref6bc395a3    *C.VkSpecializationInfo
	allocs6bc395a3 interface{}
}

// PipelineShaderStageCreateInfo as declared in vulkan/vulkan.h:1698
type PipelineShaderStageCreateInfo struct {
	SType               StructureType
	PNext               unsafe.Pointer
	Flags               PipelineShaderStageCreateFlags
	Stage               ShaderStageFlagBits
	Module              ShaderModule
	PName               string
	PSpecializationInfo []SpecializationInfo
	ref50ba8b60         *C.VkPipelineShaderStageCreateInfo
	allocs50ba8b60      interface{}
}

// VertexInputBindingDescription as declared in vulkan/vulkan.h:1704
type VertexInputBindingDescription struct {
	Binding        uint32
	Stride         uint32
	InputRate      VertexInputRate
	ref5c9d8c23    *C.VkVertexInputBindingDescription
	allocs5c9d8c23 interface{}
}

// VertexInputAttributeDescription as declared in vulkan/vulkan.h:1711
type VertexInputAttributeDescription struct {
	Location       uint32
	Binding        uint32
	Format         Format
	Offset         uint32
	refdc4635ff    *C.VkVertexInputAttributeDescription
	allocsdc4635ff interface{}
}

// PipelineVertexInputStateCreateInfo as declared in vulkan/vulkan.h:1721
type PipelineVertexInputStateCreateInfo struct {
	SType                           StructureType
	PNext                           unsafe.Pointer
	Flags                           PipelineVertexInputStateCreateFlags
	VertexBindingDescriptionCount   uint32
	PVertexBindingDescriptions      []VertexInputBindingDescription
	VertexAttributeDescriptionCount uint32
	PVertexAttributeDescriptions    []VertexInputAttributeDescription
	ref5fe4aa50                     *C.VkPipelineVertexInputStateCreateInfo
	allocs5fe4aa50                  interface{}
}

// PipelineInputAssemblyStateCreateInfo as declared in vulkan/vulkan.h:1729
type PipelineInputAssemblyStateCreateInfo struct {
	SType                  StructureType
	PNext                  unsafe.Pointer
	Flags                  PipelineInputAssemblyStateCreateFlags
	Topology               PrimitiveTopology
	PrimitiveRestartEnable Bool32
	ref22e1691d            *C.VkPipelineInputAssemblyStateCreateInfo
	allocs22e1691d         interface{}
}

// PipelineTessellationStateCreateInfo as declared in vulkan/vulkan.h:1736
type PipelineTessellationStateCreateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	Flags              PipelineTessellationStateCreateFlags
	PatchControlPoints uint32
	ref4ef3997a        *C.VkPipelineTessellationStateCreateInfo
	allocs4ef3997a     interface{}
}

// Viewport as declared in vulkan/vulkan.h:1745
type Viewport struct {
	X              float32
	Y              float32
	Width          float32
	Height         float32
	MinDepth       float32
	MaxDepth       float32
	ref75cf5291    *C.VkViewport
	allocs75cf5291 interface{}
}

// Offset2D as declared in vulkan/vulkan.h:1750
type Offset2D struct {
	X              int32
	Y              int32
	ref32734883    *C.VkOffset2D
	allocs32734883 interface{}
}

// Extent2D as declared in vulkan/vulkan.h:1755
type Extent2D struct {
	Width          uint32
	Height         uint32
	refe2edf56b    *C.VkExtent2D
	allocse2edf56b interface{}
}

// Rect2D as declared in vulkan/vulkan.h:1760
type Rect2D struct {
	Offset         Offset2D
	Extent         Extent2D
	ref89e4256f    *C.VkRect2D
	allocs89e4256f interface{}
}

// PipelineViewportStateCreateInfo as declared in vulkan/vulkan.h:1770
type PipelineViewportStateCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          PipelineViewportStateCreateFlags
	ViewportCount  uint32
	PViewports     []Viewport
	ScissorCount   uint32
	PScissors      []Rect2D
	refc4705791    *C.VkPipelineViewportStateCreateInfo
	allocsc4705791 interface{}
}

// PipelineRasterizationStateCreateInfo as declared in vulkan/vulkan.h:1786
type PipelineRasterizationStateCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   PipelineRasterizationStateCreateFlags
	DepthClampEnable        Bool32
	RasterizerDiscardEnable Bool32
	PolygonMode             PolygonMode
	CullMode                CullModeFlags
	FrontFace               FrontFace
	DepthBiasEnable         Bool32
	DepthBiasConstantFactor float32
	DepthBiasClamp          float32
	DepthBiasSlopeFactor    float32
	LineWidth               float32
	ref48cb9fad             *C.VkPipelineRasterizationStateCreateInfo
	allocs48cb9fad          interface{}
}

// PipelineMultisampleStateCreateInfo as declared in vulkan/vulkan.h:1798
type PipelineMultisampleStateCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 PipelineMultisampleStateCreateFlags
	RasterizationSamples  SampleCountFlagBits
	SampleShadingEnable   Bool32
	MinSampleShading      float32
	PSampleMask           []SampleMask
	AlphaToCoverageEnable Bool32
	AlphaToOneEnable      Bool32
	refb6538bfb           *C.VkPipelineMultisampleStateCreateInfo
	allocsb6538bfb        interface{}
}

// StencilOpState as declared in vulkan/vulkan.h:1808
type StencilOpState struct {
	FailOp         StencilOp
	PassOp         StencilOp
	DepthFailOp    StencilOp
	CompareOp      CompareOp
	CompareMask    uint32
	WriteMask      uint32
	Reference      uint32
	ref28886871    *C.VkStencilOpState
	allocs28886871 interface{}
}

// PipelineDepthStencilStateCreateInfo as declared in vulkan/vulkan.h:1823
type PipelineDepthStencilStateCreateInfo struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 PipelineDepthStencilStateCreateFlags
	DepthTestEnable       Bool32
	DepthWriteEnable      Bool32
	DepthCompareOp        CompareOp
	DepthBoundsTestEnable Bool32
	StencilTestEnable     Bool32
	Front                 StencilOpState
	Back                  StencilOpState
	MinDepthBounds        float32
	MaxDepthBounds        float32
	refeabfcf1            *C.VkPipelineDepthStencilStateCreateInfo
	allocseabfcf1         interface{}
}

// PipelineColorBlendAttachmentState as declared in vulkan/vulkan.h:1834
type PipelineColorBlendAttachmentState struct {
	BlendEnable         Bool32
	SrcColorBlendFactor BlendFactor
	DstColorBlendFactor BlendFactor
	ColorBlendOp        BlendOp
	SrcAlphaBlendFactor BlendFactor
	DstAlphaBlendFactor BlendFactor
	AlphaBlendOp        BlendOp
	ColorWriteMask      ColorComponentFlags
	ref9e889477         *C.VkPipelineColorBlendAttachmentState
	allocs9e889477      interface{}
}

// PipelineColorBlendStateCreateInfo as declared in vulkan/vulkan.h:1845
type PipelineColorBlendStateCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           PipelineColorBlendStateCreateFlags
	LogicOpEnable   Bool32
	LogicOp         LogicOp
	AttachmentCount uint32
	PAttachments    []PipelineColorBlendAttachmentState
	BlendConstants  [4]float32
	ref2a9b490b     *C.VkPipelineColorBlendStateCreateInfo
	allocs2a9b490b  interface{}
}

// PipelineDynamicStateCreateInfo as declared in vulkan/vulkan.h:1853
type PipelineDynamicStateCreateInfo struct {
	SType             StructureType
	PNext             unsafe.Pointer
	Flags             PipelineDynamicStateCreateFlags
	DynamicStateCount uint32
	PDynamicStates    []DynamicState
	ref246d7bc8       *C.VkPipelineDynamicStateCreateInfo
	allocs246d7bc8    interface{}
}

// GraphicsPipelineCreateInfo as declared in vulkan/vulkan.h:1875
type GraphicsPipelineCreateInfo struct {
	SType               StructureType
	PNext               unsafe.Pointer
	Flags               PipelineCreateFlags
	StageCount          uint32
	PStages             []PipelineShaderStageCreateInfo
	PVertexInputState   []PipelineVertexInputStateCreateInfo
	PInputAssemblyState []PipelineInputAssemblyStateCreateInfo
	PTessellationState  []PipelineTessellationStateCreateInfo
	PViewportState      []PipelineViewportStateCreateInfo
	PRasterizationState []PipelineRasterizationStateCreateInfo
	PMultisampleState   []PipelineMultisampleStateCreateInfo
	PDepthStencilState  []PipelineDepthStencilStateCreateInfo
	PColorBlendState    []PipelineColorBlendStateCreateInfo
	PDynamicState       []PipelineDynamicStateCreateInfo
	Layout              PipelineLayout
	RenderPass          RenderPass
	Subpass             uint32
	BasePipelineHandle  Pipeline
	BasePipelineIndex   int32
	ref178f88b6         *C.VkGraphicsPipelineCreateInfo
	allocs178f88b6      interface{}
}

// ComputePipelineCreateInfo as declared in vulkan/vulkan.h:1885
type ComputePipelineCreateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	Flags              PipelineCreateFlags
	Stage              PipelineShaderStageCreateInfo
	Layout             PipelineLayout
	BasePipelineHandle Pipeline
	BasePipelineIndex  int32
	ref77823220        *C.VkComputePipelineCreateInfo
	allocs77823220     interface{}
}

// PushConstantRange as declared in vulkan/vulkan.h:1891
type PushConstantRange struct {
	StageFlags     ShaderStageFlags
	Offset         uint32
	Size           uint32
	ref6f025856    *C.VkPushConstantRange
	allocs6f025856 interface{}
}

// PipelineLayoutCreateInfo as declared in vulkan/vulkan.h:1901
type PipelineLayoutCreateInfo struct {
	SType                  StructureType
	PNext                  unsafe.Pointer
	Flags                  PipelineLayoutCreateFlags
	SetLayoutCount         uint32
	PSetLayouts            []DescriptorSetLayout
	PushConstantRangeCount uint32
	PPushConstantRanges    []PushConstantRange
	ref64cc4eed            *C.VkPipelineLayoutCreateInfo
	allocs64cc4eed         interface{}
}

// SamplerCreateInfo as declared in vulkan/vulkan.h:1922
type SamplerCreateInfo struct {
	SType                   StructureType
	PNext                   unsafe.Pointer
	Flags                   SamplerCreateFlags
	MagFilter               Filter
	MinFilter               Filter
	MipmapMode              SamplerMipmapMode
	AddressModeU            SamplerAddressMode
	AddressModeV            SamplerAddressMode
	AddressModeW            SamplerAddressMode
	MipLodBias              float32
	AnisotropyEnable        Bool32
	MaxAnisotropy           float32
	CompareEnable           Bool32
	CompareOp               CompareOp
	MinLod                  float32
	MaxLod                  float32
	BorderColor             BorderColor
	UnnormalizedCoordinates Bool32
	refce034abf             *C.VkSamplerCreateInfo
	allocsce034abf          interface{}
}

// DescriptorSetLayoutBinding as declared in vulkan/vulkan.h:1930
type DescriptorSetLayoutBinding struct {
	Binding            uint32
	DescriptorType     DescriptorType
	DescriptorCount    uint32
	StageFlags         ShaderStageFlags
	PImmutableSamplers []Sampler
	ref8b50b4ec        *C.VkDescriptorSetLayoutBinding
	allocs8b50b4ec     interface{}
}

// DescriptorSetLayoutCreateInfo as declared in vulkan/vulkan.h:1938
type DescriptorSetLayoutCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DescriptorSetLayoutCreateFlags
	BindingCount   uint32
	PBindings      []DescriptorSetLayoutBinding
	ref5ee8e0ed    *C.VkDescriptorSetLayoutCreateInfo
	allocs5ee8e0ed interface{}
}

// DescriptorPoolSize as declared in vulkan/vulkan.h:1943
type DescriptorPoolSize struct {
	_type           DescriptorType
	DescriptorCount uint32
	refe15137da     *C.VkDescriptorPoolSize
	allocse15137da  interface{}
}

// DescriptorPoolCreateInfo as declared in vulkan/vulkan.h:1952
type DescriptorPoolCreateInfo struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DescriptorPoolCreateFlags
	MaxSets        uint32
	PoolSizeCount  uint32
	PPoolSizes     []DescriptorPoolSize
	ref19868463    *C.VkDescriptorPoolCreateInfo
	allocs19868463 interface{}
}

// DescriptorSetAllocateInfo as declared in vulkan/vulkan.h:1960
type DescriptorSetAllocateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	DescriptorPool     DescriptorPool
	DescriptorSetCount uint32
	PSetLayouts        []DescriptorSetLayout
	ref2dd6cc22        *C.VkDescriptorSetAllocateInfo
	allocs2dd6cc22     interface{}
}

// DescriptorImageInfo as declared in vulkan/vulkan.h:1966
type DescriptorImageInfo struct {
	Sampler        Sampler
	ImageView      ImageView
	ImageLayout    ImageLayout
	refaf073b07    *C.VkDescriptorImageInfo
	allocsaf073b07 interface{}
}

// DescriptorBufferInfo as declared in vulkan/vulkan.h:1972
type DescriptorBufferInfo struct {
	Buffer         Buffer
	Offset         DeviceSize
	_range         DeviceSize
	refe64bec0e    *C.VkDescriptorBufferInfo
	allocse64bec0e interface{}
}

// WriteDescriptorSet as declared in vulkan/vulkan.h:1985
type WriteDescriptorSet struct {
	SType            StructureType
	PNext            unsafe.Pointer
	DstSet           DescriptorSet
	DstBinding       uint32
	DstArrayElement  uint32
	DescriptorCount  uint32
	DescriptorType   DescriptorType
	PImageInfo       []DescriptorImageInfo
	PBufferInfo      []DescriptorBufferInfo
	PTexelBufferView []BufferView
	ref3cec3f3f      *C.VkWriteDescriptorSet
	allocs3cec3f3f   interface{}
}

// CopyDescriptorSet as declared in vulkan/vulkan.h:1997
type CopyDescriptorSet struct {
	SType           StructureType
	PNext           unsafe.Pointer
	SrcSet          DescriptorSet
	SrcBinding      uint32
	SrcArrayElement uint32
	DstSet          DescriptorSet
	DstBinding      uint32
	DstArrayElement uint32
	DescriptorCount uint32
	reffe237a3a     *C.VkCopyDescriptorSet
	allocsfe237a3a  interface{}
}

// FramebufferCreateInfo as declared in vulkan/vulkan.h:2009
type FramebufferCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           FramebufferCreateFlags
	RenderPass      RenderPass
	AttachmentCount uint32
	PAttachments    []ImageView
	Width           uint32
	Height          uint32
	Layers          uint32
	refa3ad85cc     *C.VkFramebufferCreateInfo
	allocsa3ad85cc  interface{}
}

// AttachmentDescription as declared in vulkan/vulkan.h:2021
type AttachmentDescription struct {
	Flags          AttachmentDescriptionFlags
	Format         Format
	Samples        SampleCountFlagBits
	LoadOp         AttachmentLoadOp
	StoreOp        AttachmentStoreOp
	StencilLoadOp  AttachmentLoadOp
	StencilStoreOp AttachmentStoreOp
	InitialLayout  ImageLayout
	FinalLayout    ImageLayout
	refa5d685fc    *C.VkAttachmentDescription
	allocsa5d685fc interface{}
}

// AttachmentReference as declared in vulkan/vulkan.h:2026
type AttachmentReference struct {
	Attachment     uint32
	Layout         ImageLayout
	refef4776de    *C.VkAttachmentReference
	allocsef4776de interface{}
}

// SubpassDescription as declared in vulkan/vulkan.h:2039
type SubpassDescription struct {
	Flags                   SubpassDescriptionFlags
	PipelineBindPoint       PipelineBindPoint
	InputAttachmentCount    uint32
	PInputAttachments       []AttachmentReference
	ColorAttachmentCount    uint32
	PColorAttachments       []AttachmentReference
	PResolveAttachments     []AttachmentReference
	PDepthStencilAttachment []AttachmentReference
	PreserveAttachmentCount uint32
	PPreserveAttachments    []uint32
	refc7bfeda              *C.VkSubpassDescription
	allocsc7bfeda           interface{}
}

// SubpassDependency as declared in vulkan/vulkan.h:2049
type SubpassDependency struct {
	SrcSubpass      uint32
	DstSubpass      uint32
	SrcStageMask    PipelineStageFlags
	DstStageMask    PipelineStageFlags
	SrcAccessMask   AccessFlags
	DstAccessMask   AccessFlags
	DependencyFlags DependencyFlags
	refdb197adb     *C.VkSubpassDependency
	allocsdb197adb  interface{}
}

// RenderPassCreateInfo as declared in vulkan/vulkan.h:2061
type RenderPassCreateInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           RenderPassCreateFlags
	AttachmentCount uint32
	PAttachments    []AttachmentDescription
	SubpassCount    uint32
	PSubpasses      []SubpassDescription
	DependencyCount uint32
	PDependencies   []SubpassDependency
	ref886d7d86     *C.VkRenderPassCreateInfo
	allocs886d7d86  interface{}
}

// CommandPoolCreateInfo as declared in vulkan/vulkan.h:2068
type CommandPoolCreateInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            CommandPoolCreateFlags
	QueueFamilyIndex uint32
	ref73550de0      *C.VkCommandPoolCreateInfo
	allocs73550de0   interface{}
}

// CommandBufferAllocateInfo as declared in vulkan/vulkan.h:2076
type CommandBufferAllocateInfo struct {
	SType              StructureType
	PNext              unsafe.Pointer
	CommandPool        CommandPool
	Level              CommandBufferLevel
	CommandBufferCount uint32
	refd1a0a7c8        *C.VkCommandBufferAllocateInfo
	allocsd1a0a7c8     interface{}
}

// CommandBufferInheritanceInfo as declared in vulkan/vulkan.h:2087
type CommandBufferInheritanceInfo struct {
	SType                StructureType
	PNext                unsafe.Pointer
	RenderPass           RenderPass
	Subpass              uint32
	Framebuffer          Framebuffer
	OcclusionQueryEnable Bool32
	QueryFlags           QueryControlFlags
	PipelineStatistics   QueryPipelineStatisticFlags
	ref737f8019          *C.VkCommandBufferInheritanceInfo
	allocs737f8019       interface{}
}

// CommandBufferBeginInfo as declared in vulkan/vulkan.h:2094
type CommandBufferBeginInfo struct {
	SType            StructureType
	PNext            unsafe.Pointer
	Flags            CommandBufferUsageFlags
	PInheritanceInfo []CommandBufferInheritanceInfo
	ref266762df      *C.VkCommandBufferBeginInfo
	allocs266762df   interface{}
}

// BufferCopy as declared in vulkan/vulkan.h:2100
type BufferCopy struct {
	SrcOffset      DeviceSize
	DstOffset      DeviceSize
	Size           DeviceSize
	ref12184ffd    *C.VkBufferCopy
	allocs12184ffd interface{}
}

// ImageSubresourceLayers as declared in vulkan/vulkan.h:2107
type ImageSubresourceLayers struct {
	AspectMask     ImageAspectFlags
	MipLevel       uint32
	BaseArrayLayer uint32
	LayerCount     uint32
	ref3b13bcd2    *C.VkImageSubresourceLayers
	allocs3b13bcd2 interface{}
}

// ImageCopy as declared in vulkan/vulkan.h:2115
type ImageCopy struct {
	SrcSubresource ImageSubresourceLayers
	SrcOffset      Offset3D
	DstSubresource ImageSubresourceLayers
	DstOffset      Offset3D
	Extent         Extent3D
	ref4e7a1214    *C.VkImageCopy
	allocs4e7a1214 interface{}
}

// ImageBlit as declared in vulkan/vulkan.h:2122
type ImageBlit struct {
	SrcSubresource ImageSubresourceLayers
	SrcOffsets     [2]Offset3D
	DstSubresource ImageSubresourceLayers
	DstOffsets     [2]Offset3D
	ref11311e8d    *C.VkImageBlit
	allocs11311e8d interface{}
}

// BufferImageCopy as declared in vulkan/vulkan.h:2131
type BufferImageCopy struct {
	BufferOffset      DeviceSize
	BufferRowLength   uint32
	BufferImageHeight uint32
	ImageSubresource  ImageSubresourceLayers
	ImageOffset       Offset3D
	ImageExtent       Extent3D
	ref6d50e36e       *C.VkBufferImageCopy
	allocs6d50e36e    interface{}
}

// ClearColorValue as declared in vulkan/vulkan.h:2137
const sizeofClearColorValue = unsafe.Sizeof(C.VkClearColorValue{})

type ClearColorValue [sizeofClearColorValue]byte

// ClearDepthStencilValue as declared in vulkan/vulkan.h:2142
type ClearDepthStencilValue struct {
	Depth          float32
	Stencil        uint32
	refa7d07c03    *C.VkClearDepthStencilValue
	allocsa7d07c03 interface{}
}

// ClearValue as declared in vulkan/vulkan.h:2147
const sizeofClearValue = unsafe.Sizeof(C.VkClearValue{})

type ClearValue [sizeofClearValue]byte

// ClearAttachment as declared in vulkan/vulkan.h:2153
type ClearAttachment struct {
	AspectMask      ImageAspectFlags
	ColorAttachment uint32
	ClearValue      ClearValue
	refe9150303     *C.VkClearAttachment
	allocse9150303  interface{}
}

// ClearRect as declared in vulkan/vulkan.h:2159
type ClearRect struct {
	Rect           Rect2D
	BaseArrayLayer uint32
	LayerCount     uint32
	ref1d449c8b    *C.VkClearRect
	allocs1d449c8b interface{}
}

// ImageResolve as declared in vulkan/vulkan.h:2167
type ImageResolve struct {
	SrcSubresource ImageSubresourceLayers
	SrcOffset      Offset3D
	DstSubresource ImageSubresourceLayers
	DstOffset      Offset3D
	Extent         Extent3D
	ref7bda856d    *C.VkImageResolve
	allocs7bda856d interface{}
}

// MemoryBarrier as declared in vulkan/vulkan.h:2174
type MemoryBarrier struct {
	SType          StructureType
	PNext          unsafe.Pointer
	SrcAccessMask  AccessFlags
	DstAccessMask  AccessFlags
	ref977c944e    *C.VkMemoryBarrier
	allocs977c944e interface{}
}

// BufferMemoryBarrier as declared in vulkan/vulkan.h:2186
type BufferMemoryBarrier struct {
	SType               StructureType
	PNext               unsafe.Pointer
	SrcAccessMask       AccessFlags
	DstAccessMask       AccessFlags
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Buffer              Buffer
	Offset              DeviceSize
	Size                DeviceSize
	refeaf4700b         *C.VkBufferMemoryBarrier
	allocseaf4700b      interface{}
}

// ImageMemoryBarrier as declared in vulkan/vulkan.h:2199
type ImageMemoryBarrier struct {
	SType               StructureType
	PNext               unsafe.Pointer
	SrcAccessMask       AccessFlags
	DstAccessMask       AccessFlags
	OldLayout           ImageLayout
	NewLayout           ImageLayout
	SrcQueueFamilyIndex uint32
	DstQueueFamilyIndex uint32
	Image               Image
	SubresourceRange    ImageSubresourceRange
	refd52734ec         *C.VkImageMemoryBarrier
	allocsd52734ec      interface{}
}

// RenderPassBeginInfo as declared in vulkan/vulkan.h:2209
type RenderPassBeginInfo struct {
	SType           StructureType
	PNext           unsafe.Pointer
	RenderPass      RenderPass
	Framebuffer     Framebuffer
	RenderArea      Rect2D
	ClearValueCount uint32
	PClearValues    []ClearValue
	ref3c3752c8     *C.VkRenderPassBeginInfo
	allocs3c3752c8  interface{}
}

// DispatchIndirectCommand as declared in vulkan/vulkan.h:2215
type DispatchIndirectCommand struct {
	X              uint32
	Y              uint32
	Z              uint32
	refd298ba27    *C.VkDispatchIndirectCommand
	allocsd298ba27 interface{}
}

// DrawIndexedIndirectCommand as declared in vulkan/vulkan.h:2223
type DrawIndexedIndirectCommand struct {
	IndexCount     uint32
	InstanceCount  uint32
	FirstIndex     uint32
	VertexOffset   int32
	FirstInstance  uint32
	ref4c78b5c3    *C.VkDrawIndexedIndirectCommand
	allocs4c78b5c3 interface{}
}

// DrawIndirectCommand as declared in vulkan/vulkan.h:2230
type DrawIndirectCommand struct {
	VertexCount    uint32
	InstanceCount  uint32
	FirstVertex    uint32
	FirstInstance  uint32
	ref2b5b67c4    *C.VkDrawIndirectCommand
	allocs2b5b67c4 interface{}
}

// PFNCreateInstance type as declared in vulkan/vulkan.h:2233
type PFNCreateInstance func(PCreateInfo []InstanceCreateInfo, PAllocator []AllocationCallbacks, PInstance []Instance) Result

// PFNDestroyInstance type as declared in vulkan/vulkan.h:2234
type PFNDestroyInstance func(Instance Instance, PAllocator []AllocationCallbacks)

// PFNEnumeratePhysicalDevices type as declared in vulkan/vulkan.h:2235
type PFNEnumeratePhysicalDevices func(Instance Instance, PPhysicalDeviceCount []uint32, PPhysicalDevices []PhysicalDevice) Result

// PFNGetPhysicalDeviceFeatures type as declared in vulkan/vulkan.h:2236
type PFNGetPhysicalDeviceFeatures func(PhysicalDevice PhysicalDevice, PFeatures []PhysicalDeviceFeatures)

// PFNGetPhysicalDeviceFormatProperties type as declared in vulkan/vulkan.h:2237
type PFNGetPhysicalDeviceFormatProperties func(PhysicalDevice PhysicalDevice, Format Format, PFormatProperties []FormatProperties)

// PFNGetPhysicalDeviceImageFormatProperties type as declared in vulkan/vulkan.h:2238
type PFNGetPhysicalDeviceImageFormatProperties func(PhysicalDevice PhysicalDevice, Format Format, _type ImageType, Tiling ImageTiling, Usage ImageUsageFlags, Flags ImageCreateFlags, PImageFormatProperties []ImageFormatProperties) Result

// PFNGetPhysicalDeviceProperties type as declared in vulkan/vulkan.h:2239
type PFNGetPhysicalDeviceProperties func(PhysicalDevice PhysicalDevice, PProperties []PhysicalDeviceProperties)

// PFNGetPhysicalDeviceQueueFamilyProperties type as declared in vulkan/vulkan.h:2240
type PFNGetPhysicalDeviceQueueFamilyProperties func(PhysicalDevice PhysicalDevice, PQueueFamilyPropertyCount []uint32, PQueueFamilyProperties []QueueFamilyProperties)

// PFNGetPhysicalDeviceMemoryProperties type as declared in vulkan/vulkan.h:2241
type PFNGetPhysicalDeviceMemoryProperties func(PhysicalDevice PhysicalDevice, PMemoryProperties []PhysicalDeviceMemoryProperties)

// PFNCreateDevice type as declared in vulkan/vulkan.h:2244
type PFNCreateDevice func(PhysicalDevice PhysicalDevice, PCreateInfo []DeviceCreateInfo, PAllocator []AllocationCallbacks, PDevice []Device) Result

// PFNDestroyDevice type as declared in vulkan/vulkan.h:2245
type PFNDestroyDevice func(Device Device, PAllocator []AllocationCallbacks)

// PFNEnumerateInstanceExtensionProperties type as declared in vulkan/vulkan.h:2246
type PFNEnumerateInstanceExtensionProperties func(PLayerName string, PPropertyCount []uint32, PProperties []ExtensionProperties) Result

// PFNEnumerateDeviceExtensionProperties type as declared in vulkan/vulkan.h:2247
type PFNEnumerateDeviceExtensionProperties func(PhysicalDevice PhysicalDevice, PLayerName string, PPropertyCount []uint32, PProperties []ExtensionProperties) Result

// PFNEnumerateInstanceLayerProperties type as declared in vulkan/vulkan.h:2248
type PFNEnumerateInstanceLayerProperties func(PPropertyCount []uint32, PProperties []LayerProperties) Result

// PFNEnumerateDeviceLayerProperties type as declared in vulkan/vulkan.h:2249
type PFNEnumerateDeviceLayerProperties func(PhysicalDevice PhysicalDevice, PPropertyCount []uint32, PProperties []LayerProperties) Result

// PFNGetDeviceQueue type as declared in vulkan/vulkan.h:2250
type PFNGetDeviceQueue func(Device Device, QueueFamilyIndex uint32, QueueIndex uint32, PQueue []Queue)

// PFNQueueSubmit type as declared in vulkan/vulkan.h:2251
type PFNQueueSubmit func(Queue Queue, SubmitCount uint32, PSubmits []SubmitInfo, Fence Fence) Result

// PFNQueueWaitIdle type as declared in vulkan/vulkan.h:2252
type PFNQueueWaitIdle func(Queue Queue) Result

// PFNDeviceWaitIdle type as declared in vulkan/vulkan.h:2253
type PFNDeviceWaitIdle func(Device Device) Result

// PFNAllocateMemory type as declared in vulkan/vulkan.h:2254
type PFNAllocateMemory func(Device Device, PAllocateInfo []MemoryAllocateInfo, PAllocator []AllocationCallbacks, PMemory []DeviceMemory) Result

// PFNFreeMemory type as declared in vulkan/vulkan.h:2255
type PFNFreeMemory func(Device Device, Memory DeviceMemory, PAllocator []AllocationCallbacks)

// PFNMapMemory type as declared in vulkan/vulkan.h:2256
type PFNMapMemory func(Device Device, Memory DeviceMemory, Offset DeviceSize, Size DeviceSize, Flags MemoryMapFlags, PpData []unsafe.Pointer) Result

// PFNUnmapMemory type as declared in vulkan/vulkan.h:2257
type PFNUnmapMemory func(Device Device, Memory DeviceMemory)

// PFNFlushMappedMemoryRanges type as declared in vulkan/vulkan.h:2258
type PFNFlushMappedMemoryRanges func(Device Device, MemoryRangeCount uint32, PMemoryRanges []MappedMemoryRange) Result

// PFNInvalidateMappedMemoryRanges type as declared in vulkan/vulkan.h:2259
type PFNInvalidateMappedMemoryRanges func(Device Device, MemoryRangeCount uint32, PMemoryRanges []MappedMemoryRange) Result

// PFNGetDeviceMemoryCommitment type as declared in vulkan/vulkan.h:2260
type PFNGetDeviceMemoryCommitment func(Device Device, Memory DeviceMemory, PCommittedMemoryInBytes []DeviceSize)

// PFNBindBufferMemory type as declared in vulkan/vulkan.h:2261
type PFNBindBufferMemory func(Device Device, Buffer Buffer, Memory DeviceMemory, MemoryOffset DeviceSize) Result

// PFNBindImageMemory type as declared in vulkan/vulkan.h:2262
type PFNBindImageMemory func(Device Device, Image Image, Memory DeviceMemory, MemoryOffset DeviceSize) Result

// PFNGetBufferMemoryRequirements type as declared in vulkan/vulkan.h:2263
type PFNGetBufferMemoryRequirements func(Device Device, Buffer Buffer, PMemoryRequirements []MemoryRequirements)

// PFNGetImageMemoryRequirements type as declared in vulkan/vulkan.h:2264
type PFNGetImageMemoryRequirements func(Device Device, Image Image, PMemoryRequirements []MemoryRequirements)

// PFNGetImageSparseMemoryRequirements type as declared in vulkan/vulkan.h:2265
type PFNGetImageSparseMemoryRequirements func(Device Device, Image Image, PSparseMemoryRequirementCount []uint32, PSparseMemoryRequirements []SparseImageMemoryRequirements)

// PFNGetPhysicalDeviceSparseImageFormatProperties type as declared in vulkan/vulkan.h:2266
type PFNGetPhysicalDeviceSparseImageFormatProperties func(PhysicalDevice PhysicalDevice, Format Format, _type ImageType, Samples SampleCountFlagBits, Usage ImageUsageFlags, Tiling ImageTiling, PPropertyCount []uint32, PProperties []SparseImageFormatProperties)

// PFNQueueBindSparse type as declared in vulkan/vulkan.h:2267
type PFNQueueBindSparse func(Queue Queue, BindInfoCount uint32, PBindInfo []BindSparseInfo, Fence Fence) Result

// PFNCreateFence type as declared in vulkan/vulkan.h:2268
type PFNCreateFence func(Device Device, PCreateInfo []FenceCreateInfo, PAllocator []AllocationCallbacks, PFence []Fence) Result

// PFNDestroyFence type as declared in vulkan/vulkan.h:2269
type PFNDestroyFence func(Device Device, Fence Fence, PAllocator []AllocationCallbacks)

// PFNResetFences type as declared in vulkan/vulkan.h:2270
type PFNResetFences func(Device Device, FenceCount uint32, PFences []Fence) Result

// PFNGetFenceStatus type as declared in vulkan/vulkan.h:2271
type PFNGetFenceStatus func(Device Device, Fence Fence) Result

// PFNWaitForFences type as declared in vulkan/vulkan.h:2272
type PFNWaitForFences func(Device Device, FenceCount uint32, PFences []Fence, WaitAll Bool32, Timeout uint64) Result

// PFNCreateSemaphore type as declared in vulkan/vulkan.h:2273
type PFNCreateSemaphore func(Device Device, PCreateInfo []SemaphoreCreateInfo, PAllocator []AllocationCallbacks, PSemaphore []Semaphore) Result

// PFNDestroySemaphore type as declared in vulkan/vulkan.h:2274
type PFNDestroySemaphore func(Device Device, Semaphore Semaphore, PAllocator []AllocationCallbacks)

// PFNCreateEvent type as declared in vulkan/vulkan.h:2275
type PFNCreateEvent func(Device Device, PCreateInfo []EventCreateInfo, PAllocator []AllocationCallbacks, PEvent []Event) Result

// PFNDestroyEvent type as declared in vulkan/vulkan.h:2276
type PFNDestroyEvent func(Device Device, Event Event, PAllocator []AllocationCallbacks)

// PFNGetEventStatus type as declared in vulkan/vulkan.h:2277
type PFNGetEventStatus func(Device Device, Event Event) Result

// PFNSetEvent type as declared in vulkan/vulkan.h:2278
type PFNSetEvent func(Device Device, Event Event) Result

// PFNResetEvent type as declared in vulkan/vulkan.h:2279
type PFNResetEvent func(Device Device, Event Event) Result

// PFNCreateQueryPool type as declared in vulkan/vulkan.h:2280
type PFNCreateQueryPool func(Device Device, PCreateInfo []QueryPoolCreateInfo, PAllocator []AllocationCallbacks, PQueryPool []QueryPool) Result

// PFNDestroyQueryPool type as declared in vulkan/vulkan.h:2281
type PFNDestroyQueryPool func(Device Device, QueryPool QueryPool, PAllocator []AllocationCallbacks)

// PFNGetQueryPoolResults type as declared in vulkan/vulkan.h:2282
type PFNGetQueryPoolResults func(Device Device, QueryPool QueryPool, FirstQuery uint32, QueryCount uint32, DataSize uint, PData unsafe.Pointer, Stride DeviceSize, Flags QueryResultFlags) Result

// PFNCreateBuffer type as declared in vulkan/vulkan.h:2283
type PFNCreateBuffer func(Device Device, PCreateInfo []BufferCreateInfo, PAllocator []AllocationCallbacks, PBuffer []Buffer) Result

// PFNDestroyBuffer type as declared in vulkan/vulkan.h:2284
type PFNDestroyBuffer func(Device Device, Buffer Buffer, PAllocator []AllocationCallbacks)

// PFNCreateBufferView type as declared in vulkan/vulkan.h:2285
type PFNCreateBufferView func(Device Device, PCreateInfo []BufferViewCreateInfo, PAllocator []AllocationCallbacks, PView []BufferView) Result

// PFNDestroyBufferView type as declared in vulkan/vulkan.h:2286
type PFNDestroyBufferView func(Device Device, BufferView BufferView, PAllocator []AllocationCallbacks)

// PFNCreateImage type as declared in vulkan/vulkan.h:2287
type PFNCreateImage func(Device Device, PCreateInfo []ImageCreateInfo, PAllocator []AllocationCallbacks, PImage []Image) Result

// PFNDestroyImage type as declared in vulkan/vulkan.h:2288
type PFNDestroyImage func(Device Device, Image Image, PAllocator []AllocationCallbacks)

// PFNGetImageSubresourceLayout type as declared in vulkan/vulkan.h:2289
type PFNGetImageSubresourceLayout func(Device Device, Image Image, PSubresource []ImageSubresource, PLayout []SubresourceLayout)

// PFNCreateImageView type as declared in vulkan/vulkan.h:2290
type PFNCreateImageView func(Device Device, PCreateInfo []ImageViewCreateInfo, PAllocator []AllocationCallbacks, PView []ImageView) Result

// PFNDestroyImageView type as declared in vulkan/vulkan.h:2291
type PFNDestroyImageView func(Device Device, ImageView ImageView, PAllocator []AllocationCallbacks)

// PFNCreateShaderModule type as declared in vulkan/vulkan.h:2292
type PFNCreateShaderModule func(Device Device, PCreateInfo []ShaderModuleCreateInfo, PAllocator []AllocationCallbacks, PShaderModule []ShaderModule) Result

// PFNDestroyShaderModule type as declared in vulkan/vulkan.h:2293
type PFNDestroyShaderModule func(Device Device, ShaderModule ShaderModule, PAllocator []AllocationCallbacks)

// PFNCreatePipelineCache type as declared in vulkan/vulkan.h:2294
type PFNCreatePipelineCache func(Device Device, PCreateInfo []PipelineCacheCreateInfo, PAllocator []AllocationCallbacks, PPipelineCache []PipelineCache) Result

// PFNDestroyPipelineCache type as declared in vulkan/vulkan.h:2295
type PFNDestroyPipelineCache func(Device Device, PipelineCache PipelineCache, PAllocator []AllocationCallbacks)

// PFNGetPipelineCacheData type as declared in vulkan/vulkan.h:2296
type PFNGetPipelineCacheData func(Device Device, PipelineCache PipelineCache, PDataSize []uint, PData unsafe.Pointer) Result

// PFNMergePipelineCaches type as declared in vulkan/vulkan.h:2297
type PFNMergePipelineCaches func(Device Device, DstCache PipelineCache, SrcCacheCount uint32, PSrcCaches []PipelineCache) Result

// PFNCreateGraphicsPipelines type as declared in vulkan/vulkan.h:2298
type PFNCreateGraphicsPipelines func(Device Device, PipelineCache PipelineCache, CreateInfoCount uint32, PCreateInfos []GraphicsPipelineCreateInfo, PAllocator []AllocationCallbacks, PPipelines []Pipeline) Result

// PFNCreateComputePipelines type as declared in vulkan/vulkan.h:2299
type PFNCreateComputePipelines func(Device Device, PipelineCache PipelineCache, CreateInfoCount uint32, PCreateInfos []ComputePipelineCreateInfo, PAllocator []AllocationCallbacks, PPipelines []Pipeline) Result

// PFNDestroyPipeline type as declared in vulkan/vulkan.h:2300
type PFNDestroyPipeline func(Device Device, Pipeline Pipeline, PAllocator []AllocationCallbacks)

// PFNCreatePipelineLayout type as declared in vulkan/vulkan.h:2301
type PFNCreatePipelineLayout func(Device Device, PCreateInfo []PipelineLayoutCreateInfo, PAllocator []AllocationCallbacks, PPipelineLayout []PipelineLayout) Result

// PFNDestroyPipelineLayout type as declared in vulkan/vulkan.h:2302
type PFNDestroyPipelineLayout func(Device Device, PipelineLayout PipelineLayout, PAllocator []AllocationCallbacks)

// PFNCreateSampler type as declared in vulkan/vulkan.h:2303
type PFNCreateSampler func(Device Device, PCreateInfo []SamplerCreateInfo, PAllocator []AllocationCallbacks, PSampler []Sampler) Result

// PFNDestroySampler type as declared in vulkan/vulkan.h:2304
type PFNDestroySampler func(Device Device, Sampler Sampler, PAllocator []AllocationCallbacks)

// PFNCreateDescriptorSetLayout type as declared in vulkan/vulkan.h:2305
type PFNCreateDescriptorSetLayout func(Device Device, PCreateInfo []DescriptorSetLayoutCreateInfo, PAllocator []AllocationCallbacks, PSetLayout []DescriptorSetLayout) Result

// PFNDestroyDescriptorSetLayout type as declared in vulkan/vulkan.h:2306
type PFNDestroyDescriptorSetLayout func(Device Device, DescriptorSetLayout DescriptorSetLayout, PAllocator []AllocationCallbacks)

// PFNCreateDescriptorPool type as declared in vulkan/vulkan.h:2307
type PFNCreateDescriptorPool func(Device Device, PCreateInfo []DescriptorPoolCreateInfo, PAllocator []AllocationCallbacks, PDescriptorPool []DescriptorPool) Result

// PFNDestroyDescriptorPool type as declared in vulkan/vulkan.h:2308
type PFNDestroyDescriptorPool func(Device Device, DescriptorPool DescriptorPool, PAllocator []AllocationCallbacks)

// PFNResetDescriptorPool type as declared in vulkan/vulkan.h:2309
type PFNResetDescriptorPool func(Device Device, DescriptorPool DescriptorPool, Flags DescriptorPoolResetFlags) Result

// PFNAllocateDescriptorSets type as declared in vulkan/vulkan.h:2310
type PFNAllocateDescriptorSets func(Device Device, PAllocateInfo []DescriptorSetAllocateInfo, PDescriptorSets []DescriptorSet) Result

// PFNFreeDescriptorSets type as declared in vulkan/vulkan.h:2311
type PFNFreeDescriptorSets func(Device Device, DescriptorPool DescriptorPool, DescriptorSetCount uint32, PDescriptorSets []DescriptorSet) Result

// PFNUpdateDescriptorSets type as declared in vulkan/vulkan.h:2312
type PFNUpdateDescriptorSets func(Device Device, DescriptorWriteCount uint32, PDescriptorWrites []WriteDescriptorSet, DescriptorCopyCount uint32, PDescriptorCopies []CopyDescriptorSet)

// PFNCreateFramebuffer type as declared in vulkan/vulkan.h:2313
type PFNCreateFramebuffer func(Device Device, PCreateInfo []FramebufferCreateInfo, PAllocator []AllocationCallbacks, PFramebuffer []Framebuffer) Result

// PFNDestroyFramebuffer type as declared in vulkan/vulkan.h:2314
type PFNDestroyFramebuffer func(Device Device, Framebuffer Framebuffer, PAllocator []AllocationCallbacks)

// PFNCreateRenderPass type as declared in vulkan/vulkan.h:2315
type PFNCreateRenderPass func(Device Device, PCreateInfo []RenderPassCreateInfo, PAllocator []AllocationCallbacks, PRenderPass []RenderPass) Result

// PFNDestroyRenderPass type as declared in vulkan/vulkan.h:2316
type PFNDestroyRenderPass func(Device Device, RenderPass RenderPass, PAllocator []AllocationCallbacks)

// PFNGetRenderAreaGranularity type as declared in vulkan/vulkan.h:2317
type PFNGetRenderAreaGranularity func(Device Device, RenderPass RenderPass, PGranularity []Extent2D)

// PFNCreateCommandPool type as declared in vulkan/vulkan.h:2318
type PFNCreateCommandPool func(Device Device, PCreateInfo []CommandPoolCreateInfo, PAllocator []AllocationCallbacks, PCommandPool []CommandPool) Result

// PFNDestroyCommandPool type as declared in vulkan/vulkan.h:2319
type PFNDestroyCommandPool func(Device Device, CommandPool CommandPool, PAllocator []AllocationCallbacks)

// PFNResetCommandPool type as declared in vulkan/vulkan.h:2320
type PFNResetCommandPool func(Device Device, CommandPool CommandPool, Flags CommandPoolResetFlags) Result

// PFNAllocateCommandBuffers type as declared in vulkan/vulkan.h:2321
type PFNAllocateCommandBuffers func(Device Device, PAllocateInfo []CommandBufferAllocateInfo, PCommandBuffers []CommandBuffer) Result

// PFNFreeCommandBuffers type as declared in vulkan/vulkan.h:2322
type PFNFreeCommandBuffers func(Device Device, CommandPool CommandPool, CommandBufferCount uint32, PCommandBuffers []CommandBuffer)

// PFNBeginCommandBuffer type as declared in vulkan/vulkan.h:2323
type PFNBeginCommandBuffer func(CommandBuffer CommandBuffer, PBeginInfo []CommandBufferBeginInfo) Result

// PFNEndCommandBuffer type as declared in vulkan/vulkan.h:2324
type PFNEndCommandBuffer func(CommandBuffer CommandBuffer) Result

// PFNResetCommandBuffer type as declared in vulkan/vulkan.h:2325
type PFNResetCommandBuffer func(CommandBuffer CommandBuffer, Flags CommandBufferResetFlags) Result

// PFNCmdBindPipeline type as declared in vulkan/vulkan.h:2326
type PFNCmdBindPipeline func(CommandBuffer CommandBuffer, PipelineBindPoint PipelineBindPoint, Pipeline Pipeline)

// PFNCmdSetViewport type as declared in vulkan/vulkan.h:2327
type PFNCmdSetViewport func(CommandBuffer CommandBuffer, FirstViewport uint32, ViewportCount uint32, PViewports []Viewport)

// PFNCmdSetScissor type as declared in vulkan/vulkan.h:2328
type PFNCmdSetScissor func(CommandBuffer CommandBuffer, FirstScissor uint32, ScissorCount uint32, PScissors []Rect2D)

// PFNCmdSetLineWidth type as declared in vulkan/vulkan.h:2329
type PFNCmdSetLineWidth func(CommandBuffer CommandBuffer, LineWidth float32)

// PFNCmdSetDepthBias type as declared in vulkan/vulkan.h:2330
type PFNCmdSetDepthBias func(CommandBuffer CommandBuffer, DepthBiasConstantFactor float32, DepthBiasClamp float32, DepthBiasSlopeFactor float32)

// PFNCmdSetDepthBounds type as declared in vulkan/vulkan.h:2332
type PFNCmdSetDepthBounds func(CommandBuffer CommandBuffer, MinDepthBounds float32, MaxDepthBounds float32)

// PFNCmdSetStencilCompareMask type as declared in vulkan/vulkan.h:2333
type PFNCmdSetStencilCompareMask func(CommandBuffer CommandBuffer, FaceMask StencilFaceFlags, CompareMask uint32)

// PFNCmdSetStencilWriteMask type as declared in vulkan/vulkan.h:2334
type PFNCmdSetStencilWriteMask func(CommandBuffer CommandBuffer, FaceMask StencilFaceFlags, WriteMask uint32)

// PFNCmdSetStencilReference type as declared in vulkan/vulkan.h:2335
type PFNCmdSetStencilReference func(CommandBuffer CommandBuffer, FaceMask StencilFaceFlags, Reference uint32)

// PFNCmdBindDescriptorSets type as declared in vulkan/vulkan.h:2336
type PFNCmdBindDescriptorSets func(CommandBuffer CommandBuffer, PipelineBindPoint PipelineBindPoint, Layout PipelineLayout, FirstSet uint32, DescriptorSetCount uint32, PDescriptorSets []DescriptorSet, DynamicOffsetCount uint32, PDynamicOffsets []uint32)

// PFNCmdBindIndexBuffer type as declared in vulkan/vulkan.h:2337
type PFNCmdBindIndexBuffer func(CommandBuffer CommandBuffer, Buffer Buffer, Offset DeviceSize, IndexType IndexType)

// PFNCmdBindVertexBuffers type as declared in vulkan/vulkan.h:2338
type PFNCmdBindVertexBuffers func(CommandBuffer CommandBuffer, FirstBinding uint32, BindingCount uint32, PBuffers []Buffer, POffsets []DeviceSize)

// PFNCmdDraw type as declared in vulkan/vulkan.h:2339
type PFNCmdDraw func(CommandBuffer CommandBuffer, VertexCount uint32, InstanceCount uint32, FirstVertex uint32, FirstInstance uint32)

// PFNCmdDrawIndexed type as declared in vulkan/vulkan.h:2340
type PFNCmdDrawIndexed func(CommandBuffer CommandBuffer, IndexCount uint32, InstanceCount uint32, FirstIndex uint32, VertexOffset int32, FirstInstance uint32)

// PFNCmdDrawIndirect type as declared in vulkan/vulkan.h:2341
type PFNCmdDrawIndirect func(CommandBuffer CommandBuffer, Buffer Buffer, Offset DeviceSize, DrawCount uint32, Stride uint32)

// PFNCmdDrawIndexedIndirect type as declared in vulkan/vulkan.h:2342
type PFNCmdDrawIndexedIndirect func(CommandBuffer CommandBuffer, Buffer Buffer, Offset DeviceSize, DrawCount uint32, Stride uint32)

// PFNCmdDispatch type as declared in vulkan/vulkan.h:2343
type PFNCmdDispatch func(CommandBuffer CommandBuffer, X uint32, Y uint32, Z uint32)

// PFNCmdDispatchIndirect type as declared in vulkan/vulkan.h:2344
type PFNCmdDispatchIndirect func(CommandBuffer CommandBuffer, Buffer Buffer, Offset DeviceSize)

// PFNCmdCopyBuffer type as declared in vulkan/vulkan.h:2345
type PFNCmdCopyBuffer func(CommandBuffer CommandBuffer, SrcBuffer Buffer, DstBuffer Buffer, RegionCount uint32, PRegions []BufferCopy)

// PFNCmdCopyImage type as declared in vulkan/vulkan.h:2346
type PFNCmdCopyImage func(CommandBuffer CommandBuffer, SrcImage Image, SrcImageLayout ImageLayout, DstImage Image, DstImageLayout ImageLayout, RegionCount uint32, PRegions []ImageCopy)

// PFNCmdBlitImage type as declared in vulkan/vulkan.h:2347
type PFNCmdBlitImage func(CommandBuffer CommandBuffer, SrcImage Image, SrcImageLayout ImageLayout, DstImage Image, DstImageLayout ImageLayout, RegionCount uint32, PRegions []ImageBlit, Filter Filter)

// PFNCmdCopyBufferToImage type as declared in vulkan/vulkan.h:2348
type PFNCmdCopyBufferToImage func(CommandBuffer CommandBuffer, SrcBuffer Buffer, DstImage Image, DstImageLayout ImageLayout, RegionCount uint32, PRegions []BufferImageCopy)

// PFNCmdCopyImageToBuffer type as declared in vulkan/vulkan.h:2349
type PFNCmdCopyImageToBuffer func(CommandBuffer CommandBuffer, SrcImage Image, SrcImageLayout ImageLayout, DstBuffer Buffer, RegionCount uint32, PRegions []BufferImageCopy)

// PFNCmdUpdateBuffer type as declared in vulkan/vulkan.h:2350
type PFNCmdUpdateBuffer func(CommandBuffer CommandBuffer, DstBuffer Buffer, DstOffset DeviceSize, DataSize DeviceSize, PData []uint32)

// PFNCmdFillBuffer type as declared in vulkan/vulkan.h:2351
type PFNCmdFillBuffer func(CommandBuffer CommandBuffer, DstBuffer Buffer, DstOffset DeviceSize, Size DeviceSize, Data uint32)

// PFNCmdClearColorImage type as declared in vulkan/vulkan.h:2352
type PFNCmdClearColorImage func(CommandBuffer CommandBuffer, Image Image, ImageLayout ImageLayout, PColor []ClearColorValue, RangeCount uint32, PRanges []ImageSubresourceRange)

// PFNCmdClearDepthStencilImage type as declared in vulkan/vulkan.h:2353
type PFNCmdClearDepthStencilImage func(CommandBuffer CommandBuffer, Image Image, ImageLayout ImageLayout, PDepthStencil []ClearDepthStencilValue, RangeCount uint32, PRanges []ImageSubresourceRange)

// PFNCmdClearAttachments type as declared in vulkan/vulkan.h:2354
type PFNCmdClearAttachments func(CommandBuffer CommandBuffer, AttachmentCount uint32, PAttachments []ClearAttachment, RectCount uint32, PRects []ClearRect)

// PFNCmdResolveImage type as declared in vulkan/vulkan.h:2355
type PFNCmdResolveImage func(CommandBuffer CommandBuffer, SrcImage Image, SrcImageLayout ImageLayout, DstImage Image, DstImageLayout ImageLayout, RegionCount uint32, PRegions []ImageResolve)

// PFNCmdSetEvent type as declared in vulkan/vulkan.h:2356
type PFNCmdSetEvent func(CommandBuffer CommandBuffer, Event Event, StageMask PipelineStageFlags)

// PFNCmdResetEvent type as declared in vulkan/vulkan.h:2357
type PFNCmdResetEvent func(CommandBuffer CommandBuffer, Event Event, StageMask PipelineStageFlags)

// PFNCmdWaitEvents type as declared in vulkan/vulkan.h:2358
type PFNCmdWaitEvents func(CommandBuffer CommandBuffer, EventCount uint32, PEvents []Event, SrcStageMask PipelineStageFlags, DstStageMask PipelineStageFlags, MemoryBarrierCount uint32, PMemoryBarriers []MemoryBarrier, BufferMemoryBarrierCount uint32, PBufferMemoryBarriers []BufferMemoryBarrier, ImageMemoryBarrierCount uint32, PImageMemoryBarriers []ImageMemoryBarrier)

// PFNCmdPipelineBarrier type as declared in vulkan/vulkan.h:2359
type PFNCmdPipelineBarrier func(CommandBuffer CommandBuffer, SrcStageMask PipelineStageFlags, DstStageMask PipelineStageFlags, DependencyFlags DependencyFlags, MemoryBarrierCount uint32, PMemoryBarriers []MemoryBarrier, BufferMemoryBarrierCount uint32, PBufferMemoryBarriers []BufferMemoryBarrier, ImageMemoryBarrierCount uint32, PImageMemoryBarriers []ImageMemoryBarrier)

// PFNCmdBeginQuery type as declared in vulkan/vulkan.h:2360
type PFNCmdBeginQuery func(CommandBuffer CommandBuffer, QueryPool QueryPool, Query uint32, Flags QueryControlFlags)

// PFNCmdEndQuery type as declared in vulkan/vulkan.h:2361
type PFNCmdEndQuery func(CommandBuffer CommandBuffer, QueryPool QueryPool, Query uint32)

// PFNCmdResetQueryPool type as declared in vulkan/vulkan.h:2362
type PFNCmdResetQueryPool func(CommandBuffer CommandBuffer, QueryPool QueryPool, FirstQuery uint32, QueryCount uint32)

// PFNCmdWriteTimestamp type as declared in vulkan/vulkan.h:2363
type PFNCmdWriteTimestamp func(CommandBuffer CommandBuffer, PipelineStage PipelineStageFlagBits, QueryPool QueryPool, Query uint32)

// PFNCmdCopyQueryPoolResults type as declared in vulkan/vulkan.h:2364
type PFNCmdCopyQueryPoolResults func(CommandBuffer CommandBuffer, QueryPool QueryPool, FirstQuery uint32, QueryCount uint32, DstBuffer Buffer, DstOffset DeviceSize, Stride DeviceSize, Flags QueryResultFlags)

// PFNCmdPushConstants type as declared in vulkan/vulkan.h:2365
type PFNCmdPushConstants func(CommandBuffer CommandBuffer, Layout PipelineLayout, StageFlags ShaderStageFlags, Offset uint32, Size uint32, PValues unsafe.Pointer)

// PFNCmdBeginRenderPass type as declared in vulkan/vulkan.h:2366
type PFNCmdBeginRenderPass func(CommandBuffer CommandBuffer, PRenderPassBegin []RenderPassBeginInfo, Contents SubpassContents)

// PFNCmdNextSubpass type as declared in vulkan/vulkan.h:2367
type PFNCmdNextSubpass func(CommandBuffer CommandBuffer, Contents SubpassContents)

// PFNCmdEndRenderPass type as declared in vulkan/vulkan.h:2368
type PFNCmdEndRenderPass func(CommandBuffer CommandBuffer)

// PFNCmdExecuteCommands type as declared in vulkan/vulkan.h:2369
type PFNCmdExecuteCommands func(CommandBuffer CommandBuffer, CommandBufferCount uint32, PCommandBuffers []CommandBuffer)

// SurfaceKHR as declared in vulkan/vulkan.h:3171
type SurfaceKHR C.VkSurfaceKHR

// SurfaceTransformFlagsKHR type as declared in vulkan/vulkan.h:3210
type SurfaceTransformFlagsKHR uint32

// CompositeAlphaFlagsKHR type as declared in vulkan/vulkan.h:3219
type CompositeAlphaFlagsKHR uint32

// SurfaceCapabilitiesKHR as declared in vulkan/vulkan.h:3232
type SurfaceCapabilitiesKHR struct {
	MinImageCount           uint32
	MaxImageCount           uint32
	CurrentExtent           Extent2D
	MinImageExtent          Extent2D
	MaxImageExtent          Extent2D
	MaxImageArrayLayers     uint32
	SupportedTransforms     SurfaceTransformFlagsKHR
	CurrentTransform        SurfaceTransformFlagBitsKHR
	SupportedCompositeAlpha CompositeAlphaFlagsKHR
	SupportedUsageFlags     ImageUsageFlags
	ref11d5f596             *C.VkSurfaceCapabilitiesKHR
	allocs11d5f596          interface{}
}

// SurfaceFormatKHR as declared in vulkan/vulkan.h:3237
type SurfaceFormatKHR struct {
	Format         Format
	ColorSpace     ColorSpaceKHR
	refedaf82ca    *C.VkSurfaceFormatKHR
	allocsedaf82ca interface{}
}

// PFNDestroySurfaceKHR type as declared in vulkan/vulkan.h:3240
type PFNDestroySurfaceKHR func(Instance Instance, Surface SurfaceKHR, PAllocator []AllocationCallbacks)

// PFNGetPhysicalDeviceSurfaceSupportKHR type as declared in vulkan/vulkan.h:3241
type PFNGetPhysicalDeviceSurfaceSupportKHR func(PhysicalDevice PhysicalDevice, QueueFamilyIndex uint32, Surface SurfaceKHR, PSupported []Bool32) Result

// PFNGetPhysicalDeviceSurfaceCapabilitiesKHR type as declared in vulkan/vulkan.h:3242
type PFNGetPhysicalDeviceSurfaceCapabilitiesKHR func(PhysicalDevice PhysicalDevice, Surface SurfaceKHR, PSurfaceCapabilities []SurfaceCapabilitiesKHR) Result

// PFNGetPhysicalDeviceSurfaceFormatsKHR type as declared in vulkan/vulkan.h:3243
type PFNGetPhysicalDeviceSurfaceFormatsKHR func(PhysicalDevice PhysicalDevice, Surface SurfaceKHR, PSurfaceFormatCount []uint32, PSurfaceFormats []SurfaceFormatKHR) Result

// PFNGetPhysicalDeviceSurfacePresentModesKHR type as declared in vulkan/vulkan.h:3244
type PFNGetPhysicalDeviceSurfacePresentModesKHR func(PhysicalDevice PhysicalDevice, Surface SurfaceKHR, PPresentModeCount []uint32, PPresentModes []PresentModeKHR) Result

// SwapchainKHR as declared in vulkan/vulkan.h:3277
type SwapchainKHR C.VkSwapchainKHR

// SwapchainCreateFlagsKHR type as declared in vulkan/vulkan.h:3282
type SwapchainCreateFlagsKHR uint32

// SwapchainCreateInfoKHR as declared in vulkan/vulkan.h:3303
type SwapchainCreateInfoKHR struct {
	SType                 StructureType
	PNext                 unsafe.Pointer
	Flags                 SwapchainCreateFlagsKHR
	Surface               SurfaceKHR
	MinImageCount         uint32
	ImageFormat           Format
	ImageColorSpace       ColorSpaceKHR
	ImageExtent           Extent2D
	ImageArrayLayers      uint32
	ImageUsage            ImageUsageFlags
	ImageSharingMode      SharingMode
	QueueFamilyIndexCount uint32
	PQueueFamilyIndices   []uint32
	PreTransform          SurfaceTransformFlagBitsKHR
	CompositeAlpha        CompositeAlphaFlagBitsKHR
	PresentMode           PresentModeKHR
	Clipped               Bool32
	OldSwapchain          SwapchainKHR
	refdb619e1c           *C.VkSwapchainCreateInfoKHR
	allocsdb619e1c        interface{}
}

// PresentInfoKHR as declared in vulkan/vulkan.h:3314
type PresentInfoKHR struct {
	SType              StructureType
	PNext              unsafe.Pointer
	WaitSemaphoreCount uint32
	PWaitSemaphores    []Semaphore
	SwapchainCount     uint32
	PSwapchains        []SwapchainKHR
	PImageIndices      []uint32
	PResults           []Result
	ref1d0e82d4        *C.VkPresentInfoKHR
	allocs1d0e82d4     interface{}
}

// PFNCreateSwapchainKHR type as declared in vulkan/vulkan.h:3317
type PFNCreateSwapchainKHR func(Device Device, PCreateInfo []SwapchainCreateInfoKHR, PAllocator []AllocationCallbacks, PSwapchain []SwapchainKHR) Result

// PFNDestroySwapchainKHR type as declared in vulkan/vulkan.h:3318
type PFNDestroySwapchainKHR func(Device Device, Swapchain SwapchainKHR, PAllocator []AllocationCallbacks)

// PFNGetSwapchainImagesKHR type as declared in vulkan/vulkan.h:3319
type PFNGetSwapchainImagesKHR func(Device Device, Swapchain SwapchainKHR, PSwapchainImageCount []uint32, PSwapchainImages []Image) Result

// PFNAcquireNextImageKHR type as declared in vulkan/vulkan.h:3320
type PFNAcquireNextImageKHR func(Device Device, Swapchain SwapchainKHR, Timeout uint64, Semaphore Semaphore, Fence Fence, PImageIndex []uint32) Result

// PFNQueuePresentKHR type as declared in vulkan/vulkan.h:3321
type PFNQueuePresentKHR func(Queue Queue, PPresentInfo []PresentInfoKHR) Result

// DisplayKHR as declared in vulkan/vulkan.h:3355
type DisplayKHR C.VkDisplayKHR

// DisplayModeKHR as declared in vulkan/vulkan.h:3356
type DisplayModeKHR C.VkDisplayModeKHR

// DisplayPlaneAlphaFlagsKHR type as declared in vulkan/vulkan.h:3369
type DisplayPlaneAlphaFlagsKHR uint32

// DisplayModeCreateFlagsKHR type as declared in vulkan/vulkan.h:3370
type DisplayModeCreateFlagsKHR uint32

// DisplaySurfaceCreateFlagsKHR type as declared in vulkan/vulkan.h:3371
type DisplaySurfaceCreateFlagsKHR uint32

// DisplayPropertiesKHR as declared in vulkan/vulkan.h:3381
type DisplayPropertiesKHR struct {
	Display              DisplayKHR
	DisplayName          string
	PhysicalDimensions   Extent2D
	PhysicalResolution   Extent2D
	SupportedTransforms  SurfaceTransformFlagsKHR
	PlaneReorderPossible Bool32
	PersistentContent    Bool32
	reffe2a7187          *C.VkDisplayPropertiesKHR
	allocsfe2a7187       interface{}
}

// DisplayModeParametersKHR as declared in vulkan/vulkan.h:3386
type DisplayModeParametersKHR struct {
	VisibleRegion  Extent2D
	RefreshRate    uint32
	refe016f77f    *C.VkDisplayModeParametersKHR
	allocse016f77f interface{}
}

// DisplayModePropertiesKHR as declared in vulkan/vulkan.h:3391
type DisplayModePropertiesKHR struct {
	DisplayMode    DisplayModeKHR
	Parameters     DisplayModeParametersKHR
	ref5e3abaaa    *C.VkDisplayModePropertiesKHR
	allocs5e3abaaa interface{}
}

// DisplayModeCreateInfoKHR as declared in vulkan/vulkan.h:3398
type DisplayModeCreateInfoKHR struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DisplayModeCreateFlagsKHR
	Parameters     DisplayModeParametersKHR
	ref392fca31    *C.VkDisplayModeCreateInfoKHR
	allocs392fca31 interface{}
}

// DisplayPlaneCapabilitiesKHR as declared in vulkan/vulkan.h:3410
type DisplayPlaneCapabilitiesKHR struct {
	SupportedAlpha DisplayPlaneAlphaFlagsKHR
	MinSrcPosition Offset2D
	MaxSrcPosition Offset2D
	MinSrcExtent   Extent2D
	MaxSrcExtent   Extent2D
	MinDstPosition Offset2D
	MaxDstPosition Offset2D
	MinDstExtent   Extent2D
	MaxDstExtent   Extent2D
	ref6f31fcaf    *C.VkDisplayPlaneCapabilitiesKHR
	allocs6f31fcaf interface{}
}

// DisplayPlanePropertiesKHR as declared in vulkan/vulkan.h:3415
type DisplayPlanePropertiesKHR struct {
	CurrentDisplay    DisplayKHR
	CurrentStackIndex uint32
	refce3db3f6       *C.VkDisplayPlanePropertiesKHR
	allocsce3db3f6    interface{}
}

// DisplaySurfaceCreateInfoKHR as declared in vulkan/vulkan.h:3428
type DisplaySurfaceCreateInfoKHR struct {
	SType           StructureType
	PNext           unsafe.Pointer
	Flags           DisplaySurfaceCreateFlagsKHR
	DisplayMode     DisplayModeKHR
	PlaneIndex      uint32
	PlaneStackIndex uint32
	Transform       SurfaceTransformFlagBitsKHR
	GlobalAlpha     float32
	AlphaMode       DisplayPlaneAlphaFlagBitsKHR
	ImageExtent     Extent2D
	ref58445c35     *C.VkDisplaySurfaceCreateInfoKHR
	allocs58445c35  interface{}
}

// PFNGetPhysicalDeviceDisplayPropertiesKHR type as declared in vulkan/vulkan.h:3431
type PFNGetPhysicalDeviceDisplayPropertiesKHR func(PhysicalDevice PhysicalDevice, PPropertyCount []uint32, PProperties []DisplayPropertiesKHR) Result

// PFNGetPhysicalDeviceDisplayPlanePropertiesKHR type as declared in vulkan/vulkan.h:3432
type PFNGetPhysicalDeviceDisplayPlanePropertiesKHR func(PhysicalDevice PhysicalDevice, PPropertyCount []uint32, PProperties []DisplayPlanePropertiesKHR) Result

// PFNGetDisplayPlaneSupportedDisplaysKHR type as declared in vulkan/vulkan.h:3433
type PFNGetDisplayPlaneSupportedDisplaysKHR func(PhysicalDevice PhysicalDevice, PlaneIndex uint32, PDisplayCount []uint32, PDisplays []DisplayKHR) Result

// PFNGetDisplayModePropertiesKHR type as declared in vulkan/vulkan.h:3434
type PFNGetDisplayModePropertiesKHR func(PhysicalDevice PhysicalDevice, Display DisplayKHR, PPropertyCount []uint32, PProperties []DisplayModePropertiesKHR) Result

// PFNCreateDisplayModeKHR type as declared in vulkan/vulkan.h:3435
type PFNCreateDisplayModeKHR func(PhysicalDevice PhysicalDevice, Display DisplayKHR, PCreateInfo []DisplayModeCreateInfoKHR, PAllocator []AllocationCallbacks, PMode []DisplayModeKHR) Result

// PFNGetDisplayPlaneCapabilitiesKHR type as declared in vulkan/vulkan.h:3436
type PFNGetDisplayPlaneCapabilitiesKHR func(PhysicalDevice PhysicalDevice, Mode DisplayModeKHR, PlaneIndex uint32, PCapabilities []DisplayPlaneCapabilitiesKHR) Result

// PFNCreateDisplayPlaneSurfaceKHR type as declared in vulkan/vulkan.h:3437
type PFNCreateDisplayPlaneSurfaceKHR func(Instance Instance, PCreateInfo []DisplaySurfaceCreateInfoKHR, PAllocator []AllocationCallbacks, PSurface []SurfaceKHR) Result

// DisplayPresentInfoKHR as declared in vulkan/vulkan.h:3492
type DisplayPresentInfoKHR struct {
	SType          StructureType
	PNext          unsafe.Pointer
	SrcRect        Rect2D
	DstRect        Rect2D
	Persistent     Bool32
	ref8d2571e4    *C.VkDisplayPresentInfoKHR
	allocs8d2571e4 interface{}
}

// PFNCreateSharedSwapchainsKHR type as declared in vulkan/vulkan.h:3495
type PFNCreateSharedSwapchainsKHR func(Device Device, SwapchainCount uint32, PCreateInfos []SwapchainCreateInfoKHR, PAllocator []AllocationCallbacks, PSwapchains []SwapchainKHR) Result

// AndroidSurfaceCreateFlagsKHR type as declared in vulkan/vulkan.h:3655
type AndroidSurfaceCreateFlagsKHR uint32

// AndroidSurfaceCreateInfoKHR as declared in vulkan/vulkan.h:3662
type AndroidSurfaceCreateInfoKHR struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          AndroidSurfaceCreateFlagsKHR
	refeca5c35c    *C.VkAndroidSurfaceCreateInfoKHR
	allocseca5c35c interface{}
}

// PFNCreateAndroidSurfaceKHR type as declared in vulkan/vulkan.h:3665
type PFNCreateAndroidSurfaceKHR func(Instance Instance, PCreateInfo []AndroidSurfaceCreateInfoKHR, PAllocator []AllocationCallbacks, PSurface []SurfaceKHR) Result

// DebugReportCallbackEXT as declared in vulkan/vulkan.h:3716
type DebugReportCallbackEXT C.VkDebugReportCallbackEXT

// DebugReportFlagsEXT type as declared in vulkan/vulkan.h:3777
type DebugReportFlagsEXT uint32

// PFNDebugReportCallbackEXT type as declared in vulkan/vulkan.h:3779
type PFNDebugReportCallbackEXT func(Flags DebugReportFlagsEXT, ObjectType DebugReportObjectTypeEXT, Object uint64, Location uint, MessageCode int32, PLayerPrefix string, PMessage string, PUserData unsafe.Pointer) Bool32

// DebugReportCallbackCreateInfoEXT as declared in vulkan/vulkan.h:3796
type DebugReportCallbackCreateInfoEXT struct {
	SType          StructureType
	PNext          unsafe.Pointer
	Flags          DebugReportFlagsEXT
	PfnCallback    PFNDebugReportCallbackEXT
	PUserData      unsafe.Pointer
	refc8238563    *C.VkDebugReportCallbackCreateInfoEXT
	allocsc8238563 interface{}
}

// PFNCreateDebugReportCallbackEXT type as declared in vulkan/vulkan.h:3799
type PFNCreateDebugReportCallbackEXT func(Instance Instance, PCreateInfo []DebugReportCallbackCreateInfoEXT, PAllocator []AllocationCallbacks, PCallback []DebugReportCallbackEXT) Result

// PFNDestroyDebugReportCallbackEXT type as declared in vulkan/vulkan.h:3800
type PFNDestroyDebugReportCallbackEXT func(Instance Instance, Callback DebugReportCallbackEXT, PAllocator []AllocationCallbacks)

// PFNDebugReportMessageEXT type as declared in vulkan/vulkan.h:3801
type PFNDebugReportMessageEXT func(Instance Instance, Flags DebugReportFlagsEXT, ObjectType DebugReportObjectTypeEXT, Object uint64, Location uint, MessageCode int32, PLayerPrefix string, PMessage string)

// PipelineRasterizationStateRasterizationOrderAMD as declared in vulkan/vulkan.h:3854
type PipelineRasterizationStateRasterizationOrderAMD struct {
	SType              StructureType
	PNext              unsafe.Pointer
	RasterizationOrder RasterizationOrderAMD
	ref5098cf82        *C.VkPipelineRasterizationStateRasterizationOrderAMD
	allocs5098cf82     interface{}
}

// DebugMarkerObjectNameInfoEXT as declared in vulkan/vulkan.h:3868
type DebugMarkerObjectNameInfoEXT struct {
	SType          StructureType
	PNext          unsafe.Pointer
	ObjectType     DebugReportObjectTypeEXT
	Object         uint64
	PObjectName    string
	refe4983fab    *C.VkDebugMarkerObjectNameInfoEXT
	allocse4983fab interface{}
}

// DebugMarkerObjectTagInfoEXT as declared in vulkan/vulkan.h:3878
type DebugMarkerObjectTagInfoEXT struct {
	SType          StructureType
	PNext          unsafe.Pointer
	ObjectType     DebugReportObjectTypeEXT
	Object         uint64
	TagName        uint64
	TagSize        uint
	PTag           unsafe.Pointer
	refa41a5c3b    *C.VkDebugMarkerObjectTagInfoEXT
	allocsa41a5c3b interface{}
}

// DebugMarkerMarkerInfoEXT as declared in vulkan/vulkan.h:3885
type DebugMarkerMarkerInfoEXT struct {
	SType          StructureType
	PNext          unsafe.Pointer
	PMarkerName    string
	Color          [4]float32
	ref234b91fd    *C.VkDebugMarkerMarkerInfoEXT
	allocs234b91fd interface{}
}

// PFNDebugMarkerSetObjectTagEXT type as declared in vulkan/vulkan.h:3888
type PFNDebugMarkerSetObjectTagEXT func(Device Device, PTagInfo []DebugMarkerObjectTagInfoEXT) Result

// PFNDebugMarkerSetObjectNameEXT type as declared in vulkan/vulkan.h:3889
type PFNDebugMarkerSetObjectNameEXT func(Device Device, PNameInfo []DebugMarkerObjectNameInfoEXT) Result

// PFNCmdDebugMarkerBeginEXT type as declared in vulkan/vulkan.h:3890
type PFNCmdDebugMarkerBeginEXT func(CommandBuffer CommandBuffer, PMarkerInfo []DebugMarkerMarkerInfoEXT)

// PFNCmdDebugMarkerEndEXT type as declared in vulkan/vulkan.h:3891
type PFNCmdDebugMarkerEndEXT func(CommandBuffer CommandBuffer)

// PFNCmdDebugMarkerInsertEXT type as declared in vulkan/vulkan.h:3892
type PFNCmdDebugMarkerInsertEXT func(CommandBuffer CommandBuffer, PMarkerInfo []DebugMarkerMarkerInfoEXT)
