// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vgpu

const (
	Version     = "v1.0.1"
	GitCommit   = "7305916"          // the commit JUST BEFORE the release
	VersionDate = "2023-02-10 08:27" // UTC
)
