// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vulkan

const (
	GoVersion   = "v1.0.6"
	GitCommit   = "7e2340c"          // the commit JUST BEFORE the release
	VersionDate = "2023-03-10 21:29" // UTC
)
