// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package vulkan

const (
	GoVersion   = "v1.0.3"
	GitCommit   = "1c25b5b"          // the commit JUST BEFORE the release
	VersionDate = "2023-02-10 12:28" // UTC
)
