// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 16 May 2016 03:35:25 MSK.
// By http://git.io/cgogen. DO NOT EDIT.

package vulkan

/*
#cgo CFLAGS: -I. -DVK_USE_PLATFORM_ANDROID_KHR -DVK_NO_PROTOTYPES
#include "vulkan/vulkan.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
